.github/labeler.yml, .github/workflows/label.yml
The labeler in this repo is currently broken - this PR changes the config to match what we have in https://github.com/instructlab/taxonomy which is currently working
=> ci: fix labeler permissions and identation

src/instructlab/generator/generate_data.py
Today `ilab generate` creates a large percentage (> 50% in my testing) of discarded examples because the examples do not match our expected format. Typically, the model fails to follow our complicated numbering scheme for instructions, inputs, and outputs. This change simplifies that scheme, taking inspiration from Emacs org-mode without any rigid adherence to it.
Before this change, we expected the model to continue a format like:
```
1. Instruction: Generate a joke involving three horses.
1. Input:
<noinput>
1. Output:
There once were three horses...
```
After this change, we now give the model:
```
* Task 1
** Instruction
Generate a joke involving three horses.
** Input
<noinput>
** Output
There once were three horses...
```
In my local testing, the model is able to replicate our new …
=> Reduce number of discarded generated data samples

src/instructlab/train/linux_train.py
Remove this interaction from linux train, it was part of the Notebook that linux_train.py was based on, we're not looking at the output so it shouldn't be needed.
Fixes #897
=> Remove the interaction test about "Barter Town"

src/instructlab/config.py, src/instructlab/generator/generate_data.py, src/instructlab/server.py, src/instructlab/train/linux_train.py
Resolves #956
Multiprocessing uses `fork` as default start method on Linux. Windows and macOS default to `spawn`. The `fork` method is not safe in multi-threaded environments. It is also incompatible with some hardware accelerators.
Use `spawn` on all platforms.
=> Use 'spawn' multiprocessing method instead of fork

tests/test_lab_generate.py
The test case was reading from `generated` directory in the current path, not a temporary directory dedicated for the test case.
=> tests: fix test file system not isolated

.github/workflows/test.yml, CONTRIBUTING/CONTRIBUTING.md, Makefile, tox.ini
The previous `tox.ini` used fixed testenvs that used the default `basepython`, which typically points to `python3`. It was not easily possible to run tests with another Python version.
The new configuration uses tox's matrix configuration feature. The default targets for tests are now `py3-unit`, `py3-unitcov`, and `py3-functional`. These targets use `python3` as base Python. With the new configurion it's now possible to run tests with different Python versions. For example `tox -e py39-unit` runs unit tests with `python3.9`.
Tox is also configured to use wheel with a common wheel env for sdist and binary wheel dist. This speeds up purelib wheel creation.
=> Use matrix configuration for tox

tests/conftest.py, tests/test_lab_train.py
See #814
Tests now use a pytest fixture to mock-patch the mlx package. This resolves a problem with my old `mock_mlx` wrapper, which broke testing with Python 3.9 and 3.10
Kudos to Ihar Hrachyshka for discovering the problem and reporting it in issue #814.
=> Use pytest fixture to mock mlx package

tests/test_lab_train.py
Test code was writing {} in the file but this results in an empty dict() produced by json.load, which would later fail with KeyError('user') in make_data.
The reason why this doesn't show up in the test runs is because make_data is mocked out. This test bug was noticed while working on another fix for the test suite where mocks were not effective [1].
While the test suite was not failing (because of mocks), it's still better to inject data that conforms to loader expectations.
[1] https://github.com/instructlab/instructlab/pull/890
=> tests: fix input data file contents

scripts/functional-tests.sh, src/instructlab/server.py
When we simply run `ilab chat`, a temporary server will run in the background and we can enjoy a great chat. However, if the chat response is interrupted with ctrl+C, the signal will be caught by uvicorn and then the server will be killed making further chat impossible and printing a large backtrace.
Another option was to run the temp server in a dedicated thread but this requires a bit more changes as well as the difficulty of handling the thread termination. This would have been handled by uvicorn natively since it is not setting up any signal handler but would still require us to handle it manually in our code.
Resolves: https://github.com/instructlab/instructlab/issues/883
=> fix: ignore SIGINT when running the temp server

src/instructlab/lab.py, src/instructlab/server.py
Related to #957
Use default multiprocessing default context for `ensure_server` to unblock contributors. For some unknown reasons, `spawn` does not work.
`ensure_server` uses a multiprocessing Process to run a server process. The exit path must wait for the process to finish after `p.terminate()`. Otherwise the parent process might go away before the client can signal the parent that it is gone.
=> Use default context for ensure_server

README.md
**Description:** Size limit was documented in taxonomy in https://github.com/instructlab/taxonomy/blob/main/README.md?plain=1#L49
Adding same text to CLI readme
#782
=> Doc: Document key pair size in cli

README.md
This was removed weeks ago during an update of the README. The code still exists and it still works.
Fixes #156
=> Restore the note about regen.json

scripts/functional-tests.sh, src/instructlab/lab.py
Lately, more INFO messages have appeared in the chat, so let's set the log level to ERROR only on the openai and http clients.
Without this change:
```
$ ilab chat
INFO 2024-04-16 11:49:33,283 _base_client.py:1040 Retrying request to /models in 0.911925 seconds
INFO 2024-04-16 11:49:34,197 _base_client.py:1040 Retrying request to /models in 1.571945 seconds
```
A more granular control over the log levels for various libraries will be implemented in a follow-up PR. That enhancement is tracked in https://github.com/instructlab/instructlab/issues/905.
Resolves: https://github.com/instructlab/instructlab/issues/909
Signed-off-by: Sébastien Han [seb@redhat.com](mailto:seb@redhat.com)
=> fix: openai and http log level

tox.ini
pyspelling defaults to aspell, although it supports both 'aspell' and 'hunspell'. However 'hunspell' reports a lot more issues than 'aspell'. It will be hard to maintain both, so let's enforce 'aspell'. Also, the GitHub action uses 'aspell'.
=> fix: force aspell spellchecker

Makefile, README.md, containers/cuda/Containerfile, docs/containerization.md, docs/demo-slides.md, docs/gpu-acceleration.md
HTTPS has much lower chances to be blocked in certain internal networks as well as more resilient to having issues with changing ssh keys on a GitHub server side.  HTTPS is also the default method recommended by GitHub.
Passing around ssh keys is also not needed anymore.
Resolves #
SSH access replaced with HTTPS everywhere in docs and the code.
This was originally submitted as https://github.com/instructlab/instructlab/pull/663 , but since the org and the repo got renamed I couldn't re-open that PR, so sending a new one.
=> Prefer https over git and ssh protocols for repo cloning.

.github/workflows/stale_bot.yml
This PR adds a stale issue bot similar to what we have in the `taxonomy` repo: https://github.com/instructlab/taxonomy/blob/main/.github/workflows/stale_bot.yml
This is also a proposal of sorts - if we feel this isn't something worth having in this repo, I'm happy to close it.
=> ci: add stale issue/PR bot

.github/workflows/test.yml, tox.ini
Resolves #983
- use `tox-gh` to run tests for each Python env
- use `setup-python`'s pip cache instead of our own home-grown solution. It's nearly as fast as caching a tox env and less brittle.
- cache 4GB model from huggingface
- test on Ubuntu / Python 3.9, 3.10, 3.11, and 3.12
- test on macOS ARM64 / Python 3.11 (only unit tests, functional shell script does not work on macOS)
=> Test with multiple Python versions

containers/cuda/Containerfile
The libcudann8 container needs to be installed in the container or
else we see errors like this one:
File "/usr/local/lib64/python3.11/site-packages/torch/__init__.py", line 237, in <module>
from torch._C import *  # noqa: F403
^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
And in order to find devices in torch:
$ python3.11
>>> import torch
>>> torch.cuda.device_count()
1
The above returns zero without nvidia-driver-NVML
=> containers: cuda contianer needs libcudann8 and nvidia-driver-NVML

.github/labeler.yml, .github/mergify.yml
commit 50b1799d725aaca21d651572512f34fa4fd31cf3
Date:   Fri Apr 26 12:39:38 2024 -0400
mergify: Don't require lint & test on github config changes
The previous config was excpecting the lint and test jobs to run and
pass on PRs taht only changed files under `.github/`, but those PRs
won't run those jobs.
=> mergify: Fix config for changes to github workflows

containers/cuda/Containerfile
commit 78fe3c8f4033dcd104da631d37636df5bb1497b0
Date:   Fri Apr 26 15:52:24 2024 -0400
containers: Add nvidia-driver-cuda-libs to cuda image
This was called out by @stefwalter on #1018. He did that PR and
commented after it merged that this is needed as well.
=> containers: Add nvidia-driver-cuda-libs to cuda image

containers/cuda/Containerfile
The current cuda builds of instructlab are unaccelerated for serve/generate
Sync requirements.txt of  llama_cpp_python with instructlab
The step which pip installs llama_cpp_python is overwritten by the instructlab install since the instructlab has a pinned version that is lesser than the preceding llama_cpp_python. Since the instructlab install does not specify the cuda CMAKE args it gets rebuilt without cuda support. By aligning requirements we ensure that  llama_cpp_python will not be rebuilt.
Before this change:
```
>>> llama_cpp.llama_supports_gpu_offload()      
False
```
After:
```      
>>> llama_cpp.llama_supports_gpu_offload()      
True
```
=> Fix llama_cpp cuda usage in Containerfile

pyproject.toml, scripts/functional-tests.sh, src/instructlab/utils.py, tests/testdata/invalid_yaml.yaml, tests/testdata/knowledge_valid.yaml, tests/testdata/skill_incomplete.yaml, tests/testdata/skill_invalid_answer.yaml, tests/testdata/skill_valid_answer.yaml
Resolves #989
We introduce a relaxed schema as v1 which will accept all existing
taxonomy files in the main branch of the taxonomy repo. The current
v1 schema is renamed to v2 and will be used for future contributions
to the taxonomy repo.
Fixes https://github.com/instructlab/instructlab/issues/989
Depends on https://github.com/instructlab/instructlab/pull/913
and https://github.com/instructlab/schema/pull/11
=> Define a relaxed schema as v1 and move current schema to v2

.github/mergify.yml, .github/workflows/test.yml
Instead of creating dependencies on specific test jobs, make a final job that depends on the others that can be referenced instead. This will simplify mergify configuration.
=> github: Add a test-workflow-complete job

.github/workflows/pypi.yaml
See #972
Packages are now automatically published to PyPI using GitHub Actions and PyPI's [Trusted
Publisher](https://docs.pypi.org/trusted-publishers/) workflow.
On PR merge to main branch event, a dev package like `instructlab-0.13.1.dev47+g666a84f` is pushed to Test PyPI. The version number means "47 commits after 0.13.0 tag at git commit 666a84f". This job lets us test the release and publishing workflow. It gives our users an easy way to install in-development wheels from https://test.pypi.org.
On release publish event, a new release version is signed with sigstore and pushed to production [PyPI](https://pypi.org).
I have already configured the `instructlab` project on PyPI and Test PyPI for trusted …
=> Enable PyPI publishing and sigstore signing

.github/workflows/pypi.yaml
Test PyPI does not accept `dev` builds with local version. Disable push on PR merge for now.
> The use of local versions in <Version('0.14.1.dev11+g12e0386')> is not
> allowed. See https://packaging.python.org/specifications/core-metadata
=> Disable push to Test PyPI on merge

src/instructlab/lab.py
the code pulls from the env HF_TOKEN not from --hf_token
(cherry picked from commit 21b8eefbd03c4aca9af68e429a33561132ad636d)
=> --hf-token flag is not used in .14 release

.github/mergify.yml
- **mergify: Keep auto merge rule at the top**
- **mergify: Automatically apply backport label**
commit af7562a584fec812998df5474a2a3176960e0c3f
Date:   Tue Apr 30 14:17:04 2024 -0400
mergify: Keep auto merge rule at the top
This lets us keep all the labeling related rules together.
commit 3d4a2511d6bcf5cb80ffd23a9dc2df88c770d1e4
Date:   Tue Apr 30 14:18:46 2024 -0400
mergify: Automatically apply backport label
Apply the backport label to all PRs posted against release branches.
=> Automatically apply a backport label to release branch PRs

src/instructlab/utils.py, tests/test_utils.py, tests/testdata/testdata.py
While we still prefer chunking on paragraphs and newlines, also allow chunking documents on spaces to handle cases where markdown files have really long lines so that we don't blow up the context window.
This change adds a test for the same that asserts our chunked documents are under an expected size. The test failed before adding the chunking on spaces and passes afterwards.
Fixes #968
=> Chunk docs on spaces for really long lines

src/instructlab/lab.py
Adds help string to `--hf-token flag` in `ilab download` command
=> Fix: Add help string to hf-token flag in download

src/instructlab/lab.py
The code check in https://github.com/instructlab/instructlab/blob/main/src/instructlab/lab.py#L721 will not be satisfied even if you pass non "instructlab" repository unless you pass the flag ` --hf-token ""` also. This is because the default is not set. This sets the default.
Test before and after with the following command: `ilab download --repository XXX/granite-7b-lab-GGUF --filename  granite-7b-lab-Q4_K_M.gguf`
=> fix: Add hf-token default to fix checking error

scripts/functional-tests.sh
The test does not need to listen on 8000 to active the temp server. The
temp server will run if 8000 is not present and choose a random port to
listen on. The `nc` line was not needed.
Fixes: https://github.com/instructlab/instructlab/issues/977
=> fix: remove useless nc command

pyproject.toml
Use Ruff's tidy import linter to ban import of `yamllint`.
Example output:
```raw
src/instructlab/lab.py:24:8: TID251 `yamllint` is banned: yamllint is for CLI usage only.
```
=> Ban import of yamllint

.github/mergify.yml
When setting a label to a PR, if it matches 'backport-release-v014' Mergify will automatically create a backport PR in the configured stable branch.
I've found this approach easier than writing a comment to a PR, also we can visually see if a PR made it in a release branch by looking at the label.
The only condition is to create the label.
=> feat: use labels to trigger backports

.github/mergify.yml
In #1074, we added a new way to trigger backports using backport
labels. To help avoid confusion, rename this label to reflect which
PRs are against release branches.
=> mergify: Rename backport label to release-branch

src/instructlab/lab.py
This is known to be broken, per issue #579. Instead of failing,
exit cleanly before we know it will fail, but print a message
noting what was skipped, along with a link to the issue.
=> linux-train: Skip convert to gguf when --4-bit-quant is used

.markdownlint-cli2.yaml
Pulls the latest schema commit whereby the schema linting has been fixed. Also, disables linting of schema in this repo as it should be linted in its own repo.
=> Fix broken md linting in schema submodule

README.md
The arg `--model` is not supported. The correct arg is `--model-path`.
A related error,
`Error: No such option: --model`
=> Update the --model arg

scripts/functional-tests.sh, src/instructlab/server.py
Our server can now be identified easily by fetching the root of the API:
```
curl 127.0.0.1:8000/                                                                   ✹
{"message":"Hello from InstructLab! Visit us at https://instructlab.ai"}%
```
Fixes: https://github.com/instructlab/instructlab/issues/1094
=> feat: add a welcome message to our server root

.github/workflows/test.yml, .spellcheck-en-custom.txt, CONTRIBUTING/CONTRIBUTING.md, scripts/functional-tests.sh
The CI will now run the functional test on a MacOS runner. The testing script was changed to accommodate MacOS.
Fixes: #802
Co-authored-by: Mark Sturdevant <mark.sturdevant@ibm.com>
=> feat: run functional test on MacOS

src/instructlab/generator/generate_data.py, src/instructlab/lab.py, src/instructlab/server.py, src/instructlab/train/linux_train.py
Python multiprocessing does not allow th change the default start method when another code path has already configured a default start method. Even `get_start_method` or `get_context` sets a default context.
I was running into this exception when doing training with some hardware accelerator frameworks like Habana.
```python
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```
---
After fixing the issue above, we were still seeing multiprocessing-related bugs exposed via CI. We went through and made several other changes ensuring that resources were …
=> Don't fail if multiprocessing is already set to spawn; fix issues from lack of cleanup

README.md
Demo is out of date - a current release badge probably makes more sense to have
=> docs: replace 0.13.0 demo badge with current release badge

.github/actionlint.yaml, .github/workflows/e2e.yml, docs/ci.md, scripts/basic-workflow-tests.sh, scripts/test-data/basic-workflow-fixture-qna.yaml
This PR introduces a new job that runs in CI that performs a minimal
configuration of the `ilab` workflow:
- `ilab init`
- `ilab download`
- `ilab serve`
- `ilab generate`
- `ilab train`
It runs on a GPU-enabled github actions runner. This is a Linux VM
with a single Tesla T4 GPU.
Given the resources required to run this job, we do not propose that
it runs automatically on every PR. Instead, it is a workflow that must
be manually launched. When launching it manually, you can specify
which branch or pull request to run it against.
Signed-off-by: Stef Walter <stefw@redhat.com>
Co-authored-by: Russell Bryant <rbryant@redhat.com>
---
Depends on:
Related:
---
Follow-up work after this PR:
- Make another variant of this job that builds our …
=> Introduce an end-to-end CI job on Linux

.github/workflows/image-cuda.yml, containers/cuda/Containerfile
- **containers/cuda: Allow specifying git branch to build from**
- **ci: Add a job that does test builds of the cuda image**
commit 971994d1df8a12e47cc00d3b94c11e8c0961054f
Date:   Sat Apr 27 21:07:59 2024 -0400
containers/cuda: Allow specifying git branch to build from
This PR adds a new arg to the cuda Containerfile to specify which
instructlab git branch to build from. The default stays the same,
using `stable`.
commit d6134622e3a64e215e45a39afd23c48723d31d70
Date:   Thu May 2 16:53:20 2024 -0400
ci: Add a job that does test builds of the cuda image
If the file `containers/cuda/Containerfile` changes, do a test build
of it against `main` and …
=> Do test builds of the cuda image in CI

src/instructlab/lab.py
Deletes intermediate model conversion outputs during `ilab convert` on macOS
Resolves #
Currently `ilab convert` on macOS is very wasteful in terms of storage space - there is a lot of duplication of large model files during the conversion from mlx safetensors to pyTorch safetensors and then to GGUF format before finally quantizing it 
This PR deletes all the intermediate files except the final trained, quantized GGUF model
=> chore: clean up intermediate output during MacOS convert

.github/workflows/pypi.yaml
Sviatoslav pointed out that our permissions are too broad. Only grant id-token and content write rights in the release jobs.
=> Use fine-grained permissions for PyPI

src/instructlab/train/linux_train.py
When using cuda and performing the VRAM check, the value was being passed was either 11 or 17 and was meant to be an expession of gibibytes. However, it was never converted to bytes before the comparison and therefore always evaluated to true because torch.cuda.mem_get_info(device)[0] returns a value expressed in bytes. This patch does the conversion to bytes before the comparison.
=> fix four_bit_quant VRAM check for cuda

.spellcheck-en-custom.txt, README.md, docs/containerization.md, docs/demo-slides.md, docs/gpu-acceleration.md
Our docs around GPU support have some rough edges. Users have been running into issues because they replaced their GPU accelerated llama-cpp-python with a slow CPU version. Pip also has some sharp edges concerning package name normalization.
- hard-code `llama_cpp_python` (sic!) version for now, so users will get the right version. I'll replace the docs with better ones after Summit.
- remove cached builds rather than disabling the cache, so pip can use its source cache to speed up builds.
- use pip's `--config-settings / -C` option to pass cmake arguments
- use ROCm 6.0
Resolves #
=> Docs: Improve instructions for hardware acceleration

src/instructlab/lab.py, tests/test_lab_train.py
Instead of returning the out of range error let's make it more human-readable.
Fixes: https://github.com/instructlab/instructlab/issues/1084
=> fix: cleaner message when generate dir is empty

src/instructlab/chat/chat.py, src/instructlab/config.py, src/instructlab/lab.py
This patch add the option to pass max_token OpenAI API parameter to ilab chat to limit the number of tokens to be generated. This can be useful in low performance devices or with large models
=> Add option to include max_tokens for the ilab chat

src/instructlab/lab.py
`ilab generate` without hardware acceleration is very slow. Notify the user when llama_cpp is not compiled with GPU or other accelerators. `llama_supports_gpu_offload` does not check whether a device is available or GPU offloading actually works.
=> generate: warn when llama_cpp has not hardware acceleration

.github/workflows/e2e.yml, .github/workflows/lint.yml, .github/workflows/test.yml, requirements.txt, tests/test_lab.py
Prevent any job from caching a llama-cpp-python wheel. It looks like a cached CUBLAS build from `e2e` test can leak into other tests that do not have the CUDA system libraries installed.
pip does not have an option to force a rebuild of a single package that has been locally cached. `--no-binary` applies to downloads but not to binary wheels in local cache. Purge `llama_cpp_python` wheels from cache after setup-python has populated pip's cache. Also remove the wheel before a job finishes.
Also refactor lint job to use the same caching and add constraints to a couple of packages to trigger the bug.
=> Do not cache llama-cpp-python builds

src/instructlab/chat/chat.py
Seeing:
```
>>> /q
[S][default]
Aborted!
```
This is ugly, due to the `raise`. This change fixes the exit to a 0 exit, removing the aborted warning.
=> Clean exit from the chat.py

tests/test_config.py, tests/test_lab.py, tests/test_lab_diff.py, tests/test_lab_download.py, tests/test_lab_generate.py, tests/test_lab_init.py, tests/test_lab_train.py, tests/test_utils.py
Tests now use modern pytest style instead of old `unittest.TestCase`. This has multiple benefits. Test code is easier to read. Pytest fixtures in functions now work. Test failures now show error context and local variables.
The code was automatically fixed by `pytestify==1.5.0`. ExceptionInfo was manually fixed to `str(exc.value)`.
=> Use pytest instead of unittest.TestCase

src/instructlab/chat/chat.py
Instead of doing `sys.exit(0)` directly, generate a custom exception
and return cleanly from the chat handler so that the code in
`src/instructlab/lab.py` can handle necessary cleanup, which includes
potentially cleaning up an automatically launched temporary model
server in the background.
=> chat: Ensure temp server is cleaned up after quit command

src/instructlab/lab.py, tests/test_lab_diff.py, tests/test_lab_download.py, tests/test_lab_generate.py, tests/test_lab_init.py, tests/test_lab_train.py
Functional tests now behave more like actual click CLI. Tests cases no longer run the subcommand function directly. Instead they invoke the cli main entry point and delegate the subcommands to click.
The config file is now parsed in the main cli entry point instead of the option's validation callback. The `ctx.obj` is created in the entry point, too. The change was necessary because click's CliRunner does neither update `sys.argv` or set `ctx.invoked_subcommand` for the callback. IMO it's also a nicer design.
=> Refactor CliRunner tests

scripts/basic-workflow-tests.sh
Every time we log a new step in the script, include a timestamp. This
should help with seeing how long each piece is taking within the
script.
This came up in discussion on #1111.
=> e2e: Add timestamps to the test script

.spellcheck-en-custom.txt, README.md
Someone asked me this week about `ilab` tab completion. Click has built-in support for this. This adds the documentation on how to enable it either temporarily or permanently.
This change also includes an automatic update to the table of contents at the top of the document.
=> ilab: Document how to enable tab completion

requirements-dev.txt, src/instructlab/config.py, tox.ini
If the specified log level in the config file is incorrect we return an
error and print the allowed levels.
Sadly, only Python 3.11+ supports logging.getLevelNamesMapping that
could be used to get the exhaustive list of supported level names. So we
maintain our own for the time being.
Fixes: https://github.com/instructlab/instructlab/issues/1091
Co-authored-by: Ihar Hrachyshka <ihrachys@redhat.com>
=> fix: handle incorrect log level

tests/test_config.py
As requested in
https://github.com/instructlab/instructlab/pull/1092#pullrequestreview-2048991277 adding some unit tests to validate the "validate_log_level" function.
=> fix: add unit test for config log level

src/instructlab/lab.py, tests/taxonomy.py, tests/test_lab_diff.py
Resolves #796
The logic is organized so there is not separate work paths for quiet and non-quiet. The code now properly identifies and handles single files.
An exception in the non-quiet code when reading the repo now results in a failing exit code.
=> diff: Rework --quiet logic and handle file without needing --quiet

scripts/functional-tests.sh, src/instructlab/chat/chat.py
Closes #948
Always pass logger to `start_prompt`.
=> chat: fix AttributeError crash on -qq with short context

src/instructlab/config.py
The pydantic models for config file were using `typing.Optional` the wrong way. `Optional[T]` is syntactic sugar for `Union[None, T]` and refers to an optional value that can be `None`. It is not the same concept as an optional argument with a default value.
=> Fix use of `typing.Optional` in config parser

.github/mergify.yml
As previously discussed, now that Summit is over we want to require 2 reviews for merging PRs instead of 1
Once this is in I will change the GitHub repo settings as well
=> Change mergify automation to require 2 approving reviews for auto-merge

.github/workflows/pypi.yaml, docs/habana-gaudi.md, pyproject.toml, requirements-hpu.txt
Resolves #1054 
Disable setuptool-scm's local version tag. Test PyPI does not accept packages with a local version. By default setuptools-scm includes `+g{GITREVISION}` in the version.
Enable dev uploads to Test PyPI again.
Disable optional dependency `instructlab[hpu]`. Intel Gaudi support currently requires a fork of optimum-habana from git. PyPI does not accept packages with a direct dependency.
=> Fix PyPI release issues

.github/workflows/actionlint.yml
Was digging into why https://github.com/instructlab/instructlab/pull/1166 wasn't automerging and it seems this typo is to blame
=> ci: fix typo in actionlint workflow

.github/mergify.yml
When I pull up the PR queue to do some reviews, having data to filter on helps me prioritize which PRs to look at first. Sometimes I want to filter out any PRs where CI isn't passing to help narrow down the list to the ones most likely to be ready for approval.
This PR makes mergify automate adding and removing the `ci-failures` label based on if there are any checks currently failing.
=> mergify: Automate a label for CI failures

src/instructlab/utils.py
Resolves #1170 
The top-level element of a yaml document can be an object (key-value pairs) or a list. We now test and provide an error message if the top-level element is not an object.
=> validation: Confirm yaml file contents are an object

.github/mergify.yml
If a PR has been approved already by one of the maintainers, the PR will be labeled with 'one-approval'. This is useful for maintainers to help them determine which PR is getting close to completion and thus prioritize the review.
With the help of filters, one can look for PRs that have one approval already.
=> ci: add 'one-approval' label on PR that has one approval

README.md
I just had a conversation on Slack where a user attempting to install
on an Intel Mac got a build error because it was trying to build with
Apple M-series GPU support. Adding an explicit build instruction to
disable that support made the build successful. Add this to the
install docs.
=> README.md: Add a build note for Intel Macs

.github/ISSUE_TEMPLATE/team_recommend.md
Our [contribution roles](https://github.com/instructlab/community/blob/main/CONTRIBUTOR_ROLES.md) document states that to nominate organization members to teams, a GitHub Issue must be opened for the nomination. This PR introduces a template to do so with.
=> Create issue template for nominating members for teams

scripts/functional-tests.sh, src/instructlab/lab.py, src/instructlab/sysinfo.py
The new `ilab sysinfo` command prints various system information related to the operating system, PyTorch, accelerators and llama-cpp. The output is useful for debugging issues.
```shell
$ ilab sysinfo
instructlab.version: 0.14.1.dev152+g3e610c1.d20240508
sys.version: 3.11.7 (main, Jan 22 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
sys.platform: linux
os.name: posix
platform.system: Linux
platform.release: 5.14.0-362.8.1.el9_3.x86_64
platform.machine: x86_64
os-release.ID: rhel
os-release.VERSION_ID: 9.4
os-release.PRETTY_NAME: Red Hat Enterprise Linux 9.4 (Plow)
torch.version: 2.3.0+cu121
torch.backends.cpu.capability: AVX512
torch.version.cuda: 12.1
torch.version.hip: None
torch.cuda.available: True
torch.backends.cuda.is_built: True …
```
=> Add `ilab sysinfo` command

src/instructlab/chat/chat.py, src/instructlab/client.py
Resolves #864
This PR does the following:
- Adds `__init__.py` to the `chat` module, which was previously preventing `chat.py` from getting linted
- Fix lint errors in `chat.py` - I've added folks that previously touched this file to ensure I didn't break anything, can run an E2E job on this as well if folks feel it is worth it
=> fix: add chat module to linting and fix errors

Makefile
Example of before/after below
```bash
[nathan@nathan-redhat instructlab (make-help)]$ make help
Usage:
make <target>
General
help             Display this help.
Build
images           Get the current controller, set the path, and build the Containerfile image. (auto-detect the compatible controller)
cuda             Build container for NVidia CUDA
hpu              Build container for Intel Gaudi HPU
rocm             Build container for AMD ROCm (auto-detect the ROCm GPU arch)
rocm-gfx1100     Build container for AMD ROCm RDNA3 (Radeon RX 7000 series)
rocm-gfx1030     Build container for AMD ROCm RDNA2 (Radeon RX 6000 series)
rocm-gfx90a      Build container for AMD ROCm gfx90a (untested)
rocm-gfx908      Build container for AMD ROCm gfx908 (untested)
rocm-gfx906      Build container for …
```
=> fix: update make help text

src/instructlab/lab.py, tests/test_lab_train.py
In order to allow ilab to run e2e on colab where diskspace is limited we move rather then copy large files around, also rm files we're done with to save space for the next step.
Fix #1011
=> More efficiently use diskspace

scripts/functional-tests.sh, src/instructlab/chat/chat.py
This is a partial revert of https://github.com/instructlab/instructlab/commit/b8c9e63c550d07369f5381eb92b5285440cfa24b
which removes the unused 'content' argument of the `_handle_quit()`
function signature. Most of the time the function is not called with two
arguments unless the user types 'exit' in the chat, then `_handle_quit()`
is called with two arguments and we get:
```
TypeError: ConsoleChatBot._handle_quit() takes 1 positional argument but
2 were given
```
To avoid linters complaining about an argument not being accessed we use
the  `_` keyword.
Fixes: https://github.com/instructlab/instructlab/issues/1196
=> fix: do not fail when sending 'exit' to the chat

.github/workflows/e2e.yml
ced8c71 e2e: Fix build error after cuda upgrade
commit ced8c7110791cf396398b4cfeb9ce9a6e5a6c097
Date:   Wed May 22 10:04:59 2024 -0400
e2e: Fix build error after cuda upgrade
Don't embed the CUDA version in the path. Symlinks are in place so
`/usr/local/cuda/` is fine.
=> Fix CUDA path to account for update

README.md
The output from `ilab convert` command has changed. This PR fixes the README content to explain the output from the command.
=> Docs: Fix converted output

containers/README.md, containers/cuda/Containerfile
- Fixes ARM64 build for the containerfile
- Bump cuda:12.4.1-devel-ubi9 to the latest
=> Add ARM64 support to the Containerfile example

src/instructlab/lab.py, src/instructlab/log.py, src/instructlab/server.py, src/instructlab/utils.py
Our logger now includes the llamap_cpp logs instead of printing to stderr and stdout, making the logs hard to read and parse. It looks like llma_cpp print debug messages to stderr instead of stdout so the startup logs look a little bit confusing when setting our log level to DEBUG.
=> feat: redirect llama_cpp server stderr/stdout to a logger

README.md
[PyPi package](https://pypi.org/project/instructlab/) is being built since v0.15.1.
This PR updates the instructions to install from package instead of the GitHub repo.
Resolves #1208
=> docs: Update install for pypi package

src/instructlab/generator/generate_data.py, src/instructlab/utils.py, tests/test_lab_generate.py, tests/testdata/skill_too_long_answer.yaml
This calculates a maximum number of characters per seed instruction example based on the configured server context size as passed to `ilab generate`. Before starting the generation, we verify that none of the examples we're going to use exceed this limit. If they do, we fail generation with a helpful error message.
When adding generated responses to our list of seed examples, we do a similar check of the response length. If the response is too long, we skip adding that particular response to our list of seed examples so that we don't end up adding really long machine-generated responses to our seed examples and blowing our context size that way.
Helps #1024 but doesn't entirely fix all sources of exceeding our context.
=> Enforce maximum length in generate seed examples

src/instructlab/chat/chat.py
Resolves #https://github.com/instructlab/instructlab/issues/1236
chat.py: def _handle_help(slef) missed one parameter even it does not use it. Update to def _handle_help(self, _)
=> fix ilab chat run /h command failed issue

notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
Improvements of notebook results:
1. Shorter, cleaner and more maintainable code and output.
2. Markdown format of output is suitable for copy-paste to PR.
3. Pre-trained text is truncated because usually it is hallucinated and not valuable. It is only used as baseline to see improvement of fine-tuned results.
4. Pre-trained text written in italic font to distinguish it visually from provided in qna.yaml and fine-tuned.
=> notebook: more clean results code and output

.github/mergify.yml
The file is `e2e.yml` not `e2e.yaml`.
Failure run:
https://github.com/instructlab/instructlab/pull/1211/checks?check_run_id=25741927743
=> mergify: fix e2e workflow file name

docs/demo-slides.md
The current link still points to the old repo.
=> docs: fix link to repo in demo-slides

src/instructlab/generator/generate_data.py
Calling `get_context()` with an arg of `DEFAULT_MULTIPROCESSING_START_METHOD`
is not necessary. The parent `lab.py` is already setting the default
before this code runs. Calling `get_context(None)` will return a
context using whatever the current default is set to.
This removes one bit of coupling from this sdg code and the rest of
the CLI, making it easier to extract into a library.
=> sdg: Remove unnecessary config access

scripts/functional-tests.sh
The test seems to fail intermittently, so let's try to push the timeout to 20m as well as printing a clear indication of why the functional test is going to fail.
Failure example: https://github.com/leseb/rook/blob/bcd2511a7269ceb72c5c4a255fa760de85dea1e1/pkg/operator/ceph/cluster/osd/spec.go#L169-L182
=> ci: try to fix flaky test_generate() functional test

.github/mergify.yml, .github/workflows/shellcheck.yaml, containers/rocm/remove-gfx.sh, scripts/basic-workflow-tests.sh, scripts/functional-tests.sh
All our bash scripts are now passing the shellcheck linter.
=> fix: make all bash script pass shellcheck

scripts/functional-tests.sh, src/instructlab/lab.py, src/instructlab/log.py
Using --log-file, we can now write the server logs to a file. It's
going to be useful once we introduce support for systemd unit as well as
launchd. Also, having a log file is crucial step toward production
deployments and system integration.
Note that while --log-file is used, `ilab serve` will continue to log on
the foreground so if running inside a container you can get the
container log stream as well as a file.
=> feat: ability to log server to file

.spellcheck-en-custom.txt, CHANGELOG.md, docs/release-strategy.md
From now on, let's get into the habit of editing the
`CHANGELOG.md` file on PR adding notable features and/or
breaking changes that users need to be aware of.
=> introduce a release note for release

.github/workflows/e2e.yml
The current flow was assuming the 'gh' CLI was present, we now install and configure it. Also, we remove the git usage since using gh is shorter.
Failing run error:
```
/home/runner/work/_temp/09f60100-6344-4e59-add5-004d08de3070.sh: line 1: gh: command not found
```
Link: https://github.com/instructlab/instructlab/actions/runs/9353362921/job/25743665032
=> ci: install gh cli on e2e runner

.github/workflows/e2e.yml
The workflow is trying to comment on PRs when run against a PR number,
but this currently fails due to a lack of permission to do so.
=> e2e: Give e2e workflow write access to PRs

src/instructlab/generator/generate_data.py, src/instructlab/lab.py, src/instructlab/llamacpp/llamacpp_convert_to_gguf.py, tests/test_lab_train.py
This is code cleanup (see each commit message in the series for details of what is done and why). It also fixes a `NameError` issue when `data-dir` is passed on linux (found the issue during code cleanup).
=> Misc code cleanup in lab.train endpoint

src/instructlab/chat/chat.py, src/instructlab/client.py, src/instructlab/generator/utils.py, src/instructlab/utils.py
httpx.Client expects cert argument to be one of: a 2+ tuple, or a string, or None.
Before the change, we were passing a 1-tuple when only the cert file was configured through cli, which is violating the typing requirements of the library; and it also made the library not initialize SSL context at all. See:
https://github.com/encode/httpx/blob/37593c1952f4972040f6163da67e3777fd3d2e94/httpx/_config.py#L183
=> chat: Fix ssl when only cert file is passed

src/instructlab/lab.py, tests/test_lab_train.py
73401138f2e8122a305dd7b3407673b68c0c824a made `train_file` and `test_file` a `Path` instead of `str`. Now when `load_dataset()` is called we get the following error:
```
LINUX_TRAIN.PY: LOADING DATASETS
File "/home/runner/work/instructlab/instructlab/venv/bin/ilab", line 8, in <module>
sys.exit(cli())
^^^^^
File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/home/runner/work/instructlab/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
return …
```
=> fix: train and test files not being iterable

.github/workflows/e2e.yml
Add GitHub Actions steps to comment on PRs based on e2e workflow success
or failure.
=> e2e workflow: add success/failed comments on PR 

src/instructlab/lab.py, src/instructlab/train/linux_train.py, tests/test_lab_train.py
The linux_train function defines these arguments as `str`, but we are now passing lists of strings. The `load_dataset` function down the stream accepts either a `str` or a sequence of strings.
This patch changes the type of the arguments to `Path` since it's a stronger type. It then converts to string before passing it further to `load_dataset`.
This also reverts a test case change that made the check ineffective because it no longer validated what the code under test did (instead checking that pathlib library behavior is valid.)
This is a follow-up to e1d59105.
=> train: fix type violation when passing test_file and train_file

pyproject.toml
These were tackled by:
https://github.com/instructlab/instructlab/pull/1234
=> mypy: clean up client.py and chat.py from excludes

src/instructlab/__init__.py
The new `sdg` repository includes a new Python library. The current
consensus on the following issue is that it should be published as a
Python namespace package, `instructlab.sdg`.
This magic snippet is required to allow this. See the discussion on
the issue for further discussion:
https://github.com/instructlab/sdg/issues/2
=> Support namespace packages under `instructlab`

src/instructlab/log.py
Add a colon after `lineno` because it is a widely used convention since `grep`.
=> Log funcName

.github/PULL_REQUEST_TEMPLATE.md
This commit introduces a new template for pull requests. The template includes sections for a description of the changes, the issue number being resolved, and a checklist for commit message formatting, updating release notes, and adding necessary documentation and tests.
=> feat: add new pull request template

.github/workflows/shellcheck.yaml
Mergify could not merge PRs touching shell scripts because it is configured to merge when the "shellcheck" job succeeds. However, the job name was starting with a capital letter.
**Checklist:**
=> ci: fix shellcheck job name

README.md
Especially in old M1/M2 devices, python build could be x86 based instead of arm64, which does not let llama.cpp to use metal. Edited the readme to ensure the user can check for it before attempting the build.
**Checklist:**
=> Updated the readme section for M1/M2/M3

src/instructlab/lab.py
The list of aliases below the Aliases header should be indented.
Resolves #1324 
**Checklist:**
=> fix: Indent help epilog alias list

src/instructlab/model/train.py
The fix is output right trained model path on linux.
Resolves #https://github.com/instructlab/instructlab/issues/1289
**Checklist:**
=> fix: output right trained model path

src/instructlab/configuration.py, src/instructlab/lab.py
`ìnit_config()` is already part of the `config` package so it's redundant to call it `init_config()` especially when calling the import like so, `config.init_config()`.
Closes: https://github.com/instructlab/instructlab/issues/1323
**Checklist:**
=> refactor: rename init_config to init

scripts/functional-tests.sh
The log error message was a bit lost in the flow of logs, so now we print a banner containing the function that failed and the exit code.
It looks like:
```
================================================================================
ERROR OCCURRED
Function: main
Exit Code: 1
================================================================================
```
And should be printed in red.
**Checklist:**
=> test: clearer banner when func test fails

src/instructlab/lab.py
This commit removes the duplicate `--version` option from the `--help` command. The `--version` option was previously added twice, causing confusion and redundancy in the help menu.
Fixes #1355
**Checklist:**
=> fix: Remove duplicate --version option

.github/dependabot.yml, .github/mergify.yml, .github/workflows/actionlint.dockerfile, .github/workflows/actionlint.yml, .github/workflows/docs.yml, .github/workflows/e2e.yml, .github/workflows/image-cuda.yml, .github/workflows/lint.yml, .github/workflows/matchers/actionlint.json, .github/workflows/pypi.yaml, .github/workflows/shellcheck.yaml, .github/workflows/spellcheck.yaml, .github/workflows/stale_bot.yml, .github/workflows/test.yml, .github/workflows/validate-notebooks.yml
We use SHAs instead of tag names to refer to action versions. Dependabot
will help us manage the SHAs.
Update permissions to minimum necessary.
Add harden-runner to monitor egress of action. After some time, we can
tighten the egress to limit hosts/ports.
We also parallelize the lint workflow's linting work.
Resolves #1218 
**Checklist:**
=> Harden the GitHub Action workflows

.github/mergify.yml, .github/workflows/e2e.yml
The e2e workflow seems stable and I've cleared the budget side of
running this a lot more often. Turn on running it on all code changes.
=> e2e: Run on PRs and pushes

src/instructlab/model/chat.py, src/instructlab/utils.py
chat_cli() has too many arguments, which is anti-pattern. Many of arguments are parameters of the context.
Pass the context instead of individual parameters.
Introduce reusable http_client() to replace tls arguments.
=> reduce arguments of chat_cli()

src/instructlab/model/test.py
When running 'ilab model test' with an empty of non-existent data dir
(`taxonomy_data`), the CLI was stack tracing, now we gently print an
error.
Closes: #1360
**Checklist:**
=> fix: do not stack trace when no data dir

src/instructlab/model/convert.py
in the old cmd structure, lab.py must have done `from glob import glob`. the new convert.py just has `import glob`.
Resolves #1371 
**Checklist:**
=> fix glob import

requirements.txt
tenacity 8.4.0 introduced a breaking change and langchain-text-splitters
is not pinning it. So let's pin it ourselves and avoid the 8.4.0
release.
Closes: https://github.com/instructlab/instructlab/issues/1389
**Checklist:**
=> deps: avoid tenacity 8.4.0

src/instructlab/configuration.py
This variable is never used, as it gets shadowed by the `utils.py`:
```python
DEFAULT_YAML_RULES = """\
extends: relaxed
rules:
line-length:
max: 120
"""
```
=> fix: Remove DEFAULT_YAML_RULES from config

src/instructlab/data/generate.py, src/instructlab/model/chat.py, src/instructlab/model/convert.py, src/instructlab/model/download.py, src/instructlab/model/serve.py, src/instructlab/model/test.py, src/instructlab/model/train.py, src/instructlab/taxonomy/diff.py, src/instructlab/utils.py
Show command parameters when enable debug, e.g.
```
(dlipy3) [root@churh1 lab]# ilab generate
You are using an aliased command, this will be deprecated in a future release. Please consider using `ilab data generate` instead
===================== using parameters ===================
model            : models/merlinite-7b-lab-Q4_K_M.gguf
num_cpus         : 10
chunk_word_count : 1000
num_instructions : 100
taxonomy_path    : taxonomy
taxonomy_base    : origin/main
output_dir       : generated
rouge_threshold  : 0.9
quiet            : False
endpoint_url     : None
api_key          : no_api_key
yaml_rules       : None
server_ctx_size  : 4096
tls_insecure     : False
tls_client_cert  : 
tls_client_key   : 
tls_client_passwd: 
model_family     : None …
```
=> add debug information to display command parameters

src/instructlab/model/train.py, src/instructlab/train/linux_train.py, tests/test_lab_train.py
Refactoring to avoid procedural programming and
rigid hard-coded key values in different files
to use functional programming and flexible style.
The "training_results" string can also be easily parameterized when it is necessary.
=> linux_train returns training_results_dir

requirements.txt
Bump minimum pydantic version to 2.7.4 which works on Python 3.12.4. Fresh installs get it automatically, but in-place updates fail to do so with the old requirements.txt, as the version on disk is already satisfied.
Fixes #1391
Resolves #1391
**Checklist:**
=> Bump minimum version of pydantic to work on Python 3.12.4.

.markdownlint-cli2.yaml, .spellcheck.yml, pyproject.toml
The schema is now provided by the instructlab-schema python package and we no longer submodule the code. So we should remove all references to the removed src/instructlab/schema folder in this repo.
**Checklist:**
=> schema: Remove references to schema folder

scripts/functional-tests.sh
The ci is failing intermittently on this test and I believe the file is created but we check for its existence too quickly. Let's wait a little for the file to be present and if not return an error.
**Checklist:**
=> ci: wait for the session file to be created

src/instructlab/configuration.py, tests/test_config.py
Using a granite model works. Using a granite model plus specifying
`--model-family granite` did not work. This is because `granite` is
not one of the defined model families. Instead, we map `granite` to
`merlinite`, which in practice means an instructlab-tuned model.
Without explicitly specifying the model family option, we'd get
`granite` out of the model name and map it to the correct model
family. The code did not attempt to do this mapping when specified
explicitly.
This change makes the code check the model family mappings for
whatever was specified using `--model-family`, which will allow
`--model-family granite` to work.
Closes #1372
=> cli: Fix `--model-family granite`

requirements.txt
This PR removes the upper bounds on packages which don't appear essential to this repository.
In general, we should only be setting these upper bounds if the packages have been known to break. 
If any of these *are* breaking and I'm mistaken, I'm happy to put them back.
Fixes #1422
**Checklist:**
=> remove upper-bounds on non-essential packages

.spellcheck-en-custom.txt, CHANGELOG.md, src/instructlab/model/train.py, src/instructlab/train/linux_train.py, tests/test_lab_train.py
Not support train using gpu index as device. Use should set visible gpu device to use specific gpu before run ilab train command.
Resolves #1279
**Checklist:**
=> fix: use right gpu device for training when use device cuda:<index>

containers/hpu/Containerfile, docs/habana-gaudi.md, pyproject.toml, requirements-hpu.txt, requirements.txt, src/instructlab/lab.py, src/instructlab/sysinfo.py
Gaudi software 1.16.1 was released on 2024-06-19. Update highlights:
- PyTorch 2.2.2 fork
- transformers 4.38.2
- habana-torch-plugin 1.16.1.7
- optimum-habana 1.11.1 (fork from git no longer needed)
`ilab sysinfo` now also prints HPU-related information like device
properties and environment variables.
`ilab sysinfo` now also prints HPU-related information like device properties and environment variables.
See: https://docs.habana.ai/en/latest/Support_Matrix/Support_Matrix.html
See: https://docs.habana.ai/en/latest/Release_Notes/GAUDI_Release_Notes.html
Resolves #
=> Update to Gaudi 1.16.1, add HPU to sysinfo

.pylintrc, src/instructlab/configuration.py, src/instructlab/data/generate.py, src/instructlab/lab.py, src/instructlab/log.py, src/instructlab/model/backends/llama.py, src/instructlab/model/chat.py, src/instructlab/model/convert.py, src/instructlab/model/serve.py, src/instructlab/taxonomy/diff.py, src/instructlab/utils.py, tests/test_lab_generate.py, tests/test_utils.py
InstructLab no longer passes a single logging instance in its `ctx.obj` instance. Instead the code uses the recommended approach for logging. Every module has its own logging instance. Logging is configured in the root logger and sub-loggers are automatically inheriting all settings.
The change also revealed several issues and code violations in the old setup. Several modules were using the deprecated alias `logger.warn` instead of `logger.warning`. Some loggers are passing f-strings to logging functions instead of delegating formatting to logging framework. `logger.level == logging.DEBUG` is the wrong approach to check if the logger has debug mode enabled. The correct way is `logger.isEnabledFor(logging.DEBUG)`. This also takes parent + root logger into account. …
=> Don't pass logger in ctx.obj

src/instructlab/model/train.py
Sorting by name is error prone. One model name
will shadow another, when it goes alphabetically
after.
Fixes #1227
=> sort train_files and test_files by real time

scripts/infra/cloud-instance.sh
Re: https://github.com/instructlab/instructlab/pull/1461
This makes the corresponding change to cloud-instance.sh to use an appropriate python version on rh based systems.
=> Updating default python version on rh systems for cloud-instance.sh to 3.11

pyproject.toml
InstructLab no longer works with Python 3.12. Update `requires-python` field in `pyproject.toml` to tell pip that 3.12 is not supported.
See #1491 
**Checklist:**
=> Update requires-python to exclude Python 3.12+

Makefile
@mbestavros highlighted to me that `make verify` didn't include the `mypy` checks - this PR adds them in
**Checklist:**
=> fix: Add mypy to `make verify`

.gitignore, src/instructlab/model/train.py
lora-alpha is an int not a float.
Also, the train-output dir is picked up by git, this has large files in it so we should ignore.
=> fix lora-alpha which should be an int, gitignore

src/instructlab/train/lora_mlx/lora.py
Having "Training" in the output was hard to see:
```
Using model_type='mistral'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Total parameters 1244.079M
Trainable parameters 1.704M
Loading datasets
Training
Epoch 1: Iter 1: Val loss 3.317, Val took 6.840s
Iter 010: Train loss 2.194, It/sec 0.289, Tokens/sec 193.114
Epoch 1: Iter 10: Val loss 1.594, Val took 6.865s
```
This PR adds a more obvious "Training" notification.
=> Made the local training a tad more fun.

.github/workflows/e2e.yml
9a36b19 e2e: Fix a permissions error
commit 9a36b19a00e2ea74405c2a3b5610ff65a7438dc0
Date:   Thu Jun 27 18:50:32 2024 -0400
e2e: Fix a permissions error
This line giving some system config debug output used to work fine,
but started failing on a permissions error today. Slap some `sudo` on
it to get things running again.
=> e2e: Fix a permissions error

scripts/basic-workflow-tests.sh
The script runs generation against 3 taxonomy types. Reorder so
knowledge is last. Whatever runs last is what training runs again. I
want knowledge last for testing some SDG library output in that repo,
since that's what is working first in the major rework happening at
the moment.
The impact shouldn't be noticable.
=> e2e: Reorder generate test cases

requirements.txt, src/instructlab/utils.py, tests/test_utils.py, tests/testdata/testdata.py
This code was only used by the sdg library. It has been moved there
and is no longer needed here as of instructlab-sdg 0.0.3.
=> Drop some more sdg-only code

src/instructlab/data/generate.py, src/instructlab/model/chat.py, src/instructlab/model/serve.py, src/instructlab/utils.py, tests/test_utils.py
Add a helper method to correctly split a `host:port` combination into hostname and port. The naive approach is not IPv6-safe and does not correctly validate the host and port.
**Checklist:**
=> IPv6-safe hostname/port split

README.md
- `gcc-c++` works on Fedora, CentOS, and RHEL
- `pip` is not needed. We use a virtual env, which provides `pip` through other means.
- `python3-GitPython` was never needed in OS. Instead install `git`, which also provides `git-core` for `GitPython` in virtual env.
- include `-DLLAMA_NATIVE=off` in all `pip install` instructions. It has a minor performance impact but a huge UX improvements.
- Explain why 3.12 is not supported.
Resolves #1505
Resolves #1488
Resolves #1379
**Checklist:**
=> Update installation and dnf instruction

CHANGELOG.md, docs/gpu-acceleration.md, requirements.txt
Update `llama-cpp-python` to latest upstream release 0.2.79. In #1305, users have reported that SDG with 0.2.75 produces poor results. The latest version is not affected.
```shell
find -name '*.txt' -or -name '*.md' | xargs sed -i 's/0.2.75/0.2.79/g'
```
See: #1305
**Checklist:**
=> Update llama-cpp-python to 0.2.79

tests/test_utils.py
PR #1513 added new usage of this import while #1458 removed it. #1458
merged first and #1513 wasn't tested on top before merging, so `main`
broke.
This has happened a few times in the past. The only way to avoid it is
to enforce testing on latest `main` before merge, but we haven't setup
automation for this, yet.
=> tests: Add missing pytest import

docs/gpu-acceleration.md
- Save the user a lookup for what package contains lscpi by adding it to the docs since it's not a default installed package on Fedora cloud images.
- No issue, smol doc change
**Checklist:**
=> Add pciutils package to the gpu-acceleration docs

src/instructlab/model/train.py, tests/test_lab_train.py
Since `ilab generate` is now deprecated.
=> Update error message to refer to `ilab data generate`

src/instructlab/sysinfo.py
`ilab sysinfo` now prints versions of other InstructLab packages:
```
$ ilab sysinfo
...
instructlab-quantize.version: 0.1.0
instructlab-schema.version: 0.2.0
instructlab-sdg.version: 0.0.4
instructlab-training.version: 0.0.3
...
```
**Checklist:**
=> Extend sysinfo to include instructlab packages

src/instructlab/model/backends/backends.py, tests/test_backends.py
Replace complicated search for a random, bindable port with port 0 trick `s.bind((host, 0))`.
**Checklist:**
=> Use port 0 trick to get a random free port from OS

src/instructlab/client.py, src/instructlab/data/generate.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/chat.py
Use one argument http_client instead of four: tls_insecure, tls_client_cert, tls_client_key, tls_client_passwd.
=> reduce number of list_models and ensure_server arguments

src/instructlab/configuration.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/serve.py, tests/test_config.py
Never use `str.split` to split arguments to subprocess or f-strings to create arguments for subprocess. This breaks as soon as there a non-ASCII characters in any path, e.g. file names with a white space.
You either need `shlex.split` and `shlex.quote` (which does not work on non-Unix shells) or use list of string all the way.
Also fix a typing bug with port. It's now an `int` all the way.
**Checklist:**
=> Fix: No str.split or f-string for subprocess args

.github/workflows/e2e-nvidia-t4-x1.yml
This commit introduces a new approach for running the e2e CI job.
Instead of using a runner provided by github, use a similarly powered
runner on AWS that is much cheaper.
The real benefit of this approach is the ability to run on any other
instance type, giving us access to GPU instances that are more
powerful than what was built-in to GitHub. More powerful e2e variants
will come in future commits.
This job can only be manually triggered for now. At some point we may
create a configuration that can replace the one that runs
automatically on every commit, but I'd like to exercise this for a
while to make sure it's stable. It's also not quite as simple as just
running this automatically directly on PRs, because have to be careful
to protect against what's possible with a malicious PR. In …
=> Add e2e CI variant that runs on AWS

README.md
**Checklist:**
- [X ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
- [X ] Documentation has been updated, if necessary.
changed `xcode select` to `xcode-select`
=> docs: fix type in xcode install instructions for Mac

.github/workflows/e2e-nvidia-a10g-x1.yml, scripts/basic-workflow-tests.sh
cecd736 e2e: Add option to turn off `--4-bit-quant`
94c38d7 e2e: Add a new variant with non-quantized training
commit cecd7366fa5c3da99148a66822566be3c9578598
Date:   Mon Jul 1 22:50:07 2024 -0400
e2e: Add option to turn off `--4-bit-quant`
This test script used `--4-bit-quant` always because the test runner
required it. Now that we can test on custom AWS instances, make this
optional.
commit 94c38d74e75b1bca0d6d2451849e65ac9c142ce7
Date:   Mon Jul 1 22:51:16 2024 -0400
e2e: Add a new variant with non-quantized training
This e2e variant runs on an instance with a single A10G GPU with 24 GB
of GPU memory. This instance type is able to exercise `ilab …
=> Add e2e variant that can run non-quantized training

scripts/functional-tests.sh
On some run, the macos test fails waiting for the server to be ready, some logs show that the server can take up to 25s to start sometimes. So let's double it and wait up to 60s.
**Checklist:**
=> ci: increase timeout for serving to be ready

.spellcheck-en-custom.txt, CHANGELOG.md, src/instructlab/data/generate.py, src/instructlab/model/chat.py, src/instructlab/model/convert.py, src/instructlab/model/evaluate.py, src/instructlab/model/test.py, src/instructlab/taxonomy/diff.py, src/instructlab/utils.py
Followup to #1369
This PR is using the new serving backends and support the vllm and llama_cpp path.  It replaces temporary code serving vllm directly.
**Checklist:**
- [ x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
- [x ] Unit tests have been added, if necessary.
=> Use new vllm/llama-cpp backends for evaluate

.pylintrc, requirements.txt, src/instructlab/model/backends/backends.py, src/instructlab/model/evaluate.py, src/instructlab/model/serve.py, src/instructlab/model/train.py, src/instructlab/sysinfo.py, tests/test_lab.py
Avoid importing `llama_cpp` by importing the `ServerException` from its
original module.
Defer import of `run_training` to avoid import of `torch`.
Move imports from `instructlab.eval` into function to avoid import of
`torch`.
Add a test case to test for slow and heavy imports like `torch` and
`llama_cpp`. 
Allow `import-outside-toplevel` globally.
See: #1467
See: https://github.com/instructlab/training/pull/116
**Checklist:**
=> Fix slow `ilab` CLI startup

scripts/basic-workflow-tests.sh
The script only set this parameter when the minimal option was used,
but we should be setting this option in all cases.
=> e2e: Always set `--num-cpus` for generate

pyproject.toml, requirements-dev.txt
`coverage` is now configured to correctly merge local paths and tox paths. External InstructLab packages such as `instructlab.sdg` are excluded from coverage.
`coverage[toml]` is needed to enable `pyproject.toml` parsing in Python 3.10.
**Checklist:**
=> Configure coverage to merge and exclude paths

src/instructlab/model/train.py
currently, e2e tests pass even if training fails. Add a catch-all for any type of exception just so we properly error out.
=> catch all exceptions from training library

.github/workflows/e2e.yml
If you push updates to a PR, currently we're leaving `e2e` jobs for
all past revisions to keep running. If you do a few quick updates,
that ends up wasting a lot of resources.
This change ensures that for a given PR, only one of these jobs runs
at a time. A previous run will get canceled and replaced with one
against the latest version of the PR.
=> e2e: Only run one job at a time for a given PR

src/instructlab/model/serve.py
Since `gpu_layers` and `max_ctx_size` have moved in their own llama_cpp section under the serve section in the config file, if the user does not pass these via flag on CLI they will be None.
The log was printing:
```
INFO 2024-07-03 11:20:38,450 serve.py:101: serve Using model
'models/merlinite-7b-lab-Q4_K_M.gguf' with None gpu-layers and None max
context size.
```
We now pick the default value from the config (which has default) if either `gpu_layers` or `max_ctx_size` are None.
**Checklist:**
=> fix: serve log message with gpu layer and context size values

src/instructlab/configuration.py, src/instructlab/model/backends/backends.py, src/instructlab/model/serve.py, tests/test_backends.py, tests/test_config.py
We support two backends: llama-cpp and vllm, the helper text was only displaying 'llama-ccp' so now we print the correct list of supported backends.
CLI output:
```
--backend [llama-cpp|vllm]  The backend to use for serving the model.
Automatically detected based on the model file
properties.
```
**Checklist:**
=> fix: add list of supported backends in the CLI help

pyproject.toml
setuptools < 70.0 have a bug in the schema definition for dynamic optional dependencies. The issue was fixed in validate-pyproject 0.17 and setuptools 70.0.0.
70.1.0 has another fix that might be relevant for Python 3.10.
This fixes the following error message:
```
ValueError: invalid pyproject.toml config: `tool.setuptools.dynamic.optional-dependencies`.
configuration error: `tool.setuptools.dynamic.optional-dependencies` keys must be named by:
{format: 'python-identifier'}
```
See: https://github.com/abravalheri/validate-pyproject/pull/170
**Checklist:**
=> Require setuptools >= 70.1.0 to build wheel

.github/workflows/e2e-nvidia-a10g-x1.yml, .github/workflows/e2e-nvidia-t4-x1.yml
The AMI we use is built to have some things pre-installed - most
notably the NVIDIA drivers and CUDA stack. I noticed that this upgrade
was now pulling in a new NVIDIA version, including a driver.
By not running an upgrade, we'll control when we apply updates to our
base image for important pre-installed dependencies.
=> e2e: Don't upgrade OS packages on AWS runners

.pylintrc, pyproject.toml, src/instructlab/configuration.py, src/instructlab/model/backends/backends.py, src/instructlab/model/evaluate.py, src/instructlab/model/test.py, src/instructlab/train/linux_train.py, src/instructlab/utils.py
Ruff can not just detect and report code violations. It can automatically fix a large amount of code violations, too. This change enables most checkers and addresses their code violations:
- Update minimal Python version to 3.10
- Remove unnecesary `zip`
- Remove some unused imports
- Simplify some code
- Avoid `l`, which can be easily confused with `1`.
- Use full path regexps for pylint's `ignore-paths`
This change only contains uncontroversial and simple fixes. I will enable more fixers in the near future.
**Checklist:**
=> Enable more Ruff checkers and fixers

.github/workflows/test.yml, .readthedocs.yaml, .spellcheck-en-custom.txt, Makefile, docs/Makefile, docs/amd-rocm.md, docs/conf.py, docs/demo-slides.md, docs/gpu-acceleration.md, docs/habana-gaudi.md, docs/ilab.rst, docs/index.rst, docs/requirements.txt, src/instructlab/utils.py, tox.ini
Add infrastructure to build documentation with Sphinx, MyST (for markdown parsing), and furo theme. An untested RDT config is included, too.
`tox -e docs` and `make docs` now builds the documentation
**Checklist:**
=> Add end user Sphinx documentation

scripts/infra/README.md, scripts/infra/cloud-instance.sh
The fix requires version locking cuda and nccl.
Includes minor change to reference cloud-instance from root of instructlab consistently.  This helps users not need to cd so many times to follow the README verbatim.
Related to: #1566 
**Checklist:**
- [*] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
=> fix: Updating Nvidia GPU setup on RH systems in cloud-instance

src/instructlab/model/evaluate.py, tests/test_lab_evaluate.py
Adding initial unit tests for ilab model evaluate.  Covers the 4 basic benchmarks (mt_bench, mt_bench_branch, mmlu, and mmlu_branch as well as some error cases.
Noticed during testing that `ilab model evaluate` returns without error.  Added --benchmark as a required option.  Not sure that's the right way any more.
**Checklist:**
- [ x] Unit tests have been added, if necessary.
=> Adding ilab model evaluate unit testcases

scripts/basic-workflow-tests.sh
When handling an invalid argument to the script, the `$OPTARG`
variable was referenced as the invalid argument. The variable is
actually `$opt`. I noticed this when I ran the script with an invalid
arg by accident.
=> e2e: Fix reference to invalid variable

scripts/basic-workflow-tests.sh
a9d5f79 e2e: Add script support for running Mixtral
c3ccacc e2e: Add script support for testing full sdg pipeline
commit a9d5f793dfaa4d9df97ebede2a8a1a92c184df0a
Date:   Thu Jul 4 00:00:35 2024 -0400
e2e: Add script support for running Mixtral
Before we can test `ilab data generate --pipeline full`, we must be
able to serve Mixtral. This commit adds that support to the e2e test
script. It includes
- downloading the 4-bit quantized version of the model
- updating config.yaml to specify mixtral
- updating command line parameters as appropriate for mixtral
- Adjust the timeout while waiting for the model server to come up to
be 30s instead of 10s. This model is much larger and takes longer to
load. In my testing, 10s wasn't enough.
A prerequisite …
=> e2e: Add support for full SDG pipeline

scripts/basic-workflow-tests.sh
The script intended to have `--num-epochs 1`, but we were overwriting
`TRAIN_ARGS` at one spot instead of appending to it. The epochs flag
was set earlier in the script.
=> e2e: Fix setting training epochs in CI

tests/test_lab_evaluate.py
In order to deliver:
https://github.com/instructlab/eval/pull/52
and
https://github.com/instructlab/instructlab/pull/1616
We need to merge and release 52 and merge 1616 at the same time.
To avoid any time delay, I am putting out this PR to merge first.  That will enable us to merge and release https://github.com/instructlab/eval/pull/52, then get the tests to pass on 1616 before merging.  Otherwise CI will be broken for the time period between the release and merge.
**Checklist:**
=> Temporarily removing assertions to allow to cross repo change

src/instructlab/clickext.py, src/instructlab/config/config.py, src/instructlab/configuration.py, src/instructlab/data/data.py, src/instructlab/model/chat.py, src/instructlab/model/evaluate.py, src/instructlab/model/model.py, src/instructlab/model/serve.py, src/instructlab/model/train.py, src/instructlab/taxonomy/taxonomy.py, tests/conftest.py, tests/test_lab.py
Introduce a `click.Option` subclass that renders help messages with defaults from the context's `default_map` and shows a hint to the config setting name. This simplifies the code and avoids code duplication.
The implementation can later be extended to show dynamic defaults from the user's config file instead of static defaults from the default config. The new `ConfigOption` can lookup defaults from nested settings. There is no need to flatten the configuration any more.
Code:
```python
@click.option(
"--model-path",
type=click.Path(),
cls=ConfigOption,
help="Path to the model used during generation.",
)
```
Output:
```
Options:
--model-path PATH           Path to the model used during generation.
[default: models/merlinite-7b-lab-Q4_K_M.gguf;
config: 'serve.model_path']
```
```python …
```
=> Improve config default lookup and `--help` message

scripts/basic-workflow-tests.sh
I'm trying to bootstrap some test workflows using larger AWS instance
types. On these instances with multiple GPUs, it's not very useful to
test the legacy training code path, because it doesn't support using
multiple GPUs. On these instances, we want to test the new training
path using the training library. Integrating that is a work in
progress (PR #1557).
This is just a temporary measure that we can remove once the new
training code path is supported in this script.
=> e2e: Add script option to skip training

tests/conftest.py, tests/test_lab_diff.py, tests/test_lab_download.py, tests/test_lab_evaluate.py, tests/test_lab_init.py, tests/test_lab_train.py
Introduce pytest fixtures for click's `CliRunner`, to reset `HOME` and `XDG_*` env variables, and access to test data.
`tmp_path_home` fixture sets `os.environ` variable `HOME` to pytest's current `tmp_path` and removes all `XDG_*` variables.
`cli_runner` uses `tmp_path_home` and creates a new click `CliRunner` with file system isolation inside pytest's `tmp_path`.
`testdata_path` returns the local test data directory as absolute `pathlib.Path` object.
All tests have been refactored to use the new `cli_runner` fixture. The change is inspired by a previous PR by Ihar Hrachyshka.
**Checklist:**
=> Test fixtures for CliRunner, HOME, and XDG_*

.github/workflows/e2e-nvidia-a10g-x4.yml, docs/ci.md
This workflow runs on a larger instance with 4 GPUs instead of 1. This
one is capable of serving Mixtral-8x7b-instruct (a quantized version,
at least). This is enough to test the full SDG pipeline.
The training library is targeted at systems with multiple GPUs, but we
don't have that in CI yet. For now, training is excluded from this
workflow. We will turn it on once that support is ready. See #1557 for
progress on that.
This commit also updates the CI docs to reflect what is tested by this
workflow.
Closes #1588 
=> e2e: Add a workflow that tests the full SDG pipeline

scripts/basic-workflow-tests.sh
PR #1471 changed where the config is located. This `sed` assumed
`config.yaml` was still in the current working directory. Look for it
in `${CONFIG_HOME}` instead. This variable is already set in the
script elsewhere.
=> e2e: Fix config update to use Mixtral

.github/workflows/e2e-nvidia-a10g-x4.yml
This `cd instructlab` is left over from when I was testing this
workflow on another repository. In that case, it was cloning
instructlab separately, so it had to `cd` into it here to run the
script. Now that we're running out of this repo, this line is not
needed.
=> e2e: Fix directory for running script

scripts/basic-workflow-tests.sh
017414f e2e: Fix path to config file
07e6607 e2e: Always create a new config file
commit 017414f497627d9834575e0cf2b17afa9b11d125
Date:   Wed Jul 10 08:00:53 2024 -0400
e2e: Fix path to config file
This is related to changes made in #1471.
PR #1645 was a previous attempt at fixing this, but the path wasn't
quite right. It missed `instructlab/` within the base config dir.
commit 07e66073b8517def46b51c7f15aa6959952cb392
Date:   Wed Jul 10 09:29:21 2024 -0400
e2e: Always create a new config file
The previous code tried to only create a config file if it did not
already exist. This script has evolved to assume it has ownership of
the config, so we should …
=> e2e: Fix path to config file

docs/gpu-acceleration.md
This PR fixes the link that points to the README Initialize section.
As this is a very simple fix, I didn't open an issue. Please let me know if I should do so (or if any further changes are needed).
**Checklist:**
=> Update Initialize link

tests/test_config.py
PR #1471 introduced a bug in `test_config`. All tests are leaking `HOME` environment variable change to the rest of the test suite. Change the fixture from `tmp_dir` to `tmp_dir_home` solves the problem.
**Checklist:**
=> Fixup PR 1471: Don't leak HOME env var

src/instructlab/model/backends/backends.py, tests/test_backends.py
Running `ilab model serve --backend vllm` on macOS will never work since
vLLM is only supported on Linux.
The CLI now warns with:
```
$ ilab model serve --backend vllm
...
WARNING 2024-07-11 09:30:34,816 backends.py:195: get The serving backend 'vllm' was configured explicitly, but the provided model is not compatible with it. The model was detected as 'llama-cpp, reason: model is a GGUF file.'.
The backend startup sequence will continue with the configured backend but might fail.
```
And the backend initialization will fail later on.
**Checklist:**
=> fix: warn if vLLM is set and OS is not Linux

scripts/functional-tests.sh, scripts/infra/README.md, src/instructlab/lab.py, src/instructlab/sysinfo.py, src/instructlab/system/info.py, src/instructlab/system/system.py, tests/test_lab.py
PR #1471 moved `ilab sysinfo` to `ilab system sysinfo`, but did not add an alias for `ilab sysinfo`.
- rename command to `ilab system info` to remove redundant `sys` prefix
- add alias to map `ilab sysinfo` to `ilab system info`
- add tests to verify aliases and now primary subcommand
Resolves: #1661
**Checklist:**
=> Rename to `ilab system info` and fix `ilab sysinfo`

scripts/basic-workflow-tests.sh
Every place in the script that used `-m`, `--model`, or `--model-path`
was broken as they weren't pointing to the new location of the models.
This is related to #1471
previous incomplete fixes in #1645, #1650
=> e2e: Fix custom model support

.github/workflows/e2e-nvidia-a10g-x1.yml, pyproject.toml, scripts/basic-workflow-tests.sh, scripts/test-data/train-profile-a10.yaml
Built on top of #1556 
adds non-legacy training to the A10 runners. These ones should be able to run natively without disabling flash-attn.
adds flash-attn, packaging, wheel pip install's to the e2e yaml. 
adds some generated data to train off of, and the model in use is granite-7b-lab.
This PR  also introduces some new handling for installing all necessary packages and reinstalling some existing ones
when doing dnf upgrade we get a nccl version mismatch because a bunch of the cuda deps are upgraded
also, the path was set to the wrong values. The outdated values were not pointing to the right nvcc or nccl causing issues when running nvidia-smi and any cuda processes.
=> Full e2e train using library and new CI runners

README.md
Hi 👋 
especially as Mac OSX ships with python, many use pyenv to avoid conflicting with the system's python.
Following the current command instructions on a system with pyenv would actually return
```
Bourne-Again shell script text executable, ASCII text
```
of the shim instead of the executable.
This PR proposes for newcomers another command to try,
instead of maybe stumbling on the first difference in the setup prerequisite check :) 
wdyt ?
**Checklist:**
=> docs: details for mac prerequisite instructions

requirements.txt, src/instructlab/model/train.py
bump sdg to a version which handles `messages`. Also, fix defaulting for `--is-padding-free` and `--gpus`. Currently these two options have no defaults and the user must specify them to run training
=> training fixes

src/instructlab/model/train.py
This PR fixes an issue where the training script currently uses the test files for both the training and the test files.
=> Fixes incorrect file reference

src/instructlab/configuration.py, src/instructlab/model/train.py, tests/test_config.py, tests/test_lab_diff.py
This work introduces additional_args a new part of the training config which holds less commonly edited options. Users can edit
```
additional_args {
}
```
to their _train config class to set some of these options.
additional_args also lives in persistent storage in  ~/.local/share/instructlab/internal/train_configuration/additional/additional_args.yaml This involved creating a few new subdirectories.
_train has been flattened since all of the torch_args were moved into the additional_args this is what a template config.yaml train section currently looks like:
```
train:
ckpt_output_dir: /home/cdoern/.cache/instructlab/checkpoints
data_output_dir: /home/cdoern/.local/share/instructlab/internal
data_path: /home/cdoern/.local/share/instructlab/datasets
deepspeed_cpu_offload_optimizer: false …
```
=> training additional_args

src/instructlab/lab.py
Just running `ilab` can be helpful in determining the default location of the config file.
```
$ ilab
Usage: ilab [OPTIONS] COMMAND [ARGS]...
CLI for interacting with InstructLab.
If this is your first time running ilab, it's best to start with `ilab
config init` to create the environment.
Options:
--config PATH  Path to a configuration file.  [default:
/home/ec2-user/.config/instructlab/config.yaml]
```
**Checklist:**
=> feat: print default config file when running ilab

src/instructlab/client.py, src/instructlab/model/backends/backends.py
ensure_server() became technological debt.
Historically, it has aggregated a mix of functionally different code, and its name does not accurately describe the content. Also usage of this function is confusing.
The plan is to split the function and reorder the code accordingly guidelines:
- clean backend agnostic code
- clean llama-cpp related code
- clean vllm related code
- no code duplication
- modularity
In order to refactoring, offshoot check_api_base() from ensure_server().
=> Introduce check_api_base

docs/ci.md
* Use dashes instead of red Xes to indicate where something isn't
used, but it's intentional and not a problem.
* Drop the target column. Our gaps are now reflected by red Xes.
* Note where the training-lib is now exercised.
* Add notes on some coverage gaps that aren't easy to reflect in the
matrix.
=> docs: Update text matrix for clarity purposes

scripts/test-data/train-profile-a10.yaml, src/instructlab/configuration.py
the current a10 train profile didn't get adjusted for additional_args support
also, so that each entry in additional_args doesn't need to be strings, switch the value type to `typing.Any`
**Checklist:**
=> fix train-profile, switch additional args to [str, typing.any]

src/instructlab/clickext.py, src/instructlab/config/init.py, src/instructlab/config/show.py, src/instructlab/data/generate.py, src/instructlab/model/chat.py, src/instructlab/model/convert.py, src/instructlab/model/download.py, src/instructlab/model/evaluate.py, src/instructlab/model/serve.py, src/instructlab/model/test.py, src/instructlab/model/train.py, src/instructlab/system/info.py, src/instructlab/taxonomy/diff.py, src/instructlab/utils.py, tests/test_lab.py
The `display_params` decorator now adds two hidden diagnostic flags `--debug-params` and `--debug-params-json` to the list of options. When a flag is passed to a subcommand, it displays all parameters with additional options and then exits with error code 0. The JSON output is designed to be used in tests.
The function now displays more information, too. Besides name and value, it reveals the type of the value and the origin (command line, env vars, default, default, map).
```console
$ ilab model chat --debug-params
Parameters:
question: ()         [type: tuple, src: commandline]
model: 'models/merlinite-7b-lab-Q4_K_M.gguf'      [type: str, src: default_map]
context: 'default'  [type: str, src: default_map]
session: None       [type: None, src: default]
...
```
**Checklist:** …
=> Debug: Improved display params diagnostics

src/instructlab/model/train.py, tests/test_lab_train.py
we should only shutil the files from input-dir to data-dir if data-dir DNE. The way this is happening now makes it so that you copy the same files on top of one another resulting in a `SameFileError`
**Checklist:**
=> legacy train fix

src/instructlab/model/backends/backends.py
Internally, we run vLLM using the Python interpreter as described in the [official
documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html).
vLLM is intended to run via the CLI and be terminated by sending SIGINT (Ctrl+C). This way, when the signal is received, vLLM will properly shut down and reap its child processes.
Another approach was developed by @alimaredia
[here](https://github.com/alimaredia/instructlab/commit/8edfb81ef915b65179bb0f07c94ff82488c8bdbd).
This method involved listing and registering child processes launched by
vLLM, then manually killing each child process during shutdown. @tiran
and I agree that this approach is overkill and should only be used if
there is an urgent bug in vLLM that needs to be fixed quickly. However,
this is not the …
=> fix: vllm serving with multiple gpus not shutting down properly

src/instructlab/model/evaluate.py
It was orphaned with this change: https://github.com/instructlab/instructlab/pull/1564/files
**Checklist:**
=> Removing orphaned pylint comment

src/instructlab/config/show.py, tests/test_lab_config.py
`ilab config show` mishandles an exception in YAML parsing. It does not exit when `yaml.load()` fails with an exception. Instead it leaves `config_yaml` undefined, which leads to an `UnboundLocalError` error.
The code was also using the wrong yaml loader. All other code paths are using a safe loader, which prevents accidental code execution and security problems. The FullLoader is not safe. PyYAML's documentation even warns against using it:
> WARNING: As of pyyaml-5.3.1 there are still trivial exploits. Do
> not use this on untrusted data for now.
The command now exits with error code 2 on error and uses safe loading. Our code is unlikely to be affected by the unsafe operation, but better safe than sorry.
See #1471 
**Checklist:**
[conventional …
=> Fix security and UnboundLocalError in config show (PR #1471)

src/instructlab/model/evaluate.py
The new logic recommends a value to be half the number of cores (rounded down) that are available in the hardware to match llama-cpp's behavior.
**Checklist:**
=> Remove magic number for eval max_workers recommendation

src/instructlab/model/evaluate.py
This is to allow for cases when for example your model or base model need to be served with llama-cpp but your judge needs to be served by vllm.  That would work as is if backend isn't specified.  But as soon as you need to force a backend, currently it would force the backend to be the same for the model and judge model
Ex:
```
(venv) [ec2-user@ip-10-0-1-95 instructlab]$ ilab model evaluate --judge-model models/instructlab/granite-7b-lab --benchmark mt_bench --backend llama-cpp --judge-backend vllm
Generating answers...
WARNING 2024-07-12 22:22:51,358 evaluate.py:276: launch_server When using llama-cpp, we recommend setting max_workers to a maximum of 16
0%| …
```
=> Allow for separate judge backend option

src/instructlab/log.py
Before the patch the log line would have a colon, then the function name and the log message. It's a bit hard to read. Now, we have the colon before the log message so it's easier to see where the log message starts.
Before:
```
INFO 2024-07-15 14:44:29,514 llama_cpp.py:177: server Starting server process,
```
After:
```
INFO 2024-07-15 14:44:29,514 llama_cpp.py:177: server: Starting server process,
```
**Checklist:**
=> Add a colon before the log message

src/instructlab/configuration.py, src/instructlab/model/evaluate.py
The recommendation is based on the number of cpus available since it relates to the number of cpu bound worker threads.  There is also some correlation to gpus as well and the results will vary based on hardware, so the recommended range is fairly wide +- 50% from the #cpus.
Also change the default max_workers in config to work better with lower end hardware.
**Checklist:**
=> Add max workers recommendation for vllm and adjust default

src/instructlab/configuration.py, src/instructlab/model/evaluate.py, tests/test_config.py
Allowing STRING types allows for the valid values of auto and auto:N to be set in addition to integers.
Also adjusting the default to auto to remove the magic number and hopefully have better out of the box tuning.
Corresponding change on the eval side: https://github.com/instructlab/eval/pull/67
**Checklist:**
=> Update batch size to not be described in terms of gpus and allow non integer values

.github/ISSUE_TEMPLATE/team_recommend.md
From convo here: https://github.com/instructlab/instructlab/issues/1686#issuecomment-2228943549
This PR adds some example GitHub queries that can be used as part of our nomination process. Thanks @tiran for the suggestion!
=> Add example GitHub queries to nomination template

src/instructlab/model/backends/backends.py, src/instructlab/model/serve.py
Before this patch, if `ilab model serve` received a SIGTERM, it would
exit abruptly, leaving the vLLM process and its child processes
orphaned.
This commit adds a signal handler to the main entrypoint of 'ilab' for
SIGTERM. This allows both llama-cpp and vLLM servers to exit gracefully
when receiving a termination signal, ensuring that resources are
properly released and shutdown procedures are correctly executed.
The handler is setup to catch SIGTERM, once received, it executes
`signal_handler()`, which calls exit 0, the code then goes into its
final sequence through `finally` which stops the server and return. At
this point, `ilab` has exited properly and cleanly.
**Checklist:**
[conventional …
=> Add signal handling to gracefully terminate vLLM server

requirements-dev.txt
We currently make use of pyspelling to validate that the docs have valid spelling.
However, we don't have a direct way of ensuring pyspelling is installed without requiring
the developer to do it manually.
This PR fixes that by adding pyspelling to the requirements-dev.txt file.
**Checklist:**
=> Add pyspelling to requirements-dev.txt

docs/ci.md
motivation: this change makes it easier at a glance to see the relative size of our E2E runners as well as what sizes of runner can run which features of ilab (e.g., only "large" runner can run full generate)
recommend reviewing the "rich diff" to see the rendered differences here
**Checklist:**
=> docs: add t-shirt sizes to E2E runners

src/instructlab/model/evaluate.py
This helps a bit with loading performance.  It also helps a current issue with lm_eval messing with the logger settings since it's not needed from mt_bench and mt_bench_branch.
This logic also removes the benchmark class map which wasn't really worth creating just to reference 1 time.
Related: https://github.com/instructlab/eval/issues/65
**Checklist:**
=> Only load mt_bench or mmlu as needed

src/instructlab/model/backends/backends.py
The check_api_base call takes over 2 seconds to respond which wasn't being accounted for in the timing of the desired sleep time.  The new logic changes the extra sleep to only 2 seconds, gets closer to a desired max wait time of 5 mins, and gives an accurate total duration on failure.
**Checklist:**
=> Change vllm startup logic to not correlate retries to seconds

src/instructlab/model/evaluate.py
The previous logic wasn't handling any of the objects inside the serving config.  So when it got to an object like vllm_args, it was modifying it directly.  And it would be reused across multiple server launches.
So the generate step of eval would start with these vllm args:
```
['--served-model-name', 'test_model']
```
and the evaluate step would start with these args:
```
['--served-model-name', 'test_model', '--tensor-parallel-size', '1', '--served-model-name', 'judge_model']
```
And then get erroneous messages like:
```
Using gpus from --gpus or evaluate config and ignoring --tensor-parallel-size configured in serve vllm_args
```
because --tensor-parallel-size  and the first --served-model-name was left in the args from before
**Checklist:**
[conventional …
=> Need to deepcopy config to handle compound objects

.spellcheck-en-custom.txt, CHANGELOG.md, scripts/functional-tests.sh, scripts/test-data/mock-template.txt, src/instructlab/configuration.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/serve.py, tests/test_backends.py, tests/test_config.py, tests/test_lab_serve.py
Introduces a `--chat-template` option, covering both vllm and llama.cpp backends. This addresses compatibility problems with ilab chat clients and the vllm backend, and brings closer consitency between llama.cpp and vllm for out of the box usage. This is also a prerequisite for e2e testing using vLLM.
The option has three possible values:
1. 'auto' (default) - instructlab overrides the model template with a new template based on hard coded model knowledege. This is the current behavior before this commit. However, in the future this could be changed to a different dynamic policy, as the name simply implies instructlab decides
2. 'tokenizer' - uses the template expressed in the model's tokenizer_config.json file (or internal gguf settings). This is the ideal long term direction, although …
=> feat: Add chat template customization to ilab serve

src/instructlab/model/backends/backends.py
complete refactoring after introduction check_api_base()
review without whitespace changes: https://github.com/instructlab/instructlab/pull/1690/files?w=1
which yelds
```
...   
-    # pylint: disable=no-else-return
if check_api_base(api_base, http_client):
return (None, None, api_base)
-    else:
...
```
=> refactor: fix up indentation of ensure_server()

containers/hpu/Containerfile, docs/habana-gaudi.md, requirements-hpu.txt, requirements.txt
Update Gaudi software to 1.16.2
Update optimum to 1.20.1 and optimum-habana to 1.12.0. The new versions support recent version of transformers library that is compatible with HabanaAI's vllm-fork.
**Checklist:**
=> Intel Gaudi: Update Gaudi software and optimum-habana

src/instructlab/model/backends/vllm.py, tests/test_backends.py, tests/test_lab_serve.py
This commit introduces a dedicated function, `build_vllm_cmd` to construct the vLLM command required to run the server. It ensures that the command includes necessary arguments such as host, port, and model path.
It also explicitly sets the distributed executor backend to multiprocessing to avoid unintended use of Ray, even if it's installed on the system. It uses the "--distributed-executor-backend mp" argument to the vLLM command if it's not already present. With this, we ensure that multiprocessing is used for distributed serving, even if Ray is installed on the system, as Ray is not supported yet.
**Checklist:**
=> fix: ensure multiprocessing is used for distributed serving in vLLM

src/instructlab/model/serve.py
`ilab model serve` no longer accepts unknown extra arguments before the argument separator `--`. Click's documentation is a bit confusing. The combination of `ignore_unknown_options=True` and `allow_extra_args=True` allows for additional arguments after the separator and blocks unknown arguments before the separator.
See: #1738
**Checklist:**
=> Fix model serve extra args

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, tests/test_lab_model_test.py
The code is moved with minimal changes.
Consolidate lama-cpp code in llama_cpp.py,
making backends.py backend implementation agnostic.
for check_api_base()  see #1596
=> refactor: move lama-cpp code from backends.py to llama_cpp.py

.github/workflows/e2e-nvidia-a10g-x1.yml, .github/workflows/e2e-nvidia-a10g-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml, .github/workflows/e2e.yml, scripts/basic-workflow-tests.sh
In our current end-to-end workflow test, we rely on hard-coding the path to the model being served by `ilab serve`
in order to initiate a chat instance. This can lead to a lot of unnecessary maintenance and testing that must be done
by the maintainers to ensure that the provided path is always correct.
Frustratingly, ilab is usually only ever serving one model at a time, and will tell you the correct model path when you actually run the chat as an end-user.
As a workaround in lieu of ilab automatically knowing which model to chat with, this PR changes the test behavior to instead query the ilab model server to find the actively served model and just plugs that directly in as the correct model path.
- **chore: add jq to the packages that are installed during the e2e CI**
- **feat: updates …
=> Automatically find the actively served model when testing chat

CHANGELOG.md
It looks this line was duplicated by mistake during merge of bb746e8f.
Original correct string is located six lines above:
"evaluation (currently applicable for vLLM only).  Also includes --merge-system-user-message"
Signed-off-by: Costa Shulyupin <costa.shul@redhat.com>
=> Changelog: remove duplicated line

CHANGELOG.md, README.md, pyproject.toml, requirements-cuda.txt
This PR introduces a new file `requirements-cuda.txt` which contains all of the dependencies that cannot install unless CUDA is available.
Presently, the only package this contains is `instructlab-training` which has a dependency on flash-attn.
To make use of this, you can install the `ilab` CLI by doing `pip install instructlab[cuda]`.
**Checklist:**
=> Add CUDA requirements file

src/instructlab/config/init.py, src/instructlab/configuration.py, src/instructlab/model/chat.py, src/instructlab/model/linux_test.py, src/instructlab/model/test.py, tests/test_config.py
There is a mismatch between the default model path set during `ilab config init` and the one that the Pydantic (BaseModel) object holds. Currently, the default model path is set to
`merlinite-7b-lab-Q4_K_M.gguf` in the `config.yaml` when we run `ilab config init`. However, the config object holds the model path `merlinite-7b-lab-Q4_K_M`. This discrepancy can lead to confusion and potential errors when the model path is used in other parts of the codebase. To resolve this issue, we should ensure that the default model path set during `ilab config init` matches the one stored in the config object. This will help maintain consistency and prevent any unexpected behavior due to the mismatched model paths.
It's unclear why the default model was changed in …
=> revert: use GGUF file as default model

.github/workflows/e2e-nvidia-a10g-x1.yml, .github/workflows/e2e-nvidia-a10g-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml, .github/workflows/e2e.yml
the 'c' flag is no longer used by the e2e test
script - left it in as this script is used in
other repos but removed it from all the jobs
defined here
**Checklist:**
=> fix: remove unused flag from e2e job configs

requirements.txt
instructlab-sdg 0.2.0 will include changes that are not backwards
compatible. Temporarily cap our dependency here. This cap will be
lifted and replaced with `>=0.2.0` in a future change.
=> requirements: Set a cap on instructlab-sdg

.github/workflows/e2e-nvidia-a10g-x4.yml, docs/ci.md, scripts/basic-workflow-tests.sh
-T enables the e2e to be run with JUST the full training library. When used the --legacy tests will be skipped.
**Checklist:**
=> add -T option to e2e

src/instructlab/data/generate.py
sdg now supports more then just the aliases defined by the sdg library. Allow all pipeline names so that the sgd library can assess if they are present.
Fixes #1703
Related instructlab/sdg#166
---
sdg PR that allows additional alias names https://github.com/instructlab/sdg/pull/166
=> Remove the check for a valid pipeline alias

.github/workflows/e2e-nvidia-a10g-x1.yml, .github/workflows/e2e-nvidia-a10g-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml, .github/workflows/e2e.yml, scripts/basic-workflow-tests.sh, scripts/functional-tests.sh, src/instructlab/model/chat.py
The detection was comparing a string with a fullpath with a basename. So
the model name was never matching and the condition was not entered.
Now when `ilab model chat` is called and a server is already running
with `ilab model serve`, the chat will fetch the model from the server
and present it in the chat header.
**Checklist:**
=> fix: model server detection

docs/ci.md
- We now run legacy training only for `a10g-x1`.
- We run the training-lib in `a10g-x4`, including the use
of the `full` SDG pipeline as input into training.
=> docs: Reflect updates to training CI status

src/instructlab/configuration.py, tests/test_config.py
=> Introduce version field in CLI config yaml

src/instructlab/model/backends/backends.py, tests/test_backends.py
`tokenizer.model` isn't required for a model directory to be a `.safetensors` model- this broke model loading for me because the checkpoints that we save don't have this file. This appears to be a common, but not a required file. (look at metaai/llama3-8b)
=> removes tokenizer.model from required safetensors model files"

.github/workflows/e2e-nvidia-t4-x1.yml, docs/ci.md
This PR is the next step of replacing the `e2e` job that runs on a GitHub hosted
runner in favor of running it on AWS. These changes get the job running
automatically just like the original `e2e`, but does not block merges on it for
now. We can let this run in parallel for a short time to make sure it's stable
before switching over to it completely.
e86902f ci: Run e2e-nvidia-t4-x1.yml automatically
commit e86902f62765d1c648c256b3656a4ac8a4a04449
Date:   Mon Jul 15 17:19:58 2024 -0400
ci: Run e2e-nvidia-t4-x1.yml automatically
This makes our smallest AWS-based e2e workflow run by default on PRs.
The hardware configuration is roughly equivalent to the existing e2e
job that runs by default on PRs on a github-hosted runner.
I propose running this …
=> Automatically trigger e2e on AWS

CHANGELOG.md, scripts/functional-tests.sh, src/instructlab/configuration.py, src/instructlab/data/generate.py, tests/test_config.py
77371ee generate: Add `--sdg-scale-factor`
commit 77371ee3efe23c5fec8fdb3afa04c607135215fa
Date:   Tue Jul 2 20:21:22 2024 -0400
generate: Add `--sdg-scale-factor`
The new implementation of data generation from the `instructlab/sdg`
library behaves differently than before. Instead of having a tunable
for the maximum number of generated examples, it has a tunable for the
number of examples to generate based on each seed example, for some
definition of "seed example". The number of seed examples expodes to
be much more than the provided q&a pairs when working with a knowledge
document.
The new option, `--sdg-scale-factor` tries to capture this new
behavior and make it clear that it's not a specific number of examples
anymore, but more of a …
=> generate: Add `--sdg-scale-factor`

scripts/infra/cloud-instance.sh
adds a remote 'upstream' as part of the setup process this allows users to pull directly from the upstream project on their clones without needing to manually add the remote
**Checklist:**
=> feat: automatically add upstream remote to instructlab clone

.github/mergify.yml, .github/workflows/actionlint.yml
This fixes an issue I hit in https://github.com/instructlab/instructlab/pull/1724 - previously, changing a non-workflow file in `.github` would block automerge as Mergify expected a result from `actionlint`, but `actionlint` only runs when a workflow file is changed. This PR aligns the regexs we are using in the respective configurations.
**Checklist:**
=> fix: match mergify automerge rules to actionlint rules

CHANGELOG.md, src/instructlab/configuration.py, src/instructlab/data/generate.py, tests/test_config.py
Currently `ilab data generate` uses the configuration from the `serve` section of configuration file to serve the teacher model in the background. 
In the case where a user is using a specific model only as the teacher model, the user would have to edit the `serve` section of the config with the teacher model's settings.
Since the teacher model and it's configuration is static, and the serve section is dynamic, the teacher model and it's configuration should live in the `generate` section of the configuration. 
Giving the teacher model it's own configuration section also prevents the user from accidentally serving the teacher model, if they have not changed the `serve` section.
This PR is meant to be a starting point. Further work should evolve the configuration of the teacher model in …
=> feat: add serve config for teacher model in `ilab data generate`

src/instructlab/model/backends/backends.py, tests/test_backends.py
Current check for auto-detection of backend requires a vLLM friendly model's directory to contain `*.safetensors` files to qualify as valid. However, we should also accept the presence of `*.bin` files in place of `*.safetensors` files as training outputs `.bin` checkpoints that can be served through vLLM
**Checklist:**
=> fix: check for .bin files during auto-detection of serving backend

src/instructlab/taxonomy/diff.py, src/instructlab/utils.py, tests/test_utils.py
Nothing uses the parsed taxonomy data that was returned by this code.
There is a proposal to change the taxonomy schema. Instead of fixing
this copy of this code, make it stop reading the contents aside from
doing automated validation.
Rename these functions to `validate_taxonomy` instead of
`read_taxonomy` since we only care about the validation part and not
returning any data from them.
If we look at changing this to use a new API, this helps clarify what
functionality we actually care about (validation, not the data).
Related to https://github.com/instructlab/sdg/issues/160
=> utils: Drop reading of taxonomy data

requirements.txt, scripts/test-data/e2e-qna-knowledge.yaml
See epic instructlab/sdg#160 for more information.
cc71e8b requirements: Make use of knowledge v3 versions of dependencies
fd50d86 e2e: Update knowledge sample to a v3 example
commit cc71e8bef521d04d112da116590f0bf427580475
Date:   Thu Jul 18 16:19:51 2024 -0400
requirements: Make use of knowledge v3 versions of dependencies
commit fd50d866bea75991de902f5749ceee63c3dc5d25
Date:   Thu Jul 18 16:20:45 2024 -0400
e2e: Update knowledge sample to a v3 example
The knowledge schema changed to v3. Older versions are no longer
supported. Update our testing accordingly.
=> Knowledge v3 support

.github/workflows/e2e-nvidia-a10g-x4.yml
This PR ensure vLLM can be installed correctly in the 4xA10 workflow. Separate PRs will ensure the `-v` flag to basic-workflows.sh is utilized.
=> ci: support vLLM installation in 4xA10 workflow

src/instructlab/train/linux_train.py, src/instructlab/utils.py, tests/test_lab_train.py
Due to differences in the design of the training & generate in the original ilab implementation and 
what we had in the dedicated SDG and full model fine-tuning pipelines, the datasets that we are generating are incompatibile.
Specifically, instructlab/sdg currently outputs datasets in the HuggingFace messages format, while ilab expects a dataset in the format of:
```py
dataset = [
{
"system": "You are a friendly assistant",
"user": "What is 2+2?",
"assistant": "2+2=4"
}
]
```
This PR introduces a shim which detects whether the provided dataset is using the legacy format or the messages format, and provides a conversion if necessary.
**Note**: This conversion can only go in one direction, as the messages format includes additional metadata. Here is a sample in the messages format:
```json …
```
=> Provide a conversion utility to ensure that the datasets being provided to legacy train are compatible

CHANGELOG.md, scripts/functional-tests.sh, src/instructlab/configuration.py, src/instructlab/model/test.py, tests/test_config.py
After #1471 was merged, @tiran raised #1705 which highlighted that downloaded models are now stored in persistent storage (aka `XDG_DATA_HOME`), when they should really be stored in `XDG_CACHE_HOME`. Further investigation on my part revealed that trained models are actually being stored in cache as well - something we want to avoid, since there seems to be general agreement that trained models should be treated like persistent user data.
This PR updates those locations to be more consistent: downloaded models now go to the cache, and trained models now go to persistent storage.
CC: @RobotSail @tiran  
Resolves #1705 
**Checklist:**
=> Update model storage locations to better reflect permanent vs ephemeral data

src/instructlab/model/evaluate.py, tests/test_lab_evaluate.py
While testing Eval, I noticed we are passing a GGUF file by default to the `evaluate` command but Evaluation won't fully support GGUF until https://github.com/instructlab/eval/issues/50 is complete
I filed https://github.com/instructlab/instructlab/issues/1792 to track this on the CLI side, but adding this minor check as well in the meantime
**Checklist:**
=> fix: add checks to ensure evaluate model args are valid

Makefile, pyproject.toml, tests/conftest.py, tests/test_config.py, tests/testdata/default_config.yaml
A new test compares the config from `get_default_config` against a default config file in VCS. This allows us to track any change in the git history.
See: #1725 
**Checklist:**
=> Add test to track config file changes

src/instructlab/model/serve.py, tests/test_lab_serve.py
The serve cli has 3 options that won't do anything when the vllm backend is used, namely:
* gpu_layers
* num_threads
* max_ctx_size
If the user passes:
```
ilab model serve --backend --max-ctx-size 2048
```
A warning will be printed indicating the option is not supported:
```
WARNING 2024-07-18 10:38:21,649 instructlab.model.serve:203: Option
--max-ctx-size not supported by the backend.
```
Closes: https://github.com/instructlab/instructlab/issues/1773
**Checklist:**
=> chore: warn when vllm is used with unsupported arguments

.github/workflows/test.yml, CHANGELOG.md, scripts/functional-tests.sh, src/instructlab/configuration.py, src/instructlab/model/download.py, src/instructlab/utils.py
Check if `repository` supplied during `ilab model download` meets the URL structure of an OCI registry, if so leverage skopeo to copy image layers into cache, and apply mapping logic to move the model files into the permanent models directory. This PR also refactors existing `ilab model download` code to introduce base and implementation classes to support multiple downloading backends (HF vs OCI)
assumes `skopeo` is installed on the system
based off of https://github.com/instructlab/instructlab/issues/1687#issuecomment-2226731736
Resolves #1687 
**Checklist:**
=> feat: Support downloading models from OCI Registries 

requirements.txt, requirements/hpu.txt
PyTorch 2.4.0 has been released, but for now we want to keep the upper bound for this dependency to 2.3.z
**Checklist:**
=> deps: limit upper bound for torch dep to 2.3.z

src/instructlab/configuration.py, tests/test_lab.py
My commit 15c9df78 introduces a bug in config loading. A missing or invalid `config.yaml` no longer raised an error. The bug was originally found by Alina Ryan.
The test suite now checks for required and optional config file for every command and sub command.
Resolves #1834
Resolves #1831
**Checklist:**
=> Fix config error reporting

.github/workflows/e2e-nvidia-a10g-x1.yml, .github/workflows/e2e-nvidia-a10g-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml, .github/workflows/e2e.yml
Install instructlab with `cuda` optional dependency. This installs `instructlab-training[cuda]` with `bitsandbytes` and `flash-attn>=2.4.0`.
To workaround a packaging bug in flash-attn<=2.6.1, first install instructlab without optional dependencies, then install it again with `cuda` optional dependency, packaging, and wheel. flash-attn needs Torch, wheel, and packaging to build without declaring the build dependencies.
Is related to #1821 but does not resolve it.
**Checklist:**
=> Install instructlab[cuda] with flash-attn workaround

scripts/functional-tests.sh, tox.ini
Since #1471, the directory structure has changed and the functional test was altered to setup the new directory and create a temporary directory for the test data. While this makes sense when running on a fresh new runner, this makes the local test quite annoying since:
a new temp is created
a model is downloaded in this directory
Now, for local users, the script can be run like this:
```
SKIP_TEST_DIR_CLEANUP=1 TEST_DIR=/tmp/foo ./scripts/functional-tests.sh
```
This assumes you control your test directory and its cleanup.
Closes: https://github.com/instructlab/instructlab/issues/1774
**Checklist:**
=> test: allow func test to use a specific temporary directory

tests/test_lab_config.py
Our cliRunner mixes stderr and stdout (mix_stderr=True is the default for the click runner.) So, accessing result.stderr won't work.
=> tests: Don't access result.stderr from cliRunner

src/instructlab/config/init.py
Since 3c73191ebd6bda30f760456769e092d8a2467bbe the message doesn't make sense, as it's not in the current directory. The message needs to be adjusted.
=> init: adjust config found prompt

CHANGELOG.md, src/instructlab/config/init.py, src/instructlab/configuration.py, src/instructlab/lab.py, tests/test_lab_config.py
When the env var `ILAB_GLOBAL_CONFIG` is set, that config is used as the
template to render the ~/.config/instructlab/config.yaml user space
config. The interactive mode is skipped when calling `ilab config init`.
This works at the `ilab` main entrypoint, this can be used to specify a
different configuration file too when running any commands.
This ensures defaults like taxonomy repos, base models, etc, are honored
from the global config.
Co-authored-by: Sébastien Han <seb@redhat.com>
Signed-off-by: Charlie Doern <cdoern@redhat.com>
**Checklist:**
=> Add support for an `ilab` global config

requirements-vllm-cuda.txt
Release includes 2 patches:
- Support for allowed_token_ids request parameter
+ Necessary for SDG
- bitsandbytes support for reading pre-quantized models
+ Necessary to serve quantized training library checkpoints
No tests are added since these will be covered by the e2e improvements
=> chore: Bump vLLM version to 2024.07.24 on ODH branch

src/instructlab/model/backends/backends.py
We don't expect any `ValueError` coming from `is_model_safetensors()`.
So the try-expect is not needed.
Closes: https://github.com/instructlab/instructlab/issues/1866
Co-authored-by: Ihar Hrachyshka <ihrachys@redhat.com>
**Checklist:**
=> fix: remove useless try-expect

.spellcheck-en-custom.txt, CHANGELOG.md, pyproject.toml, scripts/basic-workflow-tests.sh, src/instructlab/model/backends/backends.py, src/instructlab/model/list.py, src/instructlab/model/model.py, tests/test_lab.py
`ilab model list` prints a table of all models in ~/.local/share/instructlab/models. Both GGUF and Safetensor models. This cmd also takes a `--list-checkpoints` flag that will expose the checkpoints generated by `ilab model train`. These live in ~/.cache/instructlab/checkpoints
also adds an e2e test checking functionality of gguf and safetensor models
an example output of this command looks like:
```
+------------------------------+---------------------+----------+
| Model Name                   | Last Modified       | Size     |
+------------------------------+---------------------+----------+
| merlinite-7b-lab-Q4_K_M.gguf | 2024-07-24 16:01:57 | 4.1 GiB  |
| instructlab/granite-7b-lab   | 2024-07-24 16:17:39 | 12.6 GiB |
+------------------------------+---------------------+----------+ …
```
=> add `ilab model list`

src/instructlab/model/evaluate.py, tests/test_lab_evaluate.py
currently there is no indication to users what model is being used when running evaluation. this PR exposes this so it is always clear to the user what is going on.
**Checklist:**
=> evaluate: add stdout line to show what model is being evaluated

.github/workflows/test.yml, tests/conftest.py
Mock patch default setting for `--config-file` option in `tmp_path_home` to ensure that tests are properly isolated from the user's environment.
Resolves #1886
**Checklist:**
=> Properly isolate tests from default config

CHANGELOG.md, src/instructlab/model/train.py
Currently, when we train models we always save in a directory relative to the caller called './models'.
This PR updates the legacy training code to save checkpoints into the global checkpoints directory.
**Checklist:**
=> Updates legacy training to save in global checkpoints directory

.spellcheck-en-custom.txt, CHANGELOG.md, TROUBLESHOOTING.md, scripts/basic-workflow-tests.sh, src/instructlab/data/generate.py
Epic: https://github.com/instructlab/sdg/issues/135
Requires: https://github.com/instructlab/sdg/pull/157
When using a serving backend that supports batches of requests (i.e. vLLM), the current SDG pipeline sends the entire dataset as a single large batch of requests to the OpenAI server. This may lead to some requests waiting too long for the response, resulting in timeout errors and potentially overloading the backend server with extremely large batches.
SDG now supports launching parallel tasks to send smaller batches in parallel to the OpenAPI server. This is controlled by the `batch_size` argument to `generate_data()`:
* `batch_size=None` - use the library's built-in default batch size ([currently 0](https://github.com/instructlab/sdg/blob/ca30d98bac7922a095bfb661cef1851ffc2df373/src/ …
=> Enable SDG batching with vLLM

CHANGELOG.md, src/instructlab/configuration.py, tests/test_config.py
There is a bug currently where lora_quantize_dtype under the training config cannot take on
values of null. The valid range of values for this field are either "nf4" or null,
however; the CLI only permits nf4 as valid input - ensuring that all models
will be quantize during training. This commit fixes that bug so now the valid
values will be "nf4" or null
**Checklist:**
=> fix: allow for lora_qunatize_dtype to be null

requirements.txt, src/instructlab/data/generate.py
As a continuation of: https://github.com/instructlab/instructlab/pull/1889
Related to: https://github.com/instructlab/sdg/issues/195
By default this puts checkpoints under: ~/.local/share/instructlab/datasets/checkpoints/
**Checklist:**
=> Adding checkpoint dir when batching enabled

src/instructlab/utils.py
`ilab taxonomy diff` currently claims the total number of errors is the equivalent of the number of files with errors. This is sometimes but not always the case. Updated the message to paint a more accurate picture.
Resolves #1898
**Checklist:**
=> fix: modify diff exception wording to accurately reflect number of errors

src/instructlab/model/backends/vllm.py, tests/test_backends.py
When loading a bitsandbytes quantized model with vllm, we need to ensure that the `--quantization` and `--load-format` args are appropriately set to `bitsandbytes`, otherwise the model cannot be loaded. This PR introduces the logic to check whether a model is vllm quantized and adjust the `vllm_args` accordingly.
**Checklist:**
=> Add autodetection and vllm arg adjustment for bitsandbytes quantization

src/instructlab/model/chat.py, src/instructlab/model/download.py, src/instructlab/model/evaluate.py, src/instructlab/model/list.py, src/instructlab/model/serve.py
Adds missing descriptions on the evaluate and download commands in the ilab model help screen. Also, capitalizes the List help text to be consistent with the others.
**Checklist:**
=> Add missing ilab model help screen descriptions

src/instructlab/configuration.py
the additional_args file as well as many persistent storage dirs are re-created on each ilab invocation. Only create them if they do not exist.
resolves #1704
**Checklist:**
=> only create persistent storage files/dirs when needed

src/instructlab/model/download.py
Change skopeo error messages to warning when recommending a version upgrade or unable to determine version. Only emit error logs if skopeo is not installed on the system
**Checklist:**
=> fix: downgrade skopeo log msgs to warning level from error level

README.md
**Issue:** #1874 
**Description:** Fix the wording and formating in the README about the venv python environment
=> Fixing venv wording in README

src/instructlab/configuration.py, src/instructlab/data/generate.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/evaluate.py, src/instructlab/model/linux_test.py, tests/test_lab_model_test.py, tests/testdata/default_config.yaml
since generation can implicitly start servers, it at the very least needs to be able to set the amount of GPUs to run generation on when using vllm
resolves #1921
**Checklist:**
=> add --gpus to `ilab data generate`

src/instructlab/taxonomy/diff.py, src/instructlab/utils.py, tests/test_lab_diff.py
As discussed in https://github.com/instructlab/instructlab/issues/1899 and https://github.com/instructlab/instructlab/issues/1306 there is currently no indication to CLI users that `.yml` files are not supported for the taxonomy. This PR adds a warning log line to the CLI output to communicate that any files in the taxonomy not named `qna.yaml` are invalid and won't be checked as part of `ilab taxonomy diff`.
Example output:
```bash
(venv) [ec2-user@ip-10-0-7-10 instructlab]$ ilab taxonomy diff
WARNING 2024-07-30 19:18:27,919 instructlab.utils:174: Found a 'qna.yml' file: compositional_skills/writing/freeform/foo-lang/qna.yml: taxonomy files must be named 'qna.yaml'. File will not be checked.
WARNING 2024-07-30 19:18:27,937 instructlab.utils:174: Found a 'qna.yml' file: …
```
=> refactor: strictly require `qna.yaml` filename for `ilab taxonomy diff`

CHANGELOG.md, src/instructlab/data/generate.py, src/instructlab/model/chat.py, src/instructlab/model/evaluate.py, src/instructlab/utils.py
When `ilab model chat` is executed, it tries to find the default model being served
and use that when available. However; this behavior was not properly updated when
extending support for serving models via vLLM. As a result, the current code assumes that
the default model being served is the one which is specified as a default in the config.
Since users may instead download and serve a different model path, ilab model chat will
fail to detect and select this model when running ilab model chat.
This commit updates this behavior by introducing a default endpoint that ilab model serve
will commonly serve on (http://127.0.0.1:8000/v1), and checks to see if there is a
model being served at that endpoint when no other endpoint is specified. If the check
fails, then ilab model chat will proceed …
=> fix: allow chat to resolve the local model being served

src/instructlab/model/list.py
With the introduction of models using OCI images as the delivery mechanism, it is necessary to follow the symlinks in order to properly show the size of the image.
**Checklist:**
=> fix: make `model list` show correct size

.spellcheck-en-custom.txt, CHANGELOG.md, src/instructlab/utils.py, tests/test_lab_train.py, tests/test_utils.py
PR #1644 introduced a dataset conversion utility which provided the ability for datasets
in the HuggingFaces messages format to be converted into the legacy format used by Linux train.
However; SDG is now planning on providing a pretraining dataset which is represented as
phase007. This new dataset will usually only contain only a single message which can be identified
by the `pretraining` role inside the `messages` list. E.g.:
```json
{
"messages": [
{
"role": "pretraining",
"content": "<|user|>Why did the chicken cross the road?<|assistant|>To get to the other side!"
}
]
}
```
This PR provides support for this new dataset format by identifying if a dataset contains the
`pretraining` sample and then parsing it out to map into the legacy sample format:
```json
{
"user": "Why did the …
```
=> Support the pretraining samples in the legacy dataset conversion utility

requirements-vllm-cuda.txt
- includes punica kernels required by LoRA adapters
=> chore: update vllm tag to 2024.08.01

src/instructlab/configuration.py, src/instructlab/data/generate.py, src/instructlab/model/backends/backends.py, tests/test_config.py
1st commit:
```
set teacher.vllm.llm_family from model_family flag.
This was only being set for the llama_cpp backend.
```
2nd commit:
This commit changes the following with
regard to get_model_family in configuration.py:
1. rename "forced" to "family" in the function
to make it more readable.
2. get_model_family() was always guessing the
model_family even if a valid family was input.
Now if a valid family is input, it returns that.
3. add debug logging in backend.py to see the
result of get_model_family()
4. add a case in test_get_model_family() for when
model_family == "" which is it's default value
in the serve config and in other places in the
code base.
For anyone tracing through the code, here are the calls that lead to `get_model_family()`
```
1. data/generate.py -- model_family is …
```
=> Model family vllm data generate & `get_model_family()` fixes

src/instructlab/configuration.py, src/instructlab/model/evaluate.py, tests/testdata/default_config.yaml
Along the way we disabled the ability for vllm to download the model.  This default config change is reccognizing where the model should be when downloaded if using prometheus.  If we want to enable the auto download feature in the future, we should instead use the ilab download capability so the model ends up in the model cache.
Thanks to @JamesKunstle for pointing out this issue!
**Checklist:**
=> Updating default location for judge model to be a local model in the cache

scripts/basic-workflow-tests.sh, src/instructlab/configuration.py, src/instructlab/model/train.py, src/instructlab/utils.py, tests/testdata/default_config.yaml
`ilab model train --strategy=lab-multiphase` added to support phased training that accomplishes the phased training of the LAB paper.
Phase1 training followed by MMLU checkpoint evaluation, followed by Phase2 training, with the final checkpoint selected via MT-Bench.
Closes #1729, with further to-do list included on that issue that needs to be broken down into subsequent issues.
=> adds phased training to CLI

src/instructlab/data/generate.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/evaluate.py, tests/test_lab_model_test.py
Previously, if vllm failed to start and raised an exception, the logic would have tried until its max attempts ran out to connect to a server that had already died.  This new logic detects if the server process is stopped, and if so outputs a message to use --enable-serving-output to debug further if the option is available.  So users will get a quick failure and guidance on debugging.
**Checklist:**
=> Fail fast when vllm errors out and exits

src/instructlab/configuration.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/vllm.py, tests/testdata/default_config.yaml
With larger models, the existing ~5 mins timeout proved not to be sufficient on some hardware.  The longest startup times seen so far have been in the 8 min range.  This moves the default up to 20 mins and makes the retry attempts configurable.  The new config param is being added as optional so config changes aren't required.
**Checklist:**
=> Increase default vllm startup attempts and make configurable

README.md
=> doc: remove "testing doesn't work on Linux"

src/instructlab/model/train.py
@bbrowning caught that we were passing `phased_phase1_data` into `_run_phased_training` where it should have been `phased_phase2_data`
=> fix: wrong phased_phase2_data path into _run_phased_training

src/instructlab/model/download.py, tests/test_lab_download.py
Raise an error if user tries to specify version/tag within the supplied `--repository` instead of specifying the tag/version via `--release` when downloading models from OCI registries 
**Checklist:**
=> fix: log error if user supplies invalid repository for OCI download

.pylintrc, CHANGELOG.md, src/instructlab/config/init.py, src/instructlab/configuration.py
Add training profiles for the following GPU configs:
4x/8x A100/H100
2x A100/H100
4x L40
8x L40
8x L4
these are rendered into ~/.local/share/instructlab/internal/train_configuration/
also introduce ILAB_TRAIN_PROIFLE_DIR, and env var which when set will be used as the template dir to render the initial train profiles into ~/.local/share
The user will also now see an interactive menu on initialization to choose their train profile.
**Checklist:**
=> Add training profiles for GPU configs

src/instructlab/configuration.py, tests/test_config.py
Currently,  one cannot specify a partial config. This is a useful thing to do when you don't care about some/most fields in the cfg, just GPU related ones.
pydantic has a `@model_validator` which allows a pre-check to be run before erroring out for missing fields. What I did in this commit is for each class and nested sub-class in `ilab`
the user can now pass little to no entires and we will fill out the rest of the config for them using the defaults in `get_default_config`. This differs from the current behavior which only allows the `Optional` fields to be omitted.
This config format will be useful in the following scenario:
A user can specify a config like the following:
```
serve:
backend: null
chat_template: null
host_port: 127.0.0.1:8000
llama_cpp:
gpu_layers: -1
llm_family: '' …
```
=> feat: Add more robust config defaulting

src/instructlab/configuration.py
We introduced a few training profiles in an earlier PR. This commit updates the ordering of the
profile files so that the A100_H100_x8.yaml file is on the top to be consistent with the other
orderings, which are also in descending order.
**Checklist:**
=> chore: reorder location of config profiles

src/instructlab/config/init.py
Signed-off-by: James Kunstle <jkunstle@redhat.com>
=> fix: consistent list of train profiles in `ilab config init`

src/instructlab/config/init.py
This PR updates the formatting of the train profile init output:
Current:
```bash
Please choose a train profile to use:
0. A100_H100_x4.yaml
1. A100_H100_x8.yaml
2. A100_H100_x2.yaml
3. L40_x8.yaml
4. L40_x4.yaml
5. L4_x8.yaml
Enter the number of your choice [hit enter for the default] [-1]: 
Using default train profile.
Initialization completed successfully, you're ready to start using `ilab`. Enjoy!
```
After this PR:
```bash
Please choose a train profile to use:
[0] No profile (CPU-only)
[1] A100_H100_x4.yaml
[2] A100_H100_x8.yaml
[3] A100_H100_x2.yaml
[4] L40_x8.yaml
[5] L40_x4.yaml
[6] L4_x8.yaml
Enter the number of your choice [hit enter for the default CPU-only profile] [0]: 
Using default CPU-only train profile.
Initialization completed successfully, you're ready to start using …
```
=> ux: update init output for training profiles

CHANGELOG.md, README.md, src/instructlab/configuration.py, src/instructlab/data/generate.py, tests/test_config.py, tests/testdata/default_config.yaml
Most flags have config variable associated with them. The --pipeline flag for the `ilab data generate` command does not have a config variable associated with it. Ideally the `ilab data generate` command should need as few flags as possible once the config file is set.
**Checklist:**
=> feat: add pipeline into generate config

src/instructlab/configuration.py, src/instructlab/model/train.py
add the ability to turn LoRA off. Currently all of the LoRA config fields are mandatory and have strict defaults meaning LoRA is always on when called via the CLI.
Also make it so that if LoRA is used with --is-padding-free=True, we fail. In testing these two do not work together
resolves #1906
**Checklist:**
=> LoRA Adjustments

src/instructlab/configuration.py, tests/test_config.py
Expands env vars (Ex: $HOME) and user vars (Ex: ~) for config and training profiles.
**Checklist:**
=> Expand env vars and user dirs read from config

README.md
I've updated the readme to help folks who are setting up instructlabs and run into the following error:
`zsh: no matches found: instructlab[mps]`
This error occurs when try to execute the following command:
`pip install instructlab[mps]`
For some strange reason the terminal doesn't know what to do with the install and throw and error but if you wrap the package to install in quotes it works with out any issues
Solution:
`pip install 'instructlab[mps]'`
**Checklist:**
=> Update README.md Instructions Steps

pyproject.toml, src/instructlab/config/edit.py, tests/test_lab.py
This is a convenience command that will automatically launch your
${EDITOR} to edit the ilab configuration file. This saves typing out
the config storage location, or makes it so you don't have to remember
where it is.
=> Add 'ilab config edit'

src/instructlab/configuration.py
Currently we have an issue with a circular dependency inside the configuration code,
where we cannot include util code that imports from ilabclient in the utils module.
The reason why this happens is ilabclient also imports from configuration. But if we
have code which is technically a util, we cannot move it there for this reason.
**Checklist:**
=> hotfix: fix circular dependency issue

src/instructlab/configuration.py
This commit fixes the lora mappings to the train options and
sets the 'lora_quantize_dytpe' to a default of None.
**Checklist:**
=> lora followup to #1917

src/instructlab/config/init.py
If you pressed enter without specifying `y` or `N` when asked to clone taxonomy, it would by default not clone it, which would result in an empty taxonomy directory if you used the default taxonomy path. This change makes it so that the taxonomy is cloned unless you specify `n`.
Resolves #1951
=> make `ilab config init` clone taxonomy by default

scripts/functional-tests.sh
At first glance, these variables might seem unnecessary given that the
same Python call is done later, and `mkdir -p` will create everything.
The idea is only to create the base directory and let `ilab` create the
subsequent folders.
**Checklist:**
Should go **AFTER** https://github.com/instructlab/instructlab/pull/1762
=> tests: clarify the presence of some variables 

tests/test_lab_init.py
=> ilab init set default to "yes" for cloning down taxonomy if not existing

src/instructlab/config/init.py
An off-by-one bug made the last selection incorrectly considered out of bounds, which made the tool exit with an error.
Closes: #2015
**Checklist:**
=> Fix the last train profile selection

scripts/functional-tests.sh, src/instructlab/config/init.py, src/instructlab/configuration.py, tests/test_lab_config.py, tests/test_lab_init.py
`ILAB_GLOBAL_CONFIG` and `ILAB_TRAIN_PROFILE_DIR` had two unexpected behaviors:
1. `ilab config init` overwrites the cfg without warning the user when the env is set
2. get_params_from_env would overwrite all model paths with the serve model which it should not
3. `ilab config init` did NOT overwrite the train profiles, prompt the user that this is going to happen and add the functionality to overwrite
**Checklist:**
=> `ilab` global config fixes

src/instructlab/configuration.py
In the current LoRA parsing code, we do not set the lora_rank value from params into the lora
options object when we detect it. This commit fixes that issue.
**Checklist:**
=> hotfix: set lora alpha when detected

src/instructlab/configuration.py
Currently is_padding_free is broken (will always exit) due to current lora arg processing. This PR fixes that.
**Checklist:**
=> Fix training lora arg checking and exiting

requirements.txt, requirements/cuda.txt
This release includes a fix for the broken --lora-target-modules CLI option.
Closes: #2021
**Checklist:**
=> Bump min version for training to 0.3.2

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/vllm.py, tests/test_lab_serve.py, tox.ini
vLLM requires GPU vram usage to be stable when calculating its memory pools. A hard failure on start occurs when it detects this is not the case. This creates a racy failure condition for various InstructLab facilities, such as evaluation, which rely on multiple successive restarts.
Address the problem by introducing a cool down period after process termination. This will complete as early as 10s if VRAM stability is detected. In the event of in-flight reclamation this will wait as long as 30s.
Additionally address an issue where shutdown was being run twice.
No tests are included in this PR since the condition is racy. Coverage is provided by standard CI. In the future we should introduce a stress harness.
=> fix: introduce vram stability waiting

src/instructlab/configuration.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
steps of multiphase-training require different effective batch sizes.
This exposes that functionality and sets reasonable defaults.
Signed-off-by: James Kunstle <jkunstle@redhat.com>
EDIT: Blocker rationale:
`effective_batch_size` (ebs) needs to be a configurable parameter for each training phase. Phase 1 requires a very low ebs, 128, to parity the performance that was seen in testing, whereas Phase 2 accommodates a much higher ebs. Thus, we can't only pull a single ebs from general training config- the value has to be phase-specific.
=> exposes effective_batch_size for both of the training phases

src/instructlab/configuration.py
Today in the map_train_to_library function, we parse and set the lora options conditionally.
However; the LoraOptions class from instructlab/training has a default rank of 4.
Since we are not explicitly setting this value, when the ilab user sets this to 0, it will
retain the default of 0. This commit fixes this issue by explicitly initializing the rank to 0.
**Checklist:**
=> hotfix: fix issue where default lora rank is overwriting setting of 0

src/instructlab/configuration.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
currently we save checkpoints via save_samples. This adds the option to
save at the end of epochs as well.
Signed-off-by: James Kunstle <jkunstle@redhat.com>
EDIT: Blocker rationale:
Right now, checkpoint saving periodicity is configured with `save_samples`- every time we pass (# samples seen % save sames == 0) we save a checkpoint. However, this means that a user has to make a data-dependent checkpoint-saving calculation to pick a reasonable number. 
This fix adds the ability to just set a single flag that will tell training to save a checkpoint every epoch. This is hugely preferable because it's (1) better for user experience, (2) more consistent for testing (they don't have to set the value based on the dataset size, and won't have mysteriously missing checkpoints if (save_samples >> …
=> adds a switch so we can save checkpoints on epoch boundary

src/instructlab/configuration.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
set the defaults in pydantic for effective batch size
set the click flag range for save samples to be > 0 rather than > 1. Also change pydantic defaults
because save samples per phase is off by default, set checkpoint_at_each_epoch to true
**Checklist:**
=> fix: phased training fixes

src/instructlab/configuration.py, src/instructlab/data/generate.py, src/instructlab/model/evaluate.py, src/instructlab/model/serve.py
This should fix the following Traceback from data generate and similar commands:
```
INFO 2024-08-09 17:44:41,707 numexpr.utils:161: NumExpr defaulting to 4 threads.
INFO 2024-08-09 17:44:42,097 datasets:58: PyTorch version 2.3.1+cpu available.
File "/home/vagrant/git/instructlab/.tox/py311-unit/bin/ilab", line 8, in <module>
sys.exit(ilab())
^^^^^^
File "/home/vagrant/git/instructlab/.tox/py311-unit/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vagrant/git/instructlab/.tox/py311-unit/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/home/vagrant/git/instructlab/.tox/py311-unit/lib/python3.11/site-packa …
```
=> Fix Traceback when `--gpus` is used and `vllm_args` is `null` in config file

src/instructlab/config/init.py, src/instructlab/lab.py
currently if $ILAB_GLOBAL_CONFIG is set, it supercedes the ~/.config/instructlab/config.yaml in ALL scenarios. We only want $ILAB_GLOBAL_CONFIG to win when running `ilab config init`.
Therefore the `envvar=` should only be used on the command itself, and ignored everywhere else. This makes it so that `init` (a different function from ilab config init`) sets the ctx.obj.cfg value to the LOCAL file rather than the global one when running other commands
resolves #2042
**Checklist:**
=> honor ~/.config/instructlab/config.yaml

src/instructlab/config/init.py
currently we still ask the user for the path to their taxonomy and model even when reading from env, we should not do that.
[ WORKAROUND: You can simply hit enter and the right thing will happen. ]
resolves #2044
**Checklist:**
=> only prompt for taxonomy and model without env

.github/workflows/spellcheck.yaml
We need to remove the custom job name for the Spellcheck action so that it's compatible with the changes made here https://github.com/instructlab/instructlab/pull/1941
**Checklist:**
=> fix: remove custom spellcheck job name

.github/workflows/test.yml, src/instructlab/model/download.py
Currently we emit a warning message when we detect users trying to download models from OCI registries using skopeo < `v1.14.3`. We recommend they upgrade to `v1.15.0` out of an abundance of caution. It was determined through some manual effort that users only need to have skopeo >= `v1.9.0`. This is misleading to users as they think their model download might fail even though it won't, and might cause unnecessary confusion. This PR updates the recommended version to `v1.9.0` 
**Checklist:**
=> fix: update recommended skopeo version

scripts/functional-tests.sh, src/instructlab/clickext.py, src/instructlab/config/config.py, src/instructlab/config/init.py, src/instructlab/configuration.py, src/instructlab/data/data.py, src/instructlab/model/model.py, src/instructlab/system/system.py, src/instructlab/taxonomy/taxonomy.py, tests/test_lab.py, tests/test_lab_init.py
since creation of the train profiles is handled by `ilab config init` as well as
the persistent storage dir creation process, on a new system the train profiles dir
is always detected as existing. This creates a double re-write and prompts the user
asking them if they want to overwrite train profiles they didn't know existed.
Fix this by checking if ANY of the train profiles DNE when being created. If this scenario is
detected, do not prompt the user to recreate the profiles since they have just been created for the first time.
Also, `ilab config init` should be the only place that persistent storage dirs are created. Currently each time ANY ilab command is run, the ~/.local and ~/.config dirs are created if they do not exist. This PR makes it so that only `ilab config init` creates the …
=> do not re-create train profiles on fresh install

scripts/infra/cloud-instance.sh, scripts/infra/local-setup.sh
When running the following command,
cloud-instance.sh ec2
the output would be empty as the script would silently exit on the
`shift`. It is desirable to output the usage help text in this case.
Adjust the `ec2` and `ibm` handlers to handle this case and print the
usage text when no command is provided.
=> cloud-instance: Print help when only cloud type is passed

.github/workflows/e2e-nvidia-a10g-x1.yml, docs/ci.md, scripts/basic-workflow-tests.sh
This PR changes the following:
- Changes `f` flag to `L` and renames `FULLSIZE` training to `LEGACYTRAIN` to more accurately reflect what the flag is doing
- Updates ordering of `basic-workflow-tests.sh` flags to be alphabetical in both script `usage` func, `getopts` func, and docs
- Updates desc of several of the flags to be more in-depth
- Adds phased training flags to doc, which was previously missing
**Checklist:**
=> ci: update flags and descs for E2E script

src/instructlab/clickext.py
commands with names like `model_list` rather than `list` represent themselves with the function name not the command name. return the name when parsing aliases, not the attr so `model list` is printed rather than `model model_list`
before:
```
Aliases:
chat      model chat
convert   model convert
diff      taxonomy diff
download  model download
evaluate  model evaluate
generate  data generate
init      config init
list      model model_list
serve     model serve
sysinfo   system info
test      model test
train     model train
```
after:
```
Aliases:
chat      model chat
convert   model convert
diff      taxonomy diff
download  model download
evaluate  model evaluate
generate  data generate
init      config init
list      model list
serve     model serve
sysinfo   system info
test …
```
=> fix alias help text

scripts/infra/cloud-instance.sh
Add a new command to get details about the EC2 instance launched by
this script. In my case I wanted to get the public IP address, but
there's a lot of info in the output that might be useful.
=> cloud-instance: Add `ec2 details` command

src/instructlab/taxonomy/diff.py
This default value always results in the `DEFAULTS.TAXONOMY_DIR` being used when `--taxonomy-path` is not specified on the command line. This then ignores the `taxonomy_path` in the config.yaml.
Resolves: #2086
**Checklist:**
=> taxonomy: Remove click default for --taxonomy-path

CHANGELOG.md, README.md, requirements.txt, src/instructlab/data/generate.py, src/instructlab/taxonomy/diff.py, src/instructlab/utils.py, tests/test_lab_diff.py
This allows users to specify that they want all taxonomy files in their repo to be included, where 'null' symbolically represents the empty tree before this repo was created.
See also instructlab/sdg#242
**Checklist:**
=> taxonomy diff/data generate: support taxonomy-base=empty

src/instructlab/model/backends/vllm.py
vllm logging causes issues with instructlab libraries, but we want to ensure it's enabled when launching vllm itself.
Without this change, we aren't seeing most/all of the logging from vllm which makes debugging more difficult
Example of issue vllm logging causes when enabled globally: https://github.com/instructlab/eval/issues/65
Example of logging output we were missing:
```
INFO 08-18 13:42:36 distributed_gpu_executor.py:56] # GPU blocks: 199861, # CPU blocks: 16384
(VllmWorkerProcess pid=2533528) INFO 08-18 13:42:39 model_runner.py:1007] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=2533528) INFO 08-18 13:42:39 …
```
=> Ensure vllm logging is enabled

src/instructlab/configuration.py, src/instructlab/data/generate.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/evaluate.py, tests/test_lab_model_test.py, tests/testdata/default_config.yaml
The reason for adding retries is instructlab has to start and stop vllm a lot of times to work through its workflow end to end.  Whenever a component is susceptible to intermitent failures (which vllm seems to be with some hardware configurations) it risks the long running process failing as a whole.  Or to the last savepoint as much as they exist.  The goal of this logic is to retry vllm startups for all the startups that exist in long running processes.  For now the logic is set to retry once for generate, phased training, and evaluate.
Once we have some level of confidence this approach is reasonable and we do want a value in config, there is some concern that config already has a variable named max_startup_attempts which should really be something like max_startup_connect_attempts or …
=> Retry vllm startup for long running processes

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/vllm.py
In some cases, vllm may not be able to shutdown properly.  To handle that scenario, this logic adds one additional process group kill to make sure the child processes are cleaned up.  Nothing will happen if the vllm process is already shut down cleanly.
Example of it working:
```
DEBUG 2024-08-18 03:43:40,350 instructlab.eval.mt_bench_answers:29: {'answer_file': '/home/ec2-user/.local/share/instructlab/internal/eval_data/mt_bench/model_answer/test_model.jsonl'}
DEBUG 2024-08-18 03:43:40,351 instructlab.model.backends.backends:317: Sending SIGINT to vLLM server PID 1558425
DEBUG 2024-08-18 03:43:40,351 instructlab.model.backends.backends:321: Waiting for vLLM server to shut down gracefully
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown …
```
=> Add process group kill for vllm process

src/instructlab/data/generate.py
The `generate_data` argument list has become quite large.
It's necessary to refactor the code to maintain cleanliness and readability.
=> replace 6 arguments of generate_data() with client

scripts/infra/cloud-instance.sh
The logic was adjusted to pull in all the appropriate dependencies and lost the -e along the way.
**Checklist:**
=> Add back a pip -e . for instructlab in cloud-instance

requirements.txt, src/instructlab/taxonomy/diff.py, src/instructlab/utils.py, tests/test_lab_diff.py, tests/testdata/knowledge_unsupported.yaml, tox.ini
We replace parsing/validation code to use the shared code from instructlab-schema package.
**Checklist:**
=> Use instructlab-schema package to parse qna.yaml files

src/instructlab/model/evaluate.py
Previously, the eval library was defaulting to a base model adapter rather than selecting the specific one for the model.  Ideally this logic can be further improved to not rely on the correct name to be passed in.  Or at least separate the name from the type.
Resolves #2057
**Checklist:**
=> Use real model names to allow adapter selection to function

src/instructlab/model/train.py
Allow a user to set env var `INSTRUCTLAB_EVAL_MMLU_MIN_TASKS=True` to reduce phased training times for development and experimentation.
**Checklist:**
=> feat: reduce mmlu eval in phased training via env var.

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/common.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py
The backends module and modules llama_cpp and vllm have circular dependency, which is anti-pattern.
The backends module, along with the llama_cpp and vllm modules, have a circular dependencies, which is considered an anti-pattern."
This PR is intentionally kept small to facilitate an easier code review. The plan is to relocate the relevant code from `backends` to `common` in a subsequent PR, eliminating the circular dependency entirely.
Current state:
```mermaid
graph LR;
backends --> llama_cpp
llama_cpp --> backends
backends --> vllm
vllm --> backends
```
Desired state:
```mermaid
graph LR;
backends --> llama_cpp
llama_cpp -->common
backends --> common
backends --> vllm
vllm --> common
```
References:
1. https://en.wikipedia.org/wiki/Circular_dependency
2. …
=> introduce backends.common to reduce circular dependencies

tests/common.py
The combination of https://github.com/instructlab/instructlab/pull/2092 and https://github.com/instructlab/instructlab/pull/2046 broke the test cases.  This fix allows both scenarios to exist at the same time by allowing the vllm startup retry scenario within the common test case function.
Alternate fix for: https://github.com/instructlab/instructlab/pull/2115
**Checklist:**
=> Fix test case broken by conflicting changes

requirements.txt, src/instructlab/config/show.py, src/instructlab/configuration.py, tests/testdata/default_config.yaml
When you run `ilab config init` or `ilab config show`, the configuration will include comments before each option to describe its purpose, along with displaying the default value. This functionality is implemented using Pydantic Fields, which allow for metadata like a "description" field to be added. If the description is longer than 80 characters, it
will be broken into multiple lines.
Currently, not all options have documentation attached, but the code will automatically include any new descriptions as they are added.
Closes: https://github.com/instructlab/instructlab/issues/1943
**Checklist:**
=> feat: add comments to config options

src/instructlab/model/backends/vllm.py, src/instructlab/model/evaluate.py
The result of those tests showed ideal values for max_workers needs to take gpu and cpu counts into account.  The new recommendation does have a magic number but hopefully the suggestion range is large enough to account for the magic number potentially not being perfect.  Removing the magic number would require understanding the relative compute power of the gpus.
Also switching from multiprocessing.cpu_count() to len(os.sched_getaffinity(0)) to avoid cases where the instance has cpus that aren't available to the current process. (Thanks @jaideepr97 )
Resolves #2050 
**Checklist:**
=> Add better tuning for max_workers based on perf tests

src/instructlab/model/chat.py
select_backend needs `model_path=model` in order to honor `--model` in chat. Otherwise it always uses granite from the serve config.
**Checklist:**
=> `--model` is ignored in ilab chat when starting server

src/instructlab/config/init.py
when using taxonomy base from ENV, do not override with the default value from `get_params`
also place taxonomy path inside of this ENV check. If a user provides a global cfg with ANY of these paths, models, etc we should not override w/ the defaults
**Checklist:**
=> taxonomy base fix

scripts/functional-tests.sh, tests/test_lab_diff.py, tests/testdata/invalid_yaml.yaml
`instructlab-schema v0.4.1` disabled the line-length check and enforced a requirement for leaf nodes to be called `qna.yaml`. This PR reflects these updates to the testdata yaml files used in the CLI as part of the unit and functional tests
**Checklist:**
=> Update testdata yaml files to account for updated schema in instructlab-schema v0.4.1

requirements.txt
Bumping the minimum version of sdg library because of:
- Removal of parameters in the `generate()` API to force Open AI client to be passed (no longer initialized in the API)
- Schema parsing and validation now being called from the schema library instead
**Checklist:**
=> Bump min version of sdg lib to 0.3.0

scripts/basic-workflow-tests.sh
Also changes `test_serve` to use local MODEL_PATH var - this makes the test function consistent with evaluate and phased training
**Checklist:**
=> refactor: use global shell var in e2e script for all granite safetensors instances

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/common.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py
Move verify_template_exists() to reduce the circular dependencies.
```mermaid
graph LR;
backends --> llama_cpp
llama_cpp --> backends
backends --> vllm
vllm --> backends
```
Desired state of [Acyclic dependencies](https://en.wikipedia.org/wiki/Acyclic_dependencies_principle):
```mermaid
graph LR;
backends --> llama_cpp
llama_cpp -->common
backends --> common
backends --> vllm
vllm --> common
```
=> refactor: move verify_template_exists to common

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/vllm.py, tests/common.py
ensure_server is used only by vllm.
Move it to reduce circular dependency between backends.py and vllm.py.
Slightly adopt the function on the new place.
References:
- https://en.wikipedia.org/wiki/Circular_dependency
- https://en.wikipedia.org/wiki/Acyclic_dependencies_principle
=> refactor: move ensure_server() to vllm.py

src/instructlab/data/generate.py
Related: https://github.com/instructlab/sdg/pull/194
=> refactor: remove deprecated argument of generate_data() `logger`

docs/release-strategy.md
we have been sending slack and email announcements for each z-stream we release. This should be amended to be up to the release team if an announcement is necessary. Not all releases with ~1 or 2 commits warrant multiple messages
**Checklist:**
=> amend release strategy

.github/workflows/e2e-nvidia-a10g-x1.yml, .github/workflows/e2e-nvidia-a10g-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml
right now we can see what type of runner and which repository an AWS runner is associated with, but not which commit triggered it
**Checklist:**
=> ci: add AWS tag to show github ref for all jobs

src/instructlab/configuration.py, tests/test_config.py, tests/testdata/default_config.yaml
All the defaults are coming from the Field(default), thus using the
@model_validator to populate default values is not needed anymore.
Also, the @model_validator is typically used for custom logic, like if
you have more complex logic for setting defaults, such as computing them
based on other fields or some external data, the model_validator could
be necessary. However, in this case, the logic is simply setting the
default values, which Pydantic can already do through Field().
A few options with default_factory were incorrect too, we don't need a
lambda here. The default_factory should directly reference the callable
that returns an instance of the class.
Co-Authored-By: Ihar Hrachyshka <ihrachys@redhat.com>
**Checklist:**
[conventional …
=> chore: remove unecessary @model_validator

pyproject.toml
Mypy was failing to lint classes using the mlx dependency because mlx is conditionally imported only on macOS. Since mypy performs static analysis, it requires access to all imported modules to analyze their types. Running mypy in an environment without mlx installed (e.g., on
Windows or Linux) resulted in no linting errors while failing on
MacOS.
To avoid failing on MacOS we added a few files to the exclude list, so these will be skipped by mypy when running.
**Checklist:**
=> fix: mypy linting on MacOS

.github/mergify.yml, .github/workflows/e2e-nvidia-t4-x1.yml
currently the E2E PR job runs on every single PR
this commit aligns the triggering criteria for
the job with the mergify automerge criteria
**Checklist:**
=> e2e: only run PR job if certain files are changed

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/common.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/serve.py
Move Closeable and ServerException to reduce the circular dependencies.
```mermaid
graph LR;
backends --> llama_cpp
llama_cpp --> backends
backends --> vllm
vllm --> backends
```
Desired state of [Acyclic dependencies](https://en.wikipedia.org/wiki/Acyclic_dependencies_principle):
```mermaid
graph LR;
backends --> llama_cpp
llama_cpp -->common
backends --> common
backends --> vllm
vllm --> common
```
=> refactor: move Closeable and ServerException to common

CHANGELOG.md, README.md, requirements.txt, scripts/functional-tests.sh, src/instructlab/configuration.py, tests/test_config.py
Currently we use the `platformdirs` package to automatically pick the platform specific system directories that are used by instructlab. While this works fine on linux with XDG dirs, On macOS this means usage of `/Users/<user>/Library/Application Support/...` which is awkward and hard to use
This PR replaces `platformdirs` with `xdg-base-dirs` to standardize the dirs across linux and macOS
acc to https://pypi.org/project/xdg-base-dirs/ `xdg-base-dirs` functions take XDG env vars into account so we get env var support for free with this package 
There is a consideration to be made that we are making a change to the project's dependencies by making this switch so that should be taken into account 
Resolves #1747 
**Checklist:**
[conventional …
=> chore: replace platformdirs with xdg-base-dirs 

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/common.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, tests/test_backends.py
Move free_tcp_ipv4_port() to reduce the circular dependencies.
```mermaid
graph LR;
subgraph backends
x[free_tcp_ipv4_port]
style x opacity:0
select_backend
style select_backend opacity:0
end
backends --> llama_cpp & vllm
linkStyle 0,1 opacity:0
select_backend --> llama_cpp & vllm --> x
```
Desired state of [Acyclic dependencies](https://en.wikipedia.org/wiki/Acyclic_dependencies_principle):
```mermaid
graph LR;
subgraph backends
a[ ]
style a opacity:0
select_backend
style select_backend opacity:0
end
backends --> llama_cpp & vllm
linkStyle 0,1 opacity:0
select_backend …
```
=> refactor: move free_tcp_ipv4_port() to common

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/common.py, src/instructlab/model/backends/vllm.py
Move safe_close_all() to reduce the circular dependencies.
```mermaid
graph LR;
subgraph backends
x[safe_close_all]
style x opacity:0
select_backend
style select_backend opacity:0
end
backends -->  vllm
linkStyle 0 opacity:0
select_backend -->  vllm --> x
```
Desired state of [Acyclic dependencies](https://en.wikipedia.org/wiki/Acyclic_dependencies_principle):
```mermaid
graph LR;
subgraph backends
a[ ]
style a opacity:0
select_backend
style select_backend opacity:0
end
backends -->  vllm
linkStyle 0 opacity:0
select_backend -->  vllm -->x
subgraph common …
```
=> refactor: move safe_close_all() to common

src/instructlab/configuration.py, src/instructlab/data/generate.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
Wherever it was easily feasable, the `default=lambda:` options from the click option were removed. The defaults are coming from the internal Config object.
Partially solves: https://github.com/instructlab/instructlab/issues/1684
**Checklist:**
=> fix: remove unnecessary default lambda

.github/workflows/e2e-nvidia-a10g-x4.yml
not a lot of work tends to happen between 8 PM and 8 AM UTC, as such any regressions caught by the
8PM job likely would not be fixed by the 8AM job run
**Checklist:**
=> refactor: run E2E cron job once a day instead of twice

src/instructlab/configuration.py, src/instructlab/data/generate.py, tests/test_config.py, tests/testdata/default_config.yaml
instructlab.sdg.generate_data doesn't use argument
`prompt_file_path` anymore.
TODO: remove the argument from generate_data() completely.
=> refactor: remove unused argument prompt_file_path

src/instructlab/clickext.py, src/instructlab/data/generate.py, src/instructlab/model/chat.py, src/instructlab/model/evaluate.py, src/instructlab/model/serve.py, src/instructlab/model/train.py, tests/test_config.py, tests/test_lab.py
Our Pydantic model, referred to internally as Config, serves as the source of truth for default values and descriptions. When a Click CLI option is also present in the Config, it should inherit its default value and description from the corresponding Config field. When applying the cls=clickext.ConfigOption configuration to a Click option, fields such as “default” and “help” should not be specified, as these will automatically be derived from the Config object.
So this is how you should write an option that exists in the Config (ultimately in config.yaml) AND has a CLI option:
```
my_config_option: StrictStr = Field(
default="my_default_value",
description="Great description of what the option does",
)
@click.option(
"--my-config-option",
type=click.STRING,
cls=clickext.ConfigOption,
) …
```
=> feat: use default and description from Pydantic model

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/vllm.py, tests/test_lab_serve.py
Move shutdown_process to eliminate the circular dependency
vllm.py -> backends.
```mermaid
graph LR;
subgraph backends
x[shutdown_process]
style x opacity:0
select_backend
style select_backend opacity:0
end
backends --> vllm
linkStyle 0 opacity:0
select_backend --> vllm --> x
```
Final state of [Acyclic dependencies](https://en.wikipedia.org/wiki/Acyclic_dependencies_principle):
```mermaid
graph LR;
subgraph backends
select_backend
style select_backend opacity:0
end
subgraph vllm
v[Server]
style v opacity:0
x[shutdown_process]
style x opacity:0
end
select_backend -->  v …
```
=> refactor: move shutdown_process to vllm.py

scripts/functional-tests.sh, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/chat.py
When the internal server crashes, the errors will be displayed in the chat, as well as the progress logs from generate and other related commands.
Fixes: https://github.com/instructlab/instructlab/issues/889
**Checklist:**
=> fix: report server errors for chat/generate/eval

src/instructlab/model/download.py
if an HF repo doesn't have .safetensors, just .bin, `ilab model download` should still understand that it needs to download the entire repo.
add support for downloading .bin models
resolves #2022
**Checklist:**
=> add .bin support to `ilab model download`

CHANGELOG.md, pyproject.toml, scripts/functional-tests.sh, src/instructlab/clickext.py, tests/test_lab.py, tests/test_lab_config.py, tests/test_lab_init.py
This change removes a majority of the aliased commands, except `chat`,
`generate`, `serve`, and `train`. When a user attempts to use an alias
that was removed, it errors out. If a user types an alias that was kept,
it proceeds with the command.
Also updates the relevant test files.
**Checklist:**
=> Deprecate aliased commands

Makefile, containers/README.md, containers/cuda/Containerfile, containers/cuda/intel-oneapi.repo
This change modifies the Containerfile for NVIDIA CUDA to:
- Use CentOS Stream 9 as the default base image. UBI9 also works
- Install the NVIDIA packages from NVIDIA repository for exact CUDA version
- Add NVIDIA scripts from `nvcr.io/nvidia/cuda` image for copyrights...
- Install the Python packages in a Python 3.11 virtualenv
- Install instructlab package from PyPI
- Allow specifying the instructlab version at build time
- Make the final container rootless
Resolves #899
Replaces #932
Replaces #994
=> Refactor the CUDA container spec

CHANGELOG.md, Makefile, containers/hpu/Containerfile, docs/habana-gaudi.md, requirements.txt, requirements/hpu.txt, src/instructlab/train/linux_train.py, tests/test_package.py
Update to latest Intel Gaudi software 1.17.1. The new release comes with PyTorch 2.3.1a0, Python 3.11, and official RHEL 9.4 support.
**Checklist:**
=> Intel Gaudi: update to 1.17.1 with Python 3.11

.github/workflows/e2e-aws-custom.yml
This adds a custom workflow for testing one-off combinations of test
variables. The following may be specified as arguments when
dispatching the workflow:
- Which git branch or PR to run the tests against
- Which AWS instance type to use
- What install target to use for this repo (`.` or `.[vllm]`, for
example)
- What arguments to pass to the `e2e` script, which control which
combinations of features get tested
=> e2e: Add a custom paramaterized workflow

README.md
This Pull Request fixes the line break issue in the Mermaid diagram within the README.md file. The `\n` has been replaced with `<br/>` to ensure proper rendering of line breaks in the diagram.
=> docs: Fix line break issue in Mermaid diagram in README.md

.spellcheck-en-custom.txt, CHANGELOG.md, scripts/functional-tests.sh, src/instructlab/configuration.py, src/instructlab/log.py, src/instructlab/model/serve.py, tests/test_config.py, tests/testdata/default_config.yaml
Using the new `log_format` option under the `general` section of the
config file, we can now configure an alternative log format that suits
our needs.The default line remains the same, however if you want to
remove timestamps from the log message you should remove `%(asctime)s`.
Note: the formating is validated, but make sure you read the module
[attributes](https://docs.python.org/3/library/logging.html#logrecord-attributes)
when building the format string.
Closes: https://github.com/instructlab/instructlab/issues/1720
**Checklist:**
=> feat: configurable log formatter

src/instructlab/model/evaluate.py
As part of adding external serving for mmlu, the model_paths list wasn't being referenced as it should and was always passing the new model.
**Checklist:**
=> fix:mmlu_branch external serving not using base model

.spellcheck-en-custom.txt, CHANGELOG.md, src/instructlab/configuration.py, src/instructlab/model/evaluate.py, src/instructlab/model/train.py, tests/test_config.py, tests/test_lab_evaluate.py, tests/testdata/default_config.yaml
This capability takes advantage of the feature from the eval library which tunes max_workers according to the hardware configuration.  In order to accomplish this, effective gpus and max_workers="auto" needs to be passed to eval.  To accomplish this, gpus and effective gpus needed to be calculate earlier in the process.
This change also updates training to use get_gpus and max_workers=auto.  This means training now uses the gpu settings of evaluate when calling evaluate before defaulting to all gpus if not specified.
Resolves: https://github.com/instructlab/instructlab/issues/2079
https://github.com/instructlab/eval/pull/107 is now released enabling this change.
**Checklist:**
=> Add auto max_workers capability

src/instructlab/model/full_train.py
find_packing_max_batch_len_and_grad_accum used to take pad_id, with 0.5.0 in the training library, this has been removed. Change full_train.py accordingly
**Checklist:**
=> fix full_train.py

.spellcheck-en-custom.txt, CHANGELOG.md, src/instructlab/configuration.py, src/instructlab/model/evaluate.py, src/instructlab/model/phased_training.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
Adds a TrainingJournal object that represents a JournalModel pydantic
class. During phased training, an instance of the JournalModel is
updated and written to disk as progress is made.
In the event of an untimely exit from the training process, a
'journalfile.yaml' by convention, or a 'yaml' file by another name, can
be loaded into a "JournalModel" object and training can resume.
To-do:
Phased training is started with a command like:
```bash
ilab model train --strategy lab-multiphase \
--phased-phase1-data ./knowledge-data.jsonl \
--phased-phase2-data ./skills-data.jsonl
```
This will run phased training, storing checkpoints and metadata in `$HOME/.local/share/instructlab/phased`. 
Among the metadata stored is now a file `$HOME/.local/share/instructlab/phased/journalfile.yaml`, named by …
=> Implement phased training bookkeeping and better restarting

src/instructlab/configuration.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
To promote consistency in documentation between the CLI and the training library, this PR
updates the named of the parameter responsible for selecting between FSDP & deepspeed to
"distributed_backend", since it is already assumed to be a part of training, this
eliminates redundancy.
**Checklist:**
=> chore: rename distributed_training_backend -> distributed_backend

src/instructlab/configuration.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
It's been experimentally idenfitied that running MMLU to pick out phase1 output checkpoint is not ideal. This removes MMLU and communicates the more optimal 7 epochs of training for phase 1.
=> removes MMLU evaluation from multi-phase training

requirements.txt, requirements/cuda.txt
Removing alpha build option for minimum training library version
**Checklist:**
=> Bump instructlab-training requirement to 0.5.0

src/instructlab/model/train.py
The current implementation of checkpoint selection has a bug which is a result of the `sorted` function
not being able to correctly compare strings which all have an equal prefix and a numeric suffix.
This commit fixes that bug by explicitly telling `sorted` how to perform the comparison between items.
Fixes #2362 
**Checklist:**
=> fix: stabilize checkpoint selection logic

.github/workflows/image-cuda.yml
we no longer maintain the stable tag, ergo we
should no longer build it as part of this CI job
**Checklist:**
=> ci: remove cuda image build for "stable" tag

scripts/functional-tests.sh, src/instructlab/configuration.py, src/instructlab/defaults.py, src/instructlab/log.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/server.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/chat.py, src/instructlab/model/serve.py, tests/test_backends.py, tests/test_lab_model_test.py
Since we no longer pass loggers between modules, we've lost the ability to easily redirect stdout/stderr to a logger. Now, any encountered loggers will be redirected to the `log_file` if specified.
We had to introduce a new ServerConfig class to reduce the number of
attributes to BackendServer. However, only a few options were added to
avoid pylint failing. Later on, we will continue to move other
attributes into ServerConfig. But for now, let's keep the change
minimal.
Fixes: https://github.com/instructlab/instructlab/issues/1738, https://github.com/instructlab/instructlab/issues/2080
**Checklist:**
=> fix: enable server log to file

.github/actionlint.yaml, .github/workflows/lint.yml
- we used to use a self-hosted github gpu runner, this runner is no longer used, thus we can safely remove this config file
- the lint workflow used to use a 'ruff.sh' script, this is no longer the case, ergo we no longer need to trigger under this condition
**Checklist:**
=> chore: remove out-of-date runner config file and lint trigger

src/instructlab/config/init.py
due to ROCM's translation layer w/ CUDA, the torch.cuda.is_available() check evaluates to true. Since we don't have profiles for AMD yet, this code should not try to match the hw to an existing profile
**Checklist:**
=> fix: AMD should not trigger auto detection

src/instructlab/model/download.py
Removes `check_output=true` when running the skopeo downlaod as a subprocess to allow its output to show up on the terminal
**Checklist:**
=> fix: allow skopeo copy output to show up on terminal

src/instructlab/config/init.py, src/instructlab/configuration.py
`ilab config init` does not honor the profiles written to disk when auto detecting the best one for the system. Fix this by rendering the profile map by reading the applicable profiles from disk
**Checklist:**
=> train profile auto detection uses values from code not disk

README.md
- Includes new eval output
- Removes reference to GGUF not being supported for mmlu.  Was fixed in 0.19
- Removed separate examples for GGUF since they show the same output and are run the same way
- Uses a better judge model that doesn't have a high error rate
- Shows full mmlu output example
- Remove MIN_TASKS examples from main readme.  It's a development flag and shouldn't be highlighted as part of the main experience.
**Checklist:**
=> Update README with new eval output

src/instructlab/model/backends/backends.py, src/instructlab/model/backends/common.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/chat.py
The backends module, along with the llama_cpp module,
Move is_temp_server_running to common.py
to eliminate the circular dependency
llama_cpp.py -> backends.py.
=> refactor: move is_temp_server_running() to common.py

src/instructlab/configuration.py, src/instructlab/model/train.py, tests/testdata/default_config.yaml
Previously, the `disable_flash_attn` training flag was set as an additional argument that was hidden
away. However; we run into problems when running E2E testing in training where it cannot run on a T4
system (Volta GPU). This commit resolves that issue by promoting `disable_flash_attn` as a
first-class argument that can be passed as a CLI argument
**Checklist:**
=> feat: make flash-attention toggle a first-class option

.github/workflows/status-checks.yml
We need the fix to support pull_request_target target workflows properly. A bug in the wait-for-status-checks action looks at the wrong commit SHA (the target branch, e.g. main, instead of pull/nnn/head). The bug causes the ready check to look at the jobs from the last commit on the target branch not the last commit on the PR (pull/nnn/head).
**Checklist:**
=> e2e: Use fork of wait-for-status-checks action with needed fix

.github/workflows/lint.yml, .github/workflows/test.yml
Seen in https://github.com/instructlab/instructlab/pull/2409
Mergify expects `lint` and `test` to run on changes to requirements files at the top level of the repository as well as in the `requirements/` directory, but those actions were not getting triggered in the latter scenario.
**Checklist:**
=> fix: mismatch between requirements action trigger and automerge criteria

.github/workflows/e2e-aws-custom.yml, .github/workflows/e2e-nvidia-a10g-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-t4-x1.yml
`ilab system info` step has been removed from some jobs as this is now run as part of the E2E scripts themselves
**Checklist:**
=> ci: add disk check step and update AMI for all e2e runners

src/instructlab/model/backends/backends.py, src/instructlab/model/evaluate.py, src/instructlab/model/list.py, src/instructlab/utils.py, tests/test_backends.py
We currently handle all operations within the implementations of the CLI commands
themselves. This commit begins to refactor this by moving the implementation of
ilab model list to have the raw machinery exist in a seperate module named `machinery`
**Checklist:**
=> Begin decoupling listing logic from model list implementation

src/instructlab/model/convert.py
This commit addresses an issue where the source model directory (checkpoints) was being deleted prematurely during the conversion process. The problem occured when the checkpoints directory was passed in an incorrect format. As a result, users would lose their entire checkpoints directory and be forced to retrain their model.
**Checklist:**
=> Move source model deletion to end of convert

.github/mergify.yml, .github/workflows/e2e-nvidia-a10g-x1.yml
Also adds missing vllm requirements file for Medium E2E job
**Checklist:**
=> fix: mergify shouldn't require lint when script shell files are changed

src/instructlab/model/evaluate.py, tests/test_lab_evaluate.py
MMLU doesn't yet support gguf format with lm_eval.
Related: https://github.com/instructlab/instructlab/issues/2425
Related: https://github.com/instructlab/instructlab/pull/2426
**Checklist:**
=> Add explicit error message for gguf with mmlu

docs/ci.md, scripts/e2e-ci.sh
=> ci: move small-size E2E job to use `e2e-ci.sh`

.github/workflows/e2e-aws-custom.yml, README.md, docs/ci.md
previously the e2e custom job could only use the e2e custom script
with this change Maintainers can now also specify the usage of the e2e CI script to test changes
Resolves #2431
**Checklist:**
=> ci: make e2e script an arg for e2e custom job

src/instructlab/configuration.py, tests/testdata/default_config.yaml
effective batch size should be 64 for knowledge on a laptop which is what we focus on primarily
max batch len is too high for most laptops to work with. 5000 is a realistic max batch len for 64 GB of RAM following full SDG
**Checklist:**
=> fix: adjust training defaults for laptop

.github/workflows/e2e-nvidia-t4-x1.yml, .github/workflows/test.yml, CHANGELOG.md, scripts/e2e-custom.sh, scripts/functional-tests.sh, src/instructlab/config/init.py, src/instructlab/configuration.py, src/instructlab/defaults.py, src/instructlab/model/download.py, src/instructlab/model/linux_test.py, src/instructlab/model/test.py, tests/test_config.py, tests/test_lab_download.py, tests/testdata/default_config.yaml
The simple pipeline is not maintained actively. The full pipeline runs on laptops using the mistral-7b-instruct GGUF. This pipeline takes longer but yields very good results as compared to simple.
Switch the default model to mistral-7b-instruct-v0.2.Q4_K_M.gguf and the default SDG pipeline to full. Full does not work with merlinite due to prompt template incompatibility
I can provide sample outputs when using merlinite vs mistral, merlinite yields no results (0 generated samples), mistral yields ~150 from a small QNA + Wikipedia page.
Related to this change,   ilab model download by default downloads merlinite.
This should still happen for purposes of chatting with the model on your laptop.
However, --repository and --filename should be able to take multiple values and download each repo …
=> feat: Switch data generate and model download default behaviors

src/instructlab/model/download.py
allows specifying release to be downloaded per repo
addresses #2490 partially
**Checklist:**
=> fix: support specifying release per repo for download

src/instructlab/config/init.py, tests/test_lab_config.py
even though the defaults in the config file are mistral, ilab config init overrides these with merlinite due to some old logic that assumes merlinite is the model you want to use for everything
**Checklist:**
=> fix: ilab config init improperly sets generate model

src/instructlab/configuration.py
The amount of vRAM for single L40s is now set according to datasheet[1].
The profile for single A100 card has been added.
[1] https://resources.nvidia.com/en-us-l40s/l40s-datasheet-28413
Should partly address issues like #2451 
**Checklist:**
=> Setting proper amount of RAM for L40s and creating config for single A100

pyproject.toml, src/instructlab/cli/model/train.py, src/instructlab/model/accelerated_train.py, src/instructlab/model/evaluate.py, src/instructlab/model/simple_train.py, src/instructlab/model/train.py, src/instructlab/train/linux_train.py, tests/test_lab_train.py
`ilab model train` has many modes of operation. These various modes will eventually need to be different endpoints accessible to users via a REST API. Additionally, in order to implement process handling in `ilab` having the actual underlying functionality of each train loop in its own module which takes primarily primitive types will allow us to kick off and manage processes seamlessly once that work begins.  `multiprocessing` in python can only pickle certain objects, so I did my best here to remove click focused variables from the train loops and opt for raising exceptions back to `train.py` file. 
resolves #2400 
**Checklist:**
=> Split `ilab model train` click command from functionality

.spellcheck-en-custom.txt, README.md
Resolves #1354 : avoids some cases where llama_cpp_python isn't compiled with the intended build flags.
=> Prefer CMAKE_ARGS="-DLLAMA_XXX=yyy" pip install instructlab... instead of pip install instructlab... -C cmake.args="-DLLAMA_XXX=yyy"

src/instructlab/configuration.py
it will get the `TypeError` if something wrong with the config file.
```
$ ilab config show
File "/Users/instructlab/venv/bin/ilab", line 8, in <module>
sys.exit(ilab())
^^^^^^
File "/Users//instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users//instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/Users/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1685, in invoke
super().invoke(ctx)
File "/Users/instructlab/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params) …
```
=> enhance read_config

.github/workflows/e2e-aws-custom.yml
g6e instances aren't available in all zones yet.  Switching to one where they are available.
**Checklist:**
=> Update e2e custom zone to allow g6e instance types

src/instructlab/utils.py
- add a regular expression to match oci repo
```
docker://<registry>/<repository>:<tag>
command = [
"skopeo",
"copy",
f"{self.repository}:{self.release}",
f"oci:{oci_dir}",
"--remove-signatures",
]
```
since the `skopeo` use `repository` and `release` , repository should be for url part, and there is check for release, so try to a valid oci url.
**Checklist:**
=> robust check for oci repo

scripts/functional-tests.sh
Updates the OCI model download functional test to pull from https://quay.io/repository/instructlab/granite-7b-lab
fixes: #2197  
**Checklist:**
=> CI: update OCI model download test to pull from instructlab quay org

src/instructlab/model/download.py
This fix allows to download OCI artifacts which contains files in a given folder structure.
**Checklist:**
=> fix: allow OCI model folders

CHANGELOG.md, README.md, containers/cuda/Containerfile, requirements-vllm-cuda.txt, requirements.txt
**NOTE:** This PR is also relaxing the `torch` requirement to allow for the new vllm version to be installed, as it requires `2.4.0` - a proper upgrade will be done in https://github.com/instructlab/instructlab/pull/2445 
Partially addresses #2511
**Checklist:**
=> deps: update vllm tag to v0.6.2

docs/gpu-acceleration.md, notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
BREAKING CHANGE: Update PyTorch to 2.4
This change updaties the default Pytorch version to 2.4. It requires AMD ROCm >=6.1.
Intel Gaudi (HPU) remains on Intel fork of PyTorch 2.3.1, knowning that Intel Gaudi software v1.18 uses PyTorch 2.4.0a0.
It also requires the other repositories to update their dependencies accordingly, so it requires some coordination.
Fixes #2437
**Checklist:**
=> chore!: Update PyTorch to 2.4

CHANGELOG.md, containers/hpu/Containerfile, docs/habana-gaudi.md, requirements/hpu.txt
Update container, requirements, and documentation to latest Intel Gaudi software 1.18.0.524 with PyTorch 2.4.0.
Force rebuilding flash-attn with new Torch ABI.
Depends: #2437
Fixes: #2440
**Checklist:**
=> Update to Intel Gaudi software 1.18.0.524

src/instructlab/model/accelerated_train.py, src/instructlab/model/phased_training.py, tests/test_lab_train.py
This test exercises several of the paths for phased training to make sure the basic journaling is working as expected.  It first fails on the first phase, then fakes its way past phase 1, then asserts it starts on phase 2.
Also changes datetime.UTC to datatime.timezone.utc since .UTC wasn't added until 3.11
**Checklist:**
=> Add phased training unit test

src/instructlab/cli/model/train.py, tests/test_lab_train.py
Example output:
Unable to train with device=cpu and pipeline=accelerated
Resolves #2546
**Checklist:**
=> Handle case where training can't be run

src/instructlab/config/init.py, tests/test_lab_init.py
vram approximation should be >= not <. Using less than can lead to situations where we overmatch to a profile that can cause OOM situations. Making sure our profile is "overfit" for the vRAM makes more sense. However, there has to be a threshold here so we don't overfit in the other direction
=> fix: switch vram approximation

tests/test_lab_init.py
the vram approximation PR was not rebased before merging leading to a failing unit test. correct the text expected in the test
**Checklist:**
=> fix vram approximation test

docs/release-strategy.md
Also remove mention of the deprecated "stable" tag
**Checklist:**
=> docs: update release guidance to include lib dep cap

src/instructlab/configuration.py
when the user confirms they want to override their existing profiles. we should remove the entire directory. the directory being provided, if using $ILAB_SYSTEM_PROFILE_DIR, could have a different structure. If the directory structure differs, some leftover profiles could be left behind for selection
**Checklist:**
=> Ensure Deletion of Existing Profiles

src/instructlab/config/init.py, src/instructlab/lab.py
we've seen a lot of confusion from folks using deprecated Python versions installing 0.17 - adding a message to recommend folks use a support Python version so they can use the latest ilab
**Checklist:**
=> chore: add python deprecation notice to help and init

src/instructlab/configuration.py, tests/testdata/default_config.yaml
the project is beginnng to move away from DeepSpeed towards FSDP as our preferred training backend
this commit changes the default _train config class to use FSDP instead of DeepSpeed
Resolves #2521
**Checklist:**
=> config: change default training backend to FSDP

src/instructlab/cli/data/list.py, tests/test_lab_data_list.py
- use the model name and timestamp to distinguish the different  runs
User the model name and the timestamp to show it.
```
====> Currently:
generate one time:
$ ilab data list
+--------------------------------------------------------------------+---------------------+-----------+
| Dataset                                                            | Created At          | File size |
+--------------------------------------------------------------------+---------------------+-----------+
| test_mistral-7b-instruct-v0.2.Q4_K_M_2024-10-26T22_22_42.jsonl     | 2024-10-26 22:22:42 | 1.55 KB   |
| messages_mistral-7b-instruct-v0.2.Q4_K_M_2024-10-26T22_22_42.jsonl | 2024-10-26 23:08:52 | 78.61 KB  |
| train_mistral-7b-instruct-v0.2.Q4_K_M_2024-10-26T22_22_42.jsonl    | 2024-10-26 23:08:52 | …
```
=> optimize the list_datasets

src/instructlab/model/download.py, tests/test_lab_download.py
reformat the `download` output
e.g.
```
$ ilab model download
Downloading model from Hugging Face:
Model: instructlab/merlinite-7b-lab-GGUF@main
Destination: /Users/user/.cache/instructlab/models
Downloading model failed with the following Hugging Face Hub error:
(ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')), '(Request ID: eb0fd877-eae3-4799-b6a2-47422213a96f)')
Downloading model failed with the following error: 1
---------------
$ ilab model download --repository=TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF --filename=mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf
Downloading model from Hugging Face:
Model: TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF@main
Destination: /Users/user/.cache/instructlab/models
TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF requires a …
```
=> reformat the download output

src/instructlab/config/init.py, src/instructlab/defaults.py, src/instructlab/model/download.py
- Move the `DEFAULT_INDENT` to `defaults`, and use it in `init` and `download`
- And the existing profiles should use indent(merged in [2443](https://github.com/instructlab/instructlab/pull/2443)), and separate it.
```
ilab config init
Existing config file was found in:
/Users/xx/.config/instructlab/config.yaml
Do you still want to continue? [y/N]: y
Existing system profiles were found in /Users/xx/.local/share/instructlab/internal/system_profiles
Do you want to restore these profiles to the default values? [y/N]: n
$ ilab config init
Existing config file was found in:
/Users/xx/.config/instructlab/config.yaml
Do you still want to continue? [y/N]: y
Existing system profiles were found in:
/Users/xx/.local/share/instructlab/internal/system_profiles
Do you want to restore these profiles to …
```
=> use default indent constant for download and init

src/instructlab/config/show.py, tests/test_lab_config.py
- add the key option and use key to search the config
Improve the `show` command. [origin one 2264](https://github.com/instructlab/instructlab/pull/2264)
- Background
So far, `ilab config show` only simply print the `config.yaml`, and config become more and more according to the repo become stronger.
The issue is hard to read/search the config what we want. e.g. there are paths, model, data, train ..etc.
- add key search e.g. -k chat.model, easy to check the config
```
$ ilab config show -k version
1.0.0
$ ilab config show -k chat.model
/Users/xx/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf
```
**Checklist:**
=> add -k option for show

src/instructlab/cli/model/train.py, src/instructlab/model/full_train.py
Currently, full train only runs on hardware with 64GB of Memory.
With some optimizations, this can be cut down to a 16GB requirement, massively increasing the amount of users able to run this workflow.
`AutoModel` and `AutoConfig` both have a torch_dtype and low_cpu_mem_usage fields. setting the dtype to `auto` and `low_cpu_mem_usage` to True on all architectures yields improved results.
The _only_ caveat here is that Intel CPUs preform siginficantly worse when using the `torch_dtype=auto` setting. We should stick with fp32 on intel CPUs
**Checklist:**
=> Full Train Memory Optimizations

.spellcheck-en-custom.txt, scripts/infra/README.md, scripts/infra/cloud-instance.sh, scripts/infra/local-setup.sh
Supports syncing for the sdg, training, and eval repos to a remote instance for development purposes.  Repos are cloned onto the remote instance and installed with pip -e.  When synced, the delta is sent to the remote instance with git and extracted so it will take effect with the pip -e installed library.
This enables a workflow where instances are started and synced to from your local environment without having to setup an environment on the remote instance.
Two new commands are added:
```
setup-instructlab-library-devenvs - Initialize development environments for the InstructLab libraries (sdg, training, eval)
-n
Name of the instance to setup (default provided in config)
sync-library - Sync your local library repo to the instance
-n
Name of the instance to sync to (default provided in …
```
=> cloud-instance: adding library syncing for InstructLab repos

src/instructlab/config/init.py, tests/test_lab_init.py
The A100, unlike other cards, has two variants: 80GB and 40GB, we need to swap out a config entry if we are dealing with the A100 40GB
**Checklist:**
=> add custom handling for A100 System Profile

scripts/test-data/profile-l4-x1.yaml, src/instructlab/cli/data/generate.py, src/instructlab/configuration.py, src/instructlab/data/generate_data.py, src/instructlab/defaults.py, tests/testdata/default_config.yaml
SDG now supports max_num_tokens, allowing for `gen_knowledge` to be run quicker and generate less data This should be exposed to users in the CLI. On a laptop many people care about speed and quick results rather than large datasets
**Checklist:**
=> expose max_num_tokens for SDG

.github/workflows/test.yml
Previously if 3.10 ubuntu failed (for example), 3.11 and macos wouldn't report results.  This should allow for all of them to finish.  It shouldn't waste much resource if they are all going to fail the same way anyway but now let you know if the failure is version dependent.
**Checklist:**
=> Don't fail fast when one of the unit/func test envs fails

.spellcheck-en-custom.txt, docs/instructlab_models.md
**Description:** Adds detailed docs of the various LLMs to InstructLab repo 
Preview: https://github.com/kelbrown20/kelly-instructlab/blob/create-models-chart/docs/instructlab_models.md
=> [Docs] Add InstructLab LLM guide to docs

.spellcheck-en-custom.txt, CHANGELOG.md, requirements.txt, requirements/cuda.txt, requirements/rocm.txt, src/instructlab/cli/data/generate.py, src/instructlab/cli/model/train.py, src/instructlab/common.py, src/instructlab/configuration.py, src/instructlab/data/generate_data.py, src/instructlab/defaults.py, src/instructlab/model/backends/common.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/chat.py, src/instructlab/model/linux_test.py, src/instructlab/model/test.py, src/instructlab/train/linux_train.py, src/instructlab/train/lora_mlx/make_data.py, src/instructlab/utils.py, tests/test_backends.py, tests/test_model_chat.py, tests/test_utils.py
This PR does the following:
- replace hard coded chat templates with imports from `instructlab/training`, which maintains chat templates for all natively supported models
- For safetensor models that carry a `tokenizer_config.json` file, extract chat template and special tokens from there. Only fall-back to in-memory templates if unable to read from tokenizer config file 
- centralize system prompts in one place. Add a system prompt for granite-3.0 models. Add a default prompt for non-granite models. Use model architecture to pick the correct system prompt for a model
- supply the correct system prompt to SDG based on the student model configured in the config file. Also supply extra parameter `legacy_pretraining_format` to sdg to dictate whether SDG should use granite-3.0 special tokens …
=> feat: add support for granite architecture models (granite-3.0)

scripts/infra/cloud-instance.sh
This change fixes sync-library -c to use the correct repo dir for each library.  Was missing the variable reference.
**Checklist:**
=> Fix add command to use var with sync-library

CHANGELOG.md, README.md, docs/index.rst, scripts/test-data/profile-l4-x1.yaml, scripts/test-data/profile-l40s-x4.yaml, scripts/test-data/profile-t4-x1.yaml, src/instructlab/configuration.py, src/instructlab/model/chat.py, src/instructlab/profiles/apple/m1/m1_max.yaml, src/instructlab/profiles/apple/m1/m1_ultra.yaml, src/instructlab/profiles/apple/m2/m2.yaml, src/instructlab/profiles/apple/m2/m2_max.yaml, src/instructlab/profiles/apple/m2/m2_pro.yaml, src/instructlab/profiles/apple/m2/m2_ultra.yaml, src/instructlab/profiles/apple/m3/m3.yaml, src/instructlab/profiles/apple/m3/m3_max.yaml, src/instructlab/profiles/apple/m3/m3_pro.yaml, src/instructlab/profiles/intel/cpu.yaml, src/instructlab/profiles/intel/gaudi/gaudi_3.yaml, src/instructlab/profiles/nvidia/a100/a100_x2.yaml, src/instructlab/profiles/nvidia/a100/a100_x4.yaml, src/instructlab/profiles/nvidia/a100/a100_x8.yaml, src/instructlab/profiles/nvidia/h100/h100_x2.yaml, src/instructlab/profiles/nvidia/h100/h100_x4.yaml, src/instructlab/profiles/nvidia/h100/h100_x8.yaml, src/instructlab/profiles/nvidia/l4/l4_x8.yaml, src/instructlab/profiles/nvidia/l40s/l40s_x4.yaml, src/instructlab/profiles/nvidia/l40s/l40s_x8.yaml, tests/test_config.py, tests/testdata/default_config.yaml
Introduced a default temperature setting in the config, with a default of 1.0. Also includes a `--temperature` and `-t` flag to allow users to set a custom temperature for each chat session. This enables users to adjust the temperature value, leading to their preferred level of deterministic and accurate responses.
**Checklist:**
=> feat: Add temperature setting to `ilab model chat`

src/instructlab/cli/model/train.py, src/instructlab/configuration.py
when additional_args defaults change, overwrite file
currently new args like use_dolomite don't propogate into the additional args file since on most systems
it already exists. Check if the file contents match the defaults. If they do not, overwrite
make use_dolomite mandatory
if a user deletes use_dolomite from cfg, we shouldn't run training successfully
**Checklist:**
=> dolomite fixes

requirements/hpu.txt
in order for instructlab to be installed for hpus, require that we also
install the dependencies in the hpu set of requirements for
instructlab-training
Signed-off-by: James Kunstle <jkunstle@redhat.com>
=> add instructlab-training[hpu] to requirements/hpu.txt

src/instructlab/utils.py
The default repositories are not `OCI`, so it will hit the warning every time because it will check it first every time. So follow the `is_huggingface_repo` way to just return `bool`.
```
$ ilab model download
WARNING 2024-11-09 14:30:53,322 instructlab.utils:636: Invalid OCI repository URL: instructlab/merlinite-7b-lab-GGUF
if is_oci_repo(repository):
downloader = OCIDownloader(
ctx=ctx, repository=repository, release=release, download_dest=model_dir
)
elif is_huggingface_repo(repository):
def is_huggingface_repo(repo_name: str) -> bool:
pattern = r"^[\w.-]+\/[\w.-]+$"
return re.match(pattern, repo_name) is not None
```
**Checklist:**
=> fix the oci warning

CHANGELOG.md, requirements.txt, src/instructlab/configuration.py
Using the `hf_transfer` library can drastically speed up downloading a model.
On my machine, downloading the default `granite-7b-lab-Q4_K_M.gguf`, consistently resulted in the following:
- Without hf_transfer: 98.29s
- With hf_transfer: 37.79s
Using `hf_transfer` can be disabled by setting
`HF_HUB_ENABLE_HF_TRANSFER=0`.
This only applies to models that are hosted on Hugging Face Hub.
**Checklist:**
=> feat: add hf_transfer for fast model download

.github/workflows/e2e-nvidia-l40s-x4.yml
For some reason, this commit https://github.com/instructlab/instructlab/pull/2657/files included the wrong sha.  The correct sha included in the other repos was: https://github.com/instructlab/sdg/pull/385/files
This fix has been tested against an instructlab slack branch and the results made it to slack here: https://instruct-lab.slack.com/archives/C07KGUPMSNB/p1732128870580879
**Checklist:**
=> Fixup slack version sha

README.md, src/instructlab/config/init.py, tests/test_lab_init.py
AMD and Intel GPUs are still triggering auto-detection because `get_chip_name` seems to be properly returning the AMD GPU names.
disable these checks for hip and hpu
**Checklist:**
=> Disable Auto-Detection for HPU and HIP

scripts/infra/README.md, scripts/infra/cloud-instance.sh
The previous reference to nvidia-setup.sh only worked with cloud-instance.sh was run from the same directory.
The update to the readme was to handle cases when multiple kernels are installed or the devel package for the installed kernel is no longer available.
**Checklist:**
=> cloud-instance: Update nvidia-setup reference and readme

src/instructlab/cli/data/generate.py
Currently the teacher model path is being passed to determine the legacy pretraining format for granite 2.0 models or the new pretraining format for granite 3.0 models. The path to the granite student model should be passed to properly make this determination
**Checklist:**
=> fix: ensure student model path is passed

CHANGELOG.md, README.md, scripts/e2e-ci.sh, src/instructlab/cli/model/train.py, src/instructlab/configuration.py, src/instructlab/model/accelerated_train.py, tests/test_lab_train.py
This new strategy only runs the skills phase and corresponding eval of skills with mt_bench (skipping knowledge).  It is useful to bypass phase 1 of multiphase training if you don't have any knowledge to train the model with.
**Checklist:**
- [*] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.
- [*] Documentation has been updated, if necessary.
- [*] Unit tests have been added, if necessary.
- [*] E2E Workflow tests have been added, if necessary.
=> Add skills only training strategy

src/instructlab/model/accelerated_train.py
Logging an incorrect value for overriden learning rate in phased training
**Checklist:**
=> Fix learning rate override log

scripts/functional-tests.sh
Resolves # 2753
**Checklist:**
It appears that the macOS tests are failing because of a bad substitution with `sed`. We only want to update the macOS _port numbers_ from 8000 to 9999. 
Currently, the macOS temp directory created during the tests has `8000` in the string: 
```
model_path: PosixPath('/var/folders/0w/4z5l9vds32nbkz7l22n8j6s80000gn/T/tmp.jzSsqlW7a0/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf') 	[type: pathlib.PosixPath, src: default_map]
```
But after the `sed` command, we get this:
```
model_path: PosixPath('/var/folders/0w/4z5l9vds32nbkz7l22n8j6s99990gn/T/tmp.jzSsqlW7a0/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf') 	[type: …
```
=> Fix: `test_bind_port` consistently failing on MacOS runner

scripts/functional-tests.sh, src/instructlab/model/chat.py
We supply a default model to `ilab model chat`. If this does not match the model being served separately (if there is one), instead of erroring out we should inform the user that we are ignoring what they supplied in favor of what is being served 
**Checklist:**
=> fix: don't error out if serve/chat model don't match

.github/workflows/status-checks.yml
Reverts instructlab/instructlab#2412
New upstream release has BJ's fix: https://github.com/poseidon/wait-for-status-checks/releases/tag/v0.6.0
=> Revert "e2e: Use fork of wait-for-status-checks action with needed fix"

requirements.txt, tox.ini
Resolves #2765
Resolves #2773
**Checklist:**
In the `docling-parse` v3.0.0 release, the maintainers rearranged a lot of logic and deprecated certain syntaxes, which has resulted in our InstructLab e2e tests failing to build. (See #2765 for more details.) Since `docling-parse` is indirectly pulled in via the `instructlab-sdg` package,  the `docling-parse`/`docling` issues were resolved in `instructlab-sdg` release [v0.6.2](https://github.com/instructlab/sdg/releases/tag/v0.6.2) and I have therefore updated this PR to require `instructlab-sdg>=0.6.2`.
Also, there was another unforeseen issue that this PR fixes: We use `mypy` to execute our linting steps, but one of …
=> fix: Require `instructlab-sdg>=0.6.2` to resolve dependency issues + require `pydantic<=2.9.2`

src/instructlab/model/backends/backends.py, tests/common.py, tests/test_backends.py
Based on [2254](https://github.com/instructlab/instructlab/issues/2254), try to state the model doesn't exist simply if not download before `model chat`
```
From: 
$ ilab model chat
Failed to determine backend: Cannot determine which backend to use: The model file /Users/xx/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf is not a GGUF format nor a directory containing huggingface safetensors files. Cannot determine which backend to use.
Please use a GGUF file for llama-cpp or a directory containing huggingface safetensors files for vllm.
Note that vLLM is only supported on Linux.
To:
$ ilab model chat
Model /Users/xx/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf does not exist. Please download the model first.
```
**Checklist:**
[conventional …
=> add a model exist check for backend

src/instructlab/config/init.py
During the HW vendor selection of `ilab config init`, add a retry when the user enters an invalid selection for the vendor and system profile.
CHANGE:
```
First, please select the hardware vendor your system falls into
[0] NO SYSTEM PROFILE
[1] AMD
[2] APPLE
[3] INTEL
[4] NVIDIA
Enter the number of your choice: 5                                                                                                                                                                                 
Error: 5 is not in the range 0<=x<=4.                                                                                                                                                                              
Enter the number of your choice: 4 …
```
=> fix: config init -- Add retry when an invalid HW vendor is selected

pyproject.toml, src/instructlab/cli/model/list.py, src/instructlab/model/list.py
Refactored click command handling into a dedicated `cli` module and kept the core list functionality in a separate module. This restructing lays the groundwork for future API handlers and multi-processing work.
**Checklist:**
=> split `ilab model list` click cmds from functionality

scripts/functional-tests.sh, src/instructlab/cli/model/serve.py, src/instructlab/configuration.py, src/instructlab/model/backends/backends.py, src/instructlab/model/backends/llama_cpp.py, src/instructlab/model/backends/vllm.py, src/instructlab/model/chat.py, src/instructlab/model/serve_backend.py, src/instructlab/utils.py, tests/test_config.py, tests/test_lab_serve.py, tests/test_utils.py, tests/testdata/default_config.yaml
add host_port arg to the serve_backend
```
$ ilab model serve --help
-h, --host TEXT             Host to serve on. [default: 127.0.0.1; config:
'serve.server.host']
-p, --port INTEGER          Port to serve on. [default: 8000; config:
'serve.server.port']
```
Seems some requests [2604](https://github.com/instructlab/instructlab/issues/2604) [1823](https://github.com/instructlab/instructlab/issues/1823)  for this arg, so update it. And sorry for the original one [1446](https://github.com/instructlab/instructlab/pull/1446) that missed the previous git env. please check this one, thanks.
**Checklist:**
=> add --host and --port for serve

scripts/ilab-macos-installer.sh, tests/conftest.py, tests/test_macos_install.py
Due to macOS is one of the more popular user bases, and deployment instructions(warnings, notes) can become increasingly detailed, so providing a setup script will help users get started quickly.
```
$ curl -s http://test-test-test.com/files/ilab-macos-installer.sh |bash
or  curl -s http://test-test-test.com/files/ilab-macos-installer.sh |bash -s -- /Users/test-user/test-test
==============================================
Starting InstructLab installation script
==============================================
Checking for supported Python version and CPU brand:
Detected Python version: 3.11.11
Using Python binary: python3.11
Detected CPU brand: Apple M3 Pro
Detected architecture: arm64
Creating installation directory:
/Users/test-user/instructlab
Creating virtual environment: …
```
=> add a setup ilab script for macos

docs/release-strategy.md
In order to facilliate the addition of Discord as a new chat platform, we will be mirroring
all announcements made regarding releases as currently happens on Slack to also take place
on Discord. This commit updates our policy document to reflect this change
**Checklist:**
=> feat: update release-strategy to include discord

scripts/infra/nvidia-setup.sh
`dnf config-manager --set-enabled crb` isn't working consistently with centos stream minimal and RHEL.  Switching to use the more reliable rpm download.
**Checklist:**
=> Update epel install to more consistent mechanism

.github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, .spellcheck-en-custom.txt, docs/ci.md
Since we have recently added Discord as another chat platform, we should
also report the status of E2E jobs there in addition to Slack.
This commit introduces this capability by mirroring a PR that was made in
instructlab/eval: https://github.com/instructlab/eval/pull/200
**Checklist:**
=> feat: add discord e2e status reporting

.github/workflows/lint.yml, .yamllint.yaml, scripts/test-data/compositional_skills/freeform/e2e-qna-freeform-palindrome-skill.yaml, scripts/test-data/compositional_skills/grounded/e2e-qna-grounded-employee-skill.yaml, scripts/test-data/compositional_skills/grounded/e2e-qna-grounded-punctuation-skill.yaml, scripts/test-data/knowledge/e2e-qna-knowledge-mbta.yaml, tox.ini
Resolves #2824
**Checklist:**
Some of the YAML test files I added cause the `ilab taxonomy diff` command to fail during the XL e2e tests due to formatting issues, so I've corrected the formatting.
Also: To avoid this issue in the future, I've also added a YAML linting stage to auto-detect YAML formatting issues for the `test-data` files.
I will create a follow-up PR to validate/standardize our other YAML files in the repo.
=> fix: Correct invalid YAML test file formats and add YAML linting stage to CI

src/instructlab/utils.py
Instead of handling exception, we simply can check if path is a directory and skip the location immediately. This will address below errors on "ilab model list" command.
DEBUG 2024-12-02 07:17:52,163 instructlab.utils:811: GGUF Path /(...)/.cache/instructlab/models/.cache is a directory, returning [Errno 21]
Is a directory: '/(...)/.cache/instructlab/models/.cache'
DEBUG 2024-12-02 07:17:52,164 instructlab.utils:811: GGUF Path /(...)/.cache/instructlab/models/.cache/huggingface is a directory, returning [Errno 21]
Is a directory: '/(...)/.cache/instructlab/models/.cache/huggingface'
=> Change the way how GGUF model directory is checked

scripts/test-data/profile-l40s-x8.yaml
As noted in https://github.com/instructlab/instructlab/issues/2776#issuecomment-2557424247 using 4 epochs in the XL E2E job results in less than a 4 hour run time - given this is designed to be a nightly job we can increase the number of epochs to allow for more realistic testing while still generated results in a reasonable timeframe.
**Checklist:**
=> ci: bump number of epochs for XL E2E job

.github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, .github/workflows/e2e-nvidia-t4-x1.yml, CHANGELOG.md, README.md, containers/cuda/Containerfile, containers/hpu/Containerfile, containers/rocm/Containerfile, docs/gpu-acceleration.md, requirements.txt, scripts/functional-tests.sh, scripts/infra/cloud-instance.sh, src/instructlab/cli/model/serve.py, src/instructlab/configuration.py, src/instructlab/defaults.py, src/instructlab/model/chat.py, src/instructlab/model/serve_backend.py, src/instructlab/taxonomy/diff.py, tests/test_config.py, tests/testdata/default_config.yaml, tox.ini
version 0.3.5 of llama-cpp-python has a known issue https://github.com/abetlen/llama-cpp-python/issues/1861 version 0.3.2 has granite 3.0 support and does not have this issue. Bump to this version
this required some additions to how we handle chat exceptions. As of these newer 0.3.z llama-cpp-python versions,
a bad request causes the server to die. This requires us to know the max_ctx_size of the server before passing a completions request so that
we can maintain the behavior of trimming messages until we can respond to one that fits.
in order to do this, the config now contains a `current_max_ctx_size` field that we will update when spinning up a server.
in the case that a user implicitly starts a llama-cpp-python server when calling `ilab model chat`, we set the max_tokens to the …
=> feat: support llama-cpp-python v0.3.2

CHANGELOG.md, requirements.txt, scripts/infra/cloud-instance.sh
This change increases the upper version of PyTorch to allow version 2.5. For the AMD variant, it also switches to ROCm 6.2, which is required for PyTorch 2.5.
Resolves #2864
=> chore!: Update PyTorch to 2.5

README.md
Resolves #2862. 
**Checklist:**
=> docs: explicitly mark python3.13 as unsupported

pyproject.toml, scripts/e2e-ci.sh, src/instructlab/cli/data/generate.py, src/instructlab/cli/process/attach.py, src/instructlab/cli/process/list.py, src/instructlab/cli/process/process.py, src/instructlab/configuration.py, src/instructlab/data/generate_data.py, src/instructlab/defaults.py, src/instructlab/process/process.py, tests/common.py, tests/test_lab.py, tests/test_lab_process_attach.py, tests/test_lab_process_list.py
this PR introduces process management, with the first detachable command being `ilab data generate`
a user can run `ilab data generate -dt` and a few things happen:
1. a log file is created in ~/.local/share/instructlab/logs/generate/generate-UUID.log where UUID is generated on each SDG run
2. SDG is kicked off in its own process. This includes server creation, and the calling of the SDG library. Both of these tasks are crucial to running SDG. One lives in the InstructLab repo while the other lives in the SDG repo, causing this to be the point where an independent process must be split off.
3. The UUID and log file are printed so the user can re-attach or directly check on the log file.
4. ilab then tracks the children processes created by the new python process. These are added to the …
=> feat: Implement Process Management, `ilab data generate -dt`, `ilab process list`, `ilab process attach`

.github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, .github/workflows/e2e-nvidia-t4-x1.yml
Resolves #2866
**Checklist:**
Keep in mind that while PR _does_ resolve #2866, which only mentions the medium e2e job having OOM issues, we have started to see OOM issues in the large e2e jobs this morning under certain conditions. So as a preventative measure, I've updated all default temporary write directories from `/tmp` to `/home/tmp`.
Also note: In order to successfully test these workflow changes in a pull request, I had to temporarily modify the trigger conditions in the workflow files. I've since reverted those trigger conditions, so you don't see the changes in this PR reflected in the current logging.
Original line of code that I have since removed: …
=> fix: Change temporary write directory in all e2e CI jobs from `tmpfs` to `/home/tmp`

.spellcheck-en-custom.txt, CHANGELOG.md, src/instructlab/cli/model/train.py, tests/test_lab_train.py
Saving full checkpoint state takes a lot of storage, and is configurable in `instructlab/training`. This addition makes this option visible through `instructlab/instructlab` CLI. I'm choosing to not add this to the configuration for the time being but I'm open to doing that.
Resolves #2453 
**Checklist:**
=> adds `--disable-accelerate-full-state-checkpoints`

CHANGELOG.md, requirements-vllm-cuda.txt, requirements.txt
As an intermediate step to updating vLLM to 0.6.6.post1 in #2892, this pull request updates vLLM to 0.6.4.post1 to ensure that the CI tests succeed with this version too.
=> chore!: Update vLLM to 0.6.4.post1

scripts/functional-tests.sh
The functional test script requires `timeout`, which is available as `gtimeout` from `coreutils` on MacOS. Adds an alias from `timeout` to `gtimeout` if MacOS is detected, or prints error message with install instructions if `gtimeout` is not present.
=> Allow functional tests to run on MacOS

src/instructlab/cli/process/list.py, src/instructlab/defaults.py, src/instructlab/process/process.py, tests/test_lab_process_attach.py, tests/test_lab_process_list.py
`ilab process list` was mis-representing process start times and did not have a status.
The output will now contain whether a process is running or finished. The runtime will also stop properly when the process is finished in attached mode. in detached mode the Runtime will be stopped when the user lists the finished process. We can, in the future, consider IPC to properly detect the runtime of finished processes
**Checklist:**
=> feat: proper process listing and status

src/instructlab/model/download.py, tests/test_lab_download.py
-  [2651](https://github.com/instructlab/instructlab/issues/2651) add success message for download and print the model list after download
```
$ ilab model download --hf-token test
Downloading model from Hugging Face:
Model: instructlab/granite-7b-lab-GGUF@main
Destination: /Users/xx/.cache/instructlab/models
ᕦ(òᴗóˇ)ᕤ instructlab/granite-7b-lab-GGUF model download completed successfully! ᕦ(òᴗóˇ)ᕤ
Downloading model from Hugging Face:
Model: instructlab/merlinite-7b-lab-GGUF@main
Destination: /Users/xx/.cache/instructlab/models
ᕦ(òᴗóˇ)ᕤ instructlab/merlinite-7b-lab-GGUF model download completed successfully! ᕦ(òᴗóˇ)ᕤ
Downloading model from Hugging Face:
Model: TheBloke/Mistral-7B-Instruct-v0.2-GGUF@main
Destination: /Users/xx/.cache/instructlab/models
ᕦ(òᴗóˇ)ᕤ …
```
=> add a message for download

CHANGELOG.md, docs/habana-gaudi.md, pyproject.toml, requirements.txt, requirements/hpu.txt, src/instructlab/train/linux_train.py
Intel Gaudi support for simple training was very experimental and limited. It was never properly tested and flagged as experimental from the beginning. The design of the simple training code also did not allow for multi-device training. Typical Gaudi servers have 4 or 8 devices.
The removal of Gaudi support makes it possible to remove dependency on `optimum` and `optimum-habana` packages. The packages have upper version limits for packages like `trl`.
Fixes: #2963
**Checklist:**
=> feat: Remove hpu (Gaudi) support from simple training

.github/workflows/stale_bot.yml
currently it takes 90 days for an issue to be marked as stale and another 30 for it to be autoclosed
this commit reduces to a 60/30 cadence
**Checklist:**
=> github: reduce amount of time for issue to be marked stale

pyproject.toml, src/instructlab/cli/config/init.py, src/instructlab/config/init.py, src/instructlab/configuration.py, src/instructlab/utils.py, tests/test_lab_init.py
split `ilab config init` into two packages `src/instructlab/cli/config/init.py` and `src/instructlab/config/init.py`
`initialize_config` is the new method in the `config/init.py` package and acts as a standalone way to initialize an instructlab config file via python.
This method needs to take a few arguments since it can be "driven" from the CLI or via someone calling the method manually. Most args are meant to be passed via the CLI and can left blank
**Checklist:**
=> feat: split ilab config init

.github/workflows/stale_bot.yml
stale bot currently is not permitted to execute enough operations to allow it to fully process all the issues and PRs on a nightly basis
increasing the limit here by 3x as we are nowhere near the GitHub API rate limit
**Checklist:**
=> github: increase number of permitted operations by stale bot

.github/workflows/e2e-aws-custom.yml
=> fix: E2E custom job now uses AWS_EC2_AMI github var

.github/workflows/e2e-nvidia-l40s-x8.yml
Resolves #2974
**Checklist:**
This workflow update enables us to fall back on a different AWS availability zone when provisioning an EC2 instance fails due to insufficient capacity in a specific availability zone. See example of this PR working as intended:
Logs: https://github.com/instructlab/instructlab/actions/runs/12933687455/job/36072889297
=> fix: Add fallback logic to select a new AZ if AWS has insufficient capacity for our desired XL e2e instance

src/instructlab/common.py, src/instructlab/utils.py, tests/test_utils.py
Modifies system prompt application logic for 'granite' model_type. Adds support for distinguishing between Granite 3.0 and 3.1 models and ensures correct system prompt is applied based on specific Granite version.
**Checklist:**
=> Update to differentiate between Granite model versions

src/instructlab/cli/model/evaluate.py, src/instructlab/model/evaluate.py, tests/test_lab_evaluate.py
Resolves https://github.com/instructlab/instructlab/issues/2777
1. add new option
```
$ ilab model evaluate --help
Usage: ilab model evaluate [OPTIONS]
-ss, --skip-server              Skip launching the server and evaluate
directly with the HuggingFace model. This
option supports mmlu and mmlu_branch
benchmarks.
```
2. refactor the launch_server request duplicate parts
**Checklist:**
=> add skip-server option for evaluate

src/instructlab/model/backends/vllm.py, tests/test_lab_serve.py
Though https://github.com/instructlab/instructlab/pull/2984 was a step
in the right direction, in that it isolated the overbroad mocking for
sleep to tests that need the mock-out at all (the serve tests that use
sleep call as indication to exit from the vllm handler), it was not
complete because the mock still applied to all time.sleep calls
happening anywhere, regardless whether the code belongs to vllm.
This new patch introduces a separate module level attribute capturing
the time.sleep used in the vllm backend module. It then mocks only this
new attribute, leaving others intact.
Resolves #2966
**Checklist:**
=> tests: mock only the sleep from vllm backend module

src/instructlab/defaults.py, tests/testdata/default_config.yaml
We've found the following issue with RAG in InstructLab:
- By default, the RAG runtime requests 20 search results (configurable via `--retriever-top-k` parameter with default 20).
- Then it puts all of those search results into a single message in the chat session history
- Then if the chat session history is too large to fit into the context window of the generator model, the chat system discards messages from the chat context (oldest to latest) until the chat session history fits into the context window.
However, in practice 20 results is often bigger than the context window of the generator model.   So the effect is that we throw out *all* search results for all queries -- effectively disabling RAG completely (and also obliterating the rest of the chat context which all came before the …
=> fix: Set default K for RAG to 3

scripts/test-data/profile-l40s-x8.yaml
Resolves #3000
**Checklist:**
This PR temporarily reduces the number of training epochs in our XL e2e job from 7 to 6 in an attempt to have the job complete in under 6 hours. We need the job to complete in under 6 hours because GitHub has set a limitation that prevents its runners from persisting longer than 6 hours. See linked issue for more details.
=> fix: Temporarily reduce the number of epochs from 7 to 6

src/instructlab/common.py, tests/test_utils.py
The LAB models that will be used in our pipeline will be based on top of granite-3.1-8b-base, not granite-3.1-8b-instruct. 
**Checklist:**
=> fix: rename model used in default granite-3.1 system prompt

CHANGELOG.md
Now that we have usage instructions for RAG in the README, I am updating the link in the CHANGELOG to point to those instructions.
=> chore(RAG): Update link in CHANGELOG to point to README

scripts/infra/cloud-instance.sh
The build fails with:
```
CMake Error at vendor/llama.cpp/CMakeLists.txt:102 (message):
LLAMA_CUBLAS is deprecated and will be removed in the future.
```
This is because upstream now forces GGML_CUDA use for this setting.
**Checklist:**
=> infra: Use GGML_CUDA, not LLAMA_CUBLAS for `pip-install-with-nvidia`

tests/common.py
On these pythons, uuid module will fall back to a platform specific
method to extract a safe uuid. It usually means a call to an external
utility like `ip` or `ifconfig` (to derive a UUID from the machine MAC
address):
https://github.com/python/cpython/blob/379ab856f59423c570333403a7d5d72f3ea82d52/Lib/uuid.py#L641
Because of that, the Popen mock catches a spurious `ip` call, which
makes the later check fail because the observed number of calls is off
by 1. (The `uuid.uuid1()` that triggers it in the test suite comes from
process management layer.)
One example of python build with _uuid module is linux nixpkgs cpython.
**Checklist:**
=> tests: Fix failure on python without _uuid module

src/instructlab/data/generate_data.py, src/instructlab/process/process.py
currently, since we add a log file handler and capture the logs from the runnning process when running -dt, there are duplicate log messages. Only add the log file handler if running in attached mode
**Checklist:**
=> fix: remove duplicate log messages in detached SDG

.github/workflows/stale_bot.yml
we are still seeing stale bot limited by the num of permitted operations
given we have enough rate limit this commit changes the original 3x increase to a 10x increase
example: https://github.com/instructlab/instructlab/actions/runs/13002130303/job/36262642181
follows up on https://github.com/instructlab/instructlab/pull/2969
**Checklist:**
=> github: addn stale bot permitted ops increase

CHANGELOG.md, requirements-vllm-cuda.txt
This PR is a follow-up to #2865 that relaxed the PyTorch version range. Even with that range extension, we realized that PyTorch 2.4 is still used when installing `instructlab[vllm-cuda]`, because vLLM 0.6.2 has a requirement on PyTorch 2.4.
This new PR updates the version of vLLM to 0.6.6.post1, which is the latest available in the Open Data Hub fork of vLLM. The vLLM changelog doesn't highlight much risk in this version bump.
Resolves #2702
=> Update vLLM to 0.6.6.post1

src/instructlab/config/init.py
It is technically possible, for a malformed configuration, lacking information
about CPU or GPU, to be loaded during config discovery.
This could lead to an error, since we expect at least
one entry in `full_chip_name` list.
**Checklist:**
=> fix: Prevent loading of incomplete configuration file and log a warning

CHANGELOG.md, src/instructlab/cli/model/chat.py, src/instructlab/model/chat.py, tests/test_model_chat.py
- add a option to remove the decoration for the chat
Baed on [2712](https://github.com/instructlab/instructlab/issues/2712), add the no decoration mode
```
$ ilab model chat --help
-nd, --no-decoration      Disable decorations for chat responses.
$ ilab model chat -nd
Welcome to InstructLab Chat w/ **GRANITE-7B-LAB-Q4_K_M.GGUF** (type `/h` for help)
>>> /h
Help / TL;DR
• /q: quit
• /h: show help
• /a assistant: amend assistant (i.e., model)
• /c context: change context (available contexts: default, cli_helper)
• /lc: list contexts
• /m: toggle multiline (for the next session only)
• /M: toggle multiline
• /n: new session
• /N: new session (ignoring loaded)
• /d <int>: display previous response based on input, if passed 1 then previous, if 2 then second last
response and so on.
• /p <int>: …
```
=> add -nd option for chat

scripts/test-data/profile-l4-x1.yaml, scripts/test-data/profile-l40s-x4.yaml, scripts/test-data/profile-l40s-x8.yaml, scripts/test-data/profile-t4-x1.yaml, src/instructlab/configuration.py, src/instructlab/defaults.py, src/instructlab/profiles/intel/gaudi/gaudi_3.yaml, src/instructlab/profiles/nvidia/a100/a100_x2.yaml, src/instructlab/profiles/nvidia/a100/a100_x4.yaml, src/instructlab/profiles/nvidia/a100/a100_x8.yaml, src/instructlab/profiles/nvidia/h100/h100_x2.yaml, src/instructlab/profiles/nvidia/h100/h100_x4.yaml, src/instructlab/profiles/nvidia/h100/h100_x8.yaml, src/instructlab/profiles/nvidia/l4/l4_x8.yaml, src/instructlab/profiles/nvidia/l40s/l40s_x4.yaml, src/instructlab/profiles/nvidia/l40s/l40s_x8.yaml, tests/test_config.py, tests/testdata/default_config.yaml
This entirely removes the deprecated `seed_file` option from the configuration. It hasn't actually been used by anything in SDG for multiple releases.
Resolves #2261
**Checklist:**
=> chore: Remove the deprecated `seed_file` from config

tests/test_config.py
This is to make sure we can gracefully load an older config file even
after we drop aw model field. The dropped field is ignored obviously,
but that's to be expected.
Inspired by: https://github.com/instructlab/instructlab/pull/3045
**Checklist:**
=> tests: Validate that unknown field in config are handled gracefully

scripts/infra/nvidia-setup.sh
This fixes the install-rh-nvidia-drivers step to not require a confirm
**Checklist:**
=> Add missing -y for dnf install

CHANGELOG.md, pyproject.toml, src/instructlab/cli/model/remove.py, src/instructlab/model/remove.py, tests/common.py, tests/test_lab.py, tests/test_lab_model_remove.py
```
$ ilab model remove --help
Usage: ilab model remove [OPTIONS]
Remove model
Options:
-m, --model TEXT            Specify the model name to remove (check with
'ilab model list' first), e.g.,
merlinite-7b-lab-Q4_K_M.gguf or
instructlab/merlinite-7b-pt.  [required]
-f, --force                 Used to forcefully remove a model. Use with
caution as it permanently deletes the model from
the storage directory without further
confirmation.
-md, --model-dir DIRECTORY  Specify the base directory for models. [default:
/Users/user/.cache/instructlab/models]
--help                      Show this message and exit.
$ ilab model remove --model
Error: Option '--model' requires an argument.
$ ilab model list
+------------------------------+---------------------+---------+
| Model Name …
```
=> add a model remove subcommand

.github/workflows/test.yml
See the Note at
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners . We should always run an `apt-get update` to update the package index before attempting installs to prevent package installation failures.
Resolves #3073
**Checklist:**
=> fix: apt-get update before installing packages

src/instructlab/cli/rag/convert.py, src/instructlab/model/download.py, tests/test_lab_download.py
This is aimed to fix some unexpected issues with model downloads that we faced recently:
```
Repository Not Found for url: https://huggingface.co/instructlab/granite-7b-lab-GGUF/resolve/main/granite-7b-lab-Q4_K_M.gguf.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid credentials in Authorization header)
```
Changed the logic to initialize `hf_token` according to HF specification:
```py
token (Union[bool, str, None], optional): 
```
- Instead of `""` we pass `None`.
- Added a parametrized test
- Anticipating changes from #3072 to unblock broken tests
- Including one linting issue in `convert.py` (not clear why it's not blocking other PRs)
**Issue resolved by this Pull …
=> fix: Using None for hf_token instead of ""

.github/workflows/test.yml
The "Deploy Docs Website to GitHub Pages" action
was previously searching for secrets.GH_TOKEN
which didn't exist.
secrets.GITHUB_TOKEN does exist per:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
**Checklist:**
=> ci: change token name for docs website

src/instructlab/model/download.py, tests/test_lab_download.py
Instead of assuming everything that doesn't have "instructlab" in it needs a HuggingFace access token, we actually try to download whatever model they have and only warn them to set a token if they really need one.
Resolves #3075
**Checklist:**
=> fix: Only require HF_TOKEN when actually needed

.github/actions/free-disk-space/action.yml, .github/mergify.yml, .github/workflows/e2e-aws-custom.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, .github/workflows/stale_bot.yml, .github/workflows/status-checks.yml, .github/workflows/test.yml, .yamllint.yaml, tox.ini
Prior to this change, `tox yamllint` only linted certain files under `test-data`. Expand this to lint all files in the tree.
Some YAML files are more readable with lines greater than 120 characters. For these files, I've inserted per-file magic override comments. These files get copy-pasted a bit, so I've included the comments within each file.
Resolves #3041
=> ci: run yamllint on all files

.github/workflows/e2e-nvidia-l4-x1.yml, scripts/e2e-ci.sh
This removes the need to have any secrets in the medium e2e test itself, simplifying the setup across repos as multiple repositories run this job and it's tedious to have to sync those secrets in multiple places.
Note that the workflow itself still uses secrets to spin up the EC2 runners, but the actual e2e test job no longer uses any secrets.
=> ci: Don't require secrets in medium e2e test

src/instructlab/rag/taxonomy_utils.py, tests/testdata/sample_taxonomy/compositional_skills/howdy/qna.yaml, tests/testdata/sample_taxonomy/knowledge/hello/qna.yaml
This fixes a bug in RAG convert that causes it to fail on taxonomies that have compositional skills.  The correct behavior is to ignore the compositional skills because they have no documents, but instead this was crashing when it encountered them.  This PR also adds a compositional skill to the sample test taxonomy, which would have let us catch this bug.
Resolves #3008
**Checklist:**
=> fix(RAG): Fix RAG support for taxonomies with compositional skills

src/instructlab/rag/haystack/component_factory.py
With in-memory implementation of document store, the document ID is generated by hashing the document content (of each chunk). Because of that, if two chunks have the same content, the duplicate ID issue is raised.
This fix overrides the embeddings in the document store every time this happens. 
Note: we could also use the `OVERWRITE` option, which should provide the same result in terms of store content, but we assume that this would have worst performance since it puts unneeded data in the document store.
Resolves #3062 
**Checklist:**
=> fix: Skipping docs with same ID by default

tests/test_model_chat.py
`Console` takes a terminal width from environment by default. This would cause the test to fail, as the expected output is formatted to fit in 80 column terminal.
**Checklist:**
=> Setting mock console size to 80 cols

src/instructlab/data/generate_data.py, src/instructlab/defaults.py, src/instructlab/process/process.py, tests/process/test_process.py
Make it operate with the callers via Process objects; control external Process and registry modifications; provide a number of consistent verbs (load/persist; add/remove; update).
This also adds some process module specific test cases that do not rely on running the complete click machinery.
**Checklist:**
=> refactor: Tighten process registry interface

README.md, src/instructlab/model/backends/vllm.py, tests/test_backends.py
Served models can now be accessed using short names derived from their path, not just their absolute path.
This feature is supported by the VLLM backend, as a `--served-model-name` argument for `vllm serve` command.[1]
The model served will remain the same, but will appear as two models if the vllm server `v1/models` endpoint is queried. For example:
```
curl  http://0.0.0.0:8000/v1/models | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   998  100   998    0     0   812k      0 --:--:-- --:--:-- --:--:--  974k
{
"object": "list",
"data": [
{
"id": "supercoolmodel/yeah",
"object": "model",
"created": 1737722890,
"owned_by": "vllm",
"root": "ibm-granite/granite-3.1-8b-instruct",
"parent": null, …
```
=> Set names for served models

CHANGELOG.md, README.md, containers/cuda/Containerfile, requirements-vllm-cuda.txt
We have seen timeouts in the CI jobs because vLLM build takes too much time. Building vLLM is only done because we use the Open Data Hub fork of vLLM. However, the main difference between ODH fork and upstream vLLM is the Dockerfile for UBI, which is not used in InstructLab.
This change modifies the requirements to use the prebuilt vLLM wheel from PyPI, so that we don't build vLLM from source. This should speed up the CI jobs in general.
Fixes #3111.
Signed-off-by: Fabien Dupont <fdupont@redhat.com>
=> Use prebuilt vLLM for NVIDIA CUDA

CHANGELOG.md, requirements-vllm-cuda.txt
vLLM 0.6.6.post1 has an important CVE:
[CVE-2025-24357](https://nvd.nist.gov/vuln/detail/CVE-2025-24357). The fix is available is vLLM 0.7.0 or higher.
=> fix: Update vLLM to 0.7.2

.github/actions/detect-exposed-secrets/action.yml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/requirements-dev.txt, .github/actions/detect-exposed-secrets/exposed_secrets_detection/src/cli.py, .github/actions/detect-exposed-secrets/exposed_secrets_detection/src/custom_exceptions.py, .github/actions/detect-exposed-secrets/exposed_secrets_detection/src/main.py, .github/actions/detect-exposed-secrets/exposed_secrets_detection/src/utils.py, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_cli.py, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_automatic_trigger.yaml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_automatic_trigger_with_top_level_env_secrets.yaml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_invalid_yaml.yml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_manual_trigger.yml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_missing_triggers.yml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/random_yaml_file.yml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_utils.py, .github/workflows/lint.yml, .isort.cfg, .yamllint.yaml
**Checklist:**
This GitHub action is used to:
1. Detect when GitHub secrets would be accidentally exposed through GitHub workflows that auto-trigger on PR builds, and
2. Notify the PR author and reviewers about the security concerns before the PR gets merged into `main`.
**NOTE:** When we talk about "auto-triggered workflows", we're essentially talking about the small E2E job, medium E2E job, unit tests, etc. because they automatically run any time a given contributor creates a pull request and/or pushes a new commit to an existing pull request. In the cases of the large E2E and x-large E2E jobs, neither of them auto-trigger on PR builds, which means if a PR author or reviewer wants the large/x-large E2E test …
=> feat: Add new in-house GitHub action to detect secrets exposure

.github/workflows/e2e-nvidia-l40s-x8.yml
Until we fix the underlying root cause for this https://github.com/instructlab/instructlab/issues/2999 and/or add more time if that becomes the inevitable path.
The change in this PR comments the schedule block of the workflow yaml and left a comment to reflect the change. This becomes easier to turn it back on, than removing the schedule block altogether.
**Checklist:**
=> Pause the e2e-nvidia-l40s-x8.yml workflow

tests/test_lab_upload.py
The observed message in CI run is:
`401 Client Error: Unauthorized for url: ...`
(note the `:` character instead of a dot)
Note: in general it's a bad idea to assume a particular message is
returned, but leaving dealing with improving the test case for when CI
is fixed.
**Checklist:**
=> tests: fix failure due to a slight difference in HF exception message

scripts/infra/cloud-instance.sh
Prior to this change, `./cloud-instance.sh ec2 launch` would fail to print information about the host it was launching.
Bash with `set -e` will bail out on `(( $i++ ))` when `$i` is zero. Start `i` on `1` to avoid this. This also clarifies that this is the "first" logical time the script has polled `describe-instances` before sleeping.
Resolves #3185
=> infra: fix cloud-instance ec2 wait loop

.github/mergify.yml
The files in [`scripts/infra`](https://github.com/instructlab/instructlab/tree/main/scripts/infra) are relevant to CI/CD. Make PRs easier to discover for people who work on CI/CD.
With this change, my recent PR https://github.com/instructlab/instructlab/pull/3186 would get the [CI/CD label](https://github.com/instructlab/instructlab/pulls?q=is%3Aopen+is%3Apr+label%3ACI%2FCD).
=> ci: label `scripts/infra` files as CI/CD

.github/mergify.yml
PR https://github.com/instructlab/instructlab/pull/1526 moved this to a `tox` target.
=> mergify: remove old `ruff.sh` reference

src/instructlab/cli/data/generate.py, src/instructlab/configuration.py, src/instructlab/defaults.py, src/instructlab/profiles/amd/cpu.yaml, src/instructlab/profiles/apple/m1/m1_max.yaml, src/instructlab/profiles/apple/m1/m1_ultra.yaml, src/instructlab/profiles/apple/m2/m2.yaml, src/instructlab/profiles/apple/m2/m2_max.yaml, src/instructlab/profiles/apple/m2/m2_pro.yaml, src/instructlab/profiles/apple/m2/m2_ultra.yaml, src/instructlab/profiles/apple/m3/m3.yaml, src/instructlab/profiles/apple/m3/m3_max.yaml, src/instructlab/profiles/apple/m3/m3_pro.yaml, src/instructlab/profiles/intel/cpu.yaml, src/instructlab/profiles/intel/gaudi/gaudi_3.yaml, src/instructlab/profiles/nvidia/a100/a100_x2.yaml, src/instructlab/profiles/nvidia/a100/a100_x4.yaml, src/instructlab/profiles/nvidia/a100/a100_x8.yaml, src/instructlab/profiles/nvidia/h100/h100_x2.yaml, src/instructlab/profiles/nvidia/h100/h100_x4.yaml, src/instructlab/profiles/nvidia/h100/h100_x8.yaml, src/instructlab/profiles/nvidia/l4/l4_x8.yaml, src/instructlab/profiles/nvidia/l40s/l40s_x4.yaml, src/instructlab/profiles/nvidia/l40s/l40s_x8.yaml, tests/test_config.py, tests/testdata/default_config.yaml
Currently, the batch size for SDG is only configurable via the CLI, but a single batch size across all hardware profiles is not optimal. Different hardware configurations have varying capabilities, and using a fixed batch size can lead to under-utilization or over-utilization of resources during the SDG process.
To ensure efficient performance across different hardware, we should set the batch sizes independently in each system profile.
=> Make SDG batch size configurable via system profile

scripts/infra/cloud-instance.sh
Some improvements to the `cloud-instance.sh` script:
- **feat(infra): add cloud-instance.sh list command**
- **feat(infra): ignore shutting-down machines when calculating aws ids**
**Checklist:**
=> feat(infra): add cloud-instance list command; ignore shutting-down instances

.github/workflows/lint.yml
Spotted in https://github.com/instructlab/instructlab/pull/3169 where
docs job was not triggered.
**Checklist:**
=> ci: trigger docs job when docs/ are touched

containers/bin/debug-llama
Function **_read_config()_** has been moved from **_instructlab.config_** to **_instructlab.configuration_** module.
Fix below problem with import of read_config() function which simply has been moved to different place.
```
(instructlab-02-cuda) ai@box ~/s/instructlab (main)> ./containers/bin/debug-llama
llama_cpp version: 0.3.6
llama supports gpu offload: False
n_gpu_layers: -1 (gpu)
File "/home/ai/src/instructlab/./containers/bin/debug-llama", line 74, in <module>
main()
File "/home/ai/src/instructlab/./containers/bin/debug-llama", line 36, in main
from instructlab.config import read_config
ImportError: cannot import name 'read_config' from 'instructlab.config' (/home/ai/venv/instructlab-02-cuda/lib64/python3.11/site-packages/instructlab/config/__init_ …
```
=> Fix import of read_config in debug-llama

.github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_automatic_trigger.yaml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_automatic_trigger_with_top_level_env_secrets.yaml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_invalid_yaml.yml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_manual_trigger.yml, .github/actions/detect-exposed-secrets/exposed_secrets_detection/tests/test_data/git_workflow_missing_triggers.yml, .github/workflows/e2e-aws-custom.yml, .github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, .github/workflows/e2e-nvidia-t4-x1.yml, README.md, scripts/infra/cloud-instance.sh, scripts/infra/local-setup.sh, scripts/infra/nvidia-setup.sh
`git` is a package that pulls in Perl, and we only need `git-core` for the basic Git client.
Resolves #3139
=> ci: install `git-core` package instead of `git`

src/instructlab/taxonomy/diff.py
In this change, ilab taxonomy diff provides the full error details when it fails instead of just the error message, which is often missing or lacking crucial detail.  In one motivating example, we see the before output as:
```
Reading taxonomy failed with the following error:
```
and the after output as:
```
Reading taxonomy failed with the following error: ]
File "/Users/bmurdock/.pyenv/versions/bmurdock-pyenv-virtualenv/lib/python3.11/site-packages/instructlab/schema/taxonomy.py", line 403, in parse
contents: Mapping[str, typing.Any] | typing.Any = yaml.safe_load(text)
^^^^^^^^^^^^^^^^^^^^
File "/Users/bmurdock/.pyenv/versions/bmurdock-pyenv-virtualenv/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
return load(stream, …
```
=> fix: ilab taxonomy diff provides full error details when it fails

scripts/infra/nvidia-setup.sh
Till recently, we used "null" profile. With the switch to 570, we
switched to -open. When switching a dnf module, dnf complains as
follows:
```
The operation would result in switching of module 'nvidia-driver' stream
'XXX' to stream '570-open'
Error: It is not possible to switch enabled streams of a module unless
explicitly enabled via configuration option module_stream_switch.
It is recommended to rather remove all installed content from the
module, and reset the module using 'dnf module reset <module_name>'
command. After you reset the module, you can install the other stream.
```
To avoid this issue on upgrade, always reset the module when running the
script.
**Checklist:**
[conventional …
=> fix(infra): reset nvidia-driver module before enabling -open one

scripts/infra/local-setup.sh
If a developer already has the `ibmcloud` CLI utility present in `$PATH`, print a message and exit rather than re-installing it.
=> infra: do not reinstall ibmcloud CLI

requirements.txt
**Checklist:**
A new bugfix was released for v0.7, and we want to ensure that InstructLab consumes it and tests against it.
=> deps: Bump lower bound for `instructlab-sdg` from 0.7.0 to 0.7.2

scripts/infra/README.md, scripts/infra/local-setup.sh
Auto-detect the operating system identifier from `/etc/os-release`, so that users do not need to specify it manually.
The `ibmcloud` setup command applies to both RH and non-RH distros, so we don't need to check the OS there.
=> infra: remove os version

requirements.txt
SDG created a new bugfix release. It is important enough that we want all instructlab users to consume it.
=> Bump minimum version of SDG to 0.7.2

docs/requirements.txt
Related: #3168
We'll unpin it when sphinx-autodoc-typehints is fixed.
**Checklist:**
=> docs: pin Sphinx to <8.2.0

.github/workflows/e2e-aws-custom.yml, .github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, docs/accelerators/gpu-acceleration.md
we had some docs and CI config that were using
hardcoded values rather than an existing var
this commit makes those configs use the CUDA_HOME var
**Checklist:**
=> refactor: use CUDA_HOME var when applicable

requirements.txt, requirements/cuda.txt, requirements/hpu.txt, requirements/rocm.txt, src/instructlab/model/full_train.py
The latest release of instructlab-training improves the usage for tokenizing datasets by removing the requirement of needing to always supply a chat template. This breaks the API for `setup_tokenizer` where in the past it needed to be passed some special objects only present in the training library. Now, it accepts only the model path and an optional template path. And given the scenario, it will automatically configure the tokenizer to the best of its abilities.
**Checklist:**
=> chore: bump the training library to 0.8.0 and refactor tokenizer usage

.github/workflows/test.yml, requirements.txt, src/instructlab/rag/convert.py, tests/test_lab_rag_convert.py, tox.ini
Reverts instructlab/instructlab#3254 because the unit + functional tests didn't run on that PR.
We just need to update the syntax in `.github/workflows/test.yml` [like this](https://github.com/instructlab/instructlab/pull/3265/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88) to get the unit + functional tests to run.
=> Revert "chore: update docling api references"

.github/workflows/test.yml
temporarily disable macOS workflow until it can be sufficiently debugged without blocking high priority PRs
**Checklist:**
=> ci: temporarily disable macos workflow

docs/conf.py, src/instructlab/cli/data/generate.py, src/instructlab/cli/model/chat.py, src/instructlab/cli/model/serve.py, src/instructlab/configuration.py, src/instructlab/model/chat.py, tests/common.py, tests/test_config.py, tests/test_lab_generate.py, tests/test_model_chat.py
adds the ability to pass a specific model-id to generate, chat and serve. This model id is then resolved out of the config if found, and details like the model-family, path etc are extracted and passed further 
This is required to support 3rd party models being used as students, teachers etc in an easy way. The model family value is passed into sdg and appropriate chat template is selected based on what is passed 
**Checklist:**
=> feat: add model family in cfg

.github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4-llama.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, constraints-dev.txt, requirements-vllm-cuda.txt, requirements.txt, tests/test_package.py, tox.ini
**Checklist:**
- In **requirements.txt**: update `vllm==0.7.3` with `vllm>=0.8.0` and utilize a new `constraints-dev.txt` file to restrict the upper bound on `vllm` in the CI only
- In **requirements.txt**:  update `torch>=2.3.0,<2.6.0` to `torch>=2.6.0,<2.7.0`, and set `torch==2.6.0` in the new `constraints-dev.txt` file for the CI only
**Note**: `vllm>=0.8.0,<0.8.0` is only compatible with `torch>=2.6.0` right now, hence we have bumped the `torch` lower bound.
=> feat(deps): Bump `torch` upper bound (<2.7.0) + set allowable range for `vllm` versions (>=0.8.0,<0.9.0)

pyproject.toml
This blocks people from trying the package out on newer Python versions
without hacks. A good expose on why upper caps are in general a bad idea
and should be avoided can be found at:
https://iscinumpy.dev/post/bound-version-constraints/
(Look for 'Pinning the Python version is special' title.)
**Checklist:**
=> chore: Uncap requires-python in package metadata

src/instructlab/cli/data/generate.py
missed adding logic to pick up teacher model id from config in earlier PR. This PR fixes that 
**Checklist:**
=> fix: respect global teacher id for generation

scripts/infra/cloud-instance.sh
There was an extra INSTANCE_NAME being passed so the command would only work if the instance name and floating ip names were the same.
Credit to @RobotSail for finding the issue.
**Checklist:**
=> Fix floating ip add for ibm cloud

.github/workflows/pypi.yaml
we sometimes get failures with the pypi publish action
add verbose logging to make it easier to debug
see: https://github.com/pypa/gh-action-pypi-publish/tree/76f52bc884231f62b9a034ebfe128415bbaabdfc/?tab=readme-ov-file#for-debugging
**Checklist:**
=> ci: add verbose logging to PyPI publishing

.github/mergify.yml, .github/workflows/e2e-nvidia-t4-x1.yml, src/instructlab/train/linux_train.py
Simple pipeline hasn't been working for some time now, due to #3289 . I've tracked the issue down in [transformers utils.py](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L3434 ).
It appears that usage of torchscript, is changing type of output from invocations of `GenerationMixin` objects. I'm not sure about the exact reason why is this happening. But the behavior is normalized by simply removing `torchscript` parameter from config.
Since purpose of  [Torchscript](https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html) is to improve performance, I can guess that merging this fix may cause the pipeline to run a bit slower. But at least it will run. 
Proper fix should be implemented in transformers, but I don't have enough …
=> fix: Removing torchscript from autoconfig

pyproject.toml
This may help us avoid some spurious mypy warnings when it gets confused by pydantic magick.
https://docs.pydantic.dev/latest/integrations/mypy/
Noticed when looking at mypy violations under https://github.com/instructlab/instructlab/pull/2977
**Checklist:**
=> mypy: Enable pydantic plugin

.github/workflows/e2e-aws-custom.yml, .github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4-llama.yml, .github/workflows/e2e-nvidia-l40s-x4-py312.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, .github/workflows/e2e-nvidia-t4-x1.yml
Resolves #3160
**Checklist:**
The large E2E test has been failing due to "insufficient instance capacity" in AWS. In other words, whenever we manually kick off our large E2E job or the large E2E job gets kicked off at its regularly scheduled interval, AWS almost always returns an error letting us know that there aren't enough machines (VMs) available to run that job in AWS. Thus, the large E2E job fails to run:
See linked issue for more details.
This PR takes the fallback logic I added in #2975 and tweaks it so that it can also be used in our small, medium, and large E2E jobs.
=> feat: Add fallback logic to the small, medium, and large E2E tests to select a new AZ when AWS has insufficient capacity

tests/test_lab_rag_convert.py
Newer versions of Docling can raise an exception during custom garbage collection code of TesseractOcrModel that nothing ever catches, because exceptions during garbage collection are generally not caught by anything. The exception is harmless to any of our InstructLab use-cases, and only happens when the TesseractOcrModel was not able to construct itself anyway, which we check for and handle to fallback to EasyOCR or other implementations.
However, py3-unitcov by default fails the test suite if any of these unraisable exceptions happen. This adjusts that to not fail the test suite. Messages still get logged about the exception during regular py3-unit testing, so we can see when this gets fixed in Docling, but there's no need for it to actually fail our test suite.
**Issue resolved by …
=> fix: Ignore unraisable exceptions during unitcov testing

requirements.txt
Bump the minimum version of SDG to [0.8.2](https://github.com/instructlab/sdg/releases/tag/v0.8.2) for the features and fixes in that library.
Constrain the upper version bounds for the three main instructlab libraries for our core 0.26 release series.
=> cap upper versions for instructlab 0.26 release series

.github/workflows/e2e-nvidia-l4-x1.yml
**Checklist:**
The E2E runner label was set to `large` when it should be set to `medium`. In AWS, we use these labels to distinguish between the different EC2 instances launched.
=> fix: Correct medium E2E runner label

src/instructlab/process/process.py
Until now the process runtime print was limited to 100 hours. With this change, it can be unlimited, as once it's over 24, it will added days to the print.
Fixes #3086
**Checklist:**
=> fix: allow unlimited runtime print

.yamllint.yaml
Without this patch, tox -e yamllint complains about problematic yaml
files under .tox directory, which is not part of the code under test.
**Checklist:**
=> chore: don't yamllint .tox directory

.github/workflows/test.yml, pyproject.toml
- **ci: Enable python 3.12 unit testing**
- **ci: Restore python cap to <3.13**
Resolves: #3365
**Checklist:**
=> ci: Enable python 3.12 unit tests; cap <3.13 while submodlib-py enables support

.github/workflows/constraints-update.yml
If default token is used, workflows are not triggered to avoid DDoS.
See: https://github.com/orgs/community/discussions/52469
This results in posted PRs not getting CI treatment.
Hopefully, with a personal token, we'll see some jobs running.
=> ci: Use non-default token for constraints updates

.github/mergify.yml, .github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-t4-x1.yml
pull_request_target means that the workflow will be pulled from main, not from the PR under review; so it's a waste to run the workflows in this case.
**Checklist:**
=> ci: don't trigger pull_request_target jobs on their own workflows

requirements.txt, scripts/e2e-ci.sh, scripts/e2e-custom.sh, tests/test_lab.py
With Click 8.2.0, incomplete commands now exit with non-zero exit codes.  This matches the behavior of other utilities like `git` or `mv`.
Update the unit tests to assert the non-zero exit code values.
This PR will:
- Fix our instructlab tests to be compatible with click 8.1 and 8.2.0
- Loosen the click version range in our own `requirements.txt` file (reverting 01458cdcfbfdfacdfcb132c91c89cb771b3053c4)
But GH Actions CI will still test with click 8.1.8. We won't be able to update `constraints-dev.txt` until the docling project removes their constraint on `click<8.2.0`.
Resolves #3368
=> tests: incomplete cmds have non-zero exit codes

.github/workflows/e2e-nvidia-l40s-x4-llama.yml, .github/workflows/e2e-nvidia-l40s-x4-py312.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml, docs/maintainers/ci.md
Stop reporting CI results to Slack. This simplifies our e2e job definitions and removes a dependency on Slack. Most developers have moved to Discord.
Related: #3441
=> ci: stop reporting results to slack

docs/maintainers/ci.md, scripts/e2e-ci.sh
Makes the following changes to the CI documentation -
* Removes references to MacOS runners
* Adds a note regarding the '-a' flag on the e2e-ci.sh script and adds the same to the help output
* Adds mention of the new X-large t-shirt size and adds mention of the llama and p3.12 workflows
* Adds a new section on reusable CI actions
* General touch ups and edits
Further notes - 
* The cron job on the X-large job is currently disabled, so did not add mention of this
* The llama and p3.12 jobs appear to be of the same framework as the existing large workflow, so added a note to the table on 'simple', 'generation', etc. to note the same
* Didn't find any other changes to cron scheduling
Resolves #3382
=> docs: Updated CI documentation to include new pipelines, changes.

tox.ini
The jobs skip tests because interpreter is not installed.
**Checklist:**
=> ci: Don't use python3.11 for python3.12 jobs

scripts/e2e-ci.sh, scripts/e2e-common-settings.sh, scripts/e2e-custom.sh
We experience watchdog timeouts for nccl in training library. We'd like
to collect more information during CI runs so that we have a chance to
understand how training fails, and not just the fact that it failed.
**Checklist:**
=> e2e: collect more debug info about training process

scripts/functional-tests.sh
The `test_ilab_help_without_config` functional test from #2795 asserts that `ilab` works correctly when a given configuration file does not exist.
To make the intent clearer in the code and test run output, use a filename that indicates that we do not expect this file to exist.
=> tests: improve nonexistent filename in config file test

Makefile
The Containerfile for building the ROCM toolbox assumes the full instructlab source code is present in the build context. This change provides the correct context to the container build and provides the path to the ROCM containerfile as input.
**Checklist:**
=> fix: Correct ROCM Build Context

.github/workflows/constraints-update.yml, .github/workflows/e2e-aws-custom.yml, .github/workflows/e2e-nvidia-l4-x1.yml, .github/workflows/e2e-nvidia-l40s-x4-llama.yml, .github/workflows/e2e-nvidia-l40s-x4-py312.yml, .github/workflows/e2e-nvidia-l40s-x4-release.yml, .github/workflows/e2e-nvidia-l40s-x4.yml, .github/workflows/e2e-nvidia-l40s-x8.yml
**Checklist:**
We have a new Y-stream release: https://github.com/instructlab/ci-actions/releases
This PR bumps the minimum versions to consume the latest y-stream release's changes.
Note that we haven't made any changes to the `launch-ec2-runner-with-fallback` CI action in release v0.2, but I'm bumping the minimum version in case we do need to consume future bugfixes, etc. for that action.
=> chore: Bump ci-actions version to v0.2 + replace commit SHA in `constraints-update.yml`

.github/workflows/e2e-nvidia-l40s-x4-release.yml
Right now, the E2E job is checking out the latest commit on `main` by default.
**Checklist:**
=> fix: Force large E2E "release branch" job to check out latest release branch
