- SECURITY.md
> provide vuln reporting mechanism

- src/instructlab/train/linux_train.py
- src/instructlab/train/lora_mlx/utils.py
> remove remaining mentions of ibm hf repo

- src/instructlab/utils.py
Resolves #936
Bring the code in line with the check_yaml script error reporting in the taxonomy repo. In particular, we improve the message for too few seed examples.
> validation: Improve error message for too few examples provided

- .github/labeler.yml
Auto-labeler hasn't been updated in a bit, making some additions here with existing files/labels for maintainer ease
> ci: Update labeler.yml with additional files/labels

- README.md
Added a few additional badges to the README now that we're public
> docs: add additional badges to README

-  .markdownlint-cli2.yaml
- .github/workflows/docs.yml
- .markdownlint-cli2.yaml
- .spellcheck-en-custom.txt
- CONTRIBUTING/CONTRIBUTING.md
- CONTRIBUTING/FIRST_TIME_CONTRIBUTORS.md
- MAINTAINERS/STABLE.md
- Makefile
- README.md
- SECURITY.md
- containers/rocm/README.md
- docs/demo-slides.md
- docs/gpu-acceleration.md
- notebooks/README.md
- src/instructlab/generator/README.md
- src/instructlab/mlx_explore/README.md
- src/instructlab/train/lora_mlx/models/README.md
Adds a Markdown Linter - needs some testing before merge - I'll review the `hold` label and add reviewers once I feel it's ready
> ci: add markdown linter

- .github/mergify.yml
commit 3772f64034905cfdf63eeb125ddb145284fadab7
Date:   Mon Apr 29 11:12:03 2024 -0400
mergify: Update to latest set of test jobs
When I merged #984, I failed to ensure the mergify config was updated
accordingly to reflect the updated set of test jobs.
> mergify: Update to latest set of test jobs

- src/instructlab/lab.py
when downloading from HF, check check if the repo has .safetensor files. If it does, and `--filename` is default, download the entire repo and put it into a <repo_name> folder inside of models
Signed-off-by: Charlie Doern <cdoern@redhat.com>
> Make `ilab` able to download safetensors

- src/instructlab/lab.py
add `--hf-token` that defaults to the envvar HF_TOKEN, use snapshot_download to get the whole repo, and switch the check for HF_TOKEN to only see if instructlab is in the repo name, not full merl url
> Follow up to safetensor support

- README.md
**Description:** Just splits up command and adds a clarification for mac users
> Docs: Add install python packages on mac

- src/instructlab/utils.py
> Ensure we found some knowledge

- src/instructlab/lab.py
the code pulls from the env HF_TOKEN not from --hf_token
> --hf-token flag is not used in .14 release

- .github/mergify.yml
> mergify: Allow merging on release branches

- .github/mergify.yml
- .github/workflows/actionlint.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/pypi.yaml
- .github/workflows/spellcheck.yaml
- .github/workflows/test.yml
(cherry picked from commit d211e6cf6d873c06e922a96f9670419f9929a600)
> Run CI jobs on release branches

- README.md
> README.md: s/Instruct-Lab/InstructLab/

- containers/cuda/Containerfile
> Fix container build on machines without avx

- notebooks/README.md
Link for testing: [Testing the fine-tuned](https://github.com/RedHat-Israel/instructlab/blob/240503%2B101249/README.md#-test-the-newly-trained-model)
> fix link to "Testing the fine-tuned model"

- scripts/functional-tests.sh
A welcome message was introduced so the server wait is different now.
> ci: fix macos job

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .markdownlint-cli2.yaml
This PR adds templates for users opening issues for either bugs or enhancements, to ensure we are getting the proper information and standardizing the format of these kinds of issues for the ease of the maintainers
> Add Bug and Feature templates for new issues

- .spellcheck-en-custom.txt
- docs/release-strategy.md
> Document release strategy for Instructlab CLI

- notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
> notebook: open PR link

- notebooks/README.md
because repository is open-sourced
> add "Open the notebook in Colab"

- notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
Raw html link with numbers is noisy.
> beautify link to LoRA

- README.md
[preview](https://github.com/RedHat-Israel/instructlab/tree/diargam?tab=readme-ov-file#-what-is-ilab)
> docs: add inline mermaid diagram of basic workflow

- README.md
Resolves #1132
This PR suggests several improvements to "Welcome to the InstructLab CLI" to improve readability.
These are editorial changes only; no changes to the meaning of the section are proposed.
> Issue 1132 - Suggested improvements to "Welcome to the InstructLab CLI"

- src/instructlab/lab.py
> Fixes for linter in lab.py

- .github/workflows/test.yml
- Makefile
Now 'make' checks for commands being present or not before running targets. It handles missing commands nicely.
> feat: friendlier 'make'

- README.md
**Description:** Cleaning up some sections and titles in the README for readability. 
Additional info: Fixing the fails
> Docs: Making fixes in README

- docs/habana-gaudi.md
> docs: update habana-gaudi.md

- requirements.txt
- scripts/functional-tests.sh
- src/instructlab/chat/chat.py
Resolves # https://github.com/instructlab/instructlab/security/dependabot/1
Testing needs to be done on M3 Macs to ensure https://github.com/abetlen/llama-cpp-python/issues/1286 doesn't still occur.
> Update llama_cpp_python version to 0.2.75

- src/instructlab/lab.py
- src/instructlab/llamacpp/llamacpp_convert_to_gguf.py
- tests/test_lab_train.py
don't try to guess it or use hard-coded
from #1109 
for #1006
> use actual converted file name

- src/instructlab/config.py
- src/instructlab/generator/generate_data.py
- src/instructlab/lab.py
- src/instructlab/server.py
Extract model_family from model_path automatically by default.
--model-family forces model_family.
Resolves #1060
> Extract model_family from model_path automatically by default.

- scripts/functional-tests.sh
- src/instructlab/chat/chat.py
- src/instructlab/config.py
- src/instructlab/generator/utils.py
- src/instructlab/lab.py
- tests/test_config.py
the openAI client that connects to endpoint_url has a list of models the server can chat with.
We need to look through that list and ensure the user specified --model or -m exists in that list
Resolves #753
> Validate the existence of the model specified in --model

- README.md
> Update README with new download features and flags

- .github/workflows/validate-notebooks.yml
- notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
> Revert "notebook: more clean results code and output" and fix CI

- CONTRIBUTING/CONTRIBUTING.md
Update link to Code of Conduct and fix link to open an issue.
> docs: Update a couple of links in CONTRIBUTING.md

- src/instructlab/lab.py
Make the code more clean and readable using functional programming.
> refactor: remove unnecessary tmp var safe_tensors

- Makefile
`verify` help text was out of date, fixed that and a couple other minor things
> fix: inaccurate makefile help message

- src/instructlab/config.py
This change fixes a regression introduced in commit
bf332e84a3ddeaa4150bbeb6fb05648d6d0e8537 from PR #1174.
Prior to this commit, ilab would correctly use the `merlinte` model
family when using a granite model as that was the default. The change
in #1174 added some additional logic trying to guess the model family
based on filename to avoid having to specify `--model-family` in some
cases.
This change made the code automatically set the model family to
`granite`, which the code did not understand, which resulted in broken
model behavior.
The code has been updated to do the following:
- Understand that `granite` maps to `merlinite` for the model family
- When guessing a model family based on filename, don't assume the
result is valid. Validate it against the set of known model families
to …
> Use correct model family for granite

- src/instructlab/server.py
> update ensure_server(): wait longer time to make sure server is started

- README.md
- docs/gpu-acceleration.md
Update gpu-acceleration.md file to be in line with the recent update of llama-cpp-python 0.2.75 in https://github.com/instructlab/instructlab/commit/f24d0d7b5988f0999d821647a14c4500f7afa109
N/A
- Change `CUBLAS` to `CUDA` in env vars.
- Change version from 0.2.55 to 0.2.75 where applicable.
- Change links to point to the fixed 0.2.75 branch/tag of the llama-cpp-python repo.
> Update gpu-acceleration.md with llama-cpp-python 0.2.75

- README.md
> Ensure commands in "Installing ilab" section are easy to copy

- CHANGELOG.md
This adds a feature note about the redesign as requested by @leseb. Please let me know if this is not descriptive enough!
resolves #1333
> Add feature note about the ilab command redesign

- .markdownlint-cli2.yaml
- .spellcheck-en-custom.txt
- notebooks/README.md
- notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
This PR brings some minor changes to the text of the Jupyter notebook `notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb`, mainly to improve readability.
* Updates the name of the cli (`lab` -> `ilab`)
* Updates the name of the project (InstructLab, not `instruct lab`)
* Makes some stylistic improvements
* fixes a few typos
The content itself, including the code, is untouched.
Please ignore whitespace with `&w=1` when looking at the diff.
> Stylistic improvements to notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb

- pyproject.toml
Update pyproject.toml author to reflect the project name, the dev email and website.
**Checklist:**
> update py project authors and website

- pyproject.toml
- src/instructlab/data/generate.py
- src/instructlab/model/backends/backends.py
- src/instructlab/model/backends/llama.py
- src/instructlab/model/chat.py
- src/instructlab/model/serve.py
This commit lays the foundation for supporting multiple backends in the InstructLab project. Key changes include:
- Refactored the server module to introduce a base `BackendServer` class, enabling the implementation of various backends.
- Moved and renamed `server.py` to `llama.py` within a new `backends` directory, aligning with the new backend architecture.
- Updated imports and usage of `ensure_server` across the project to reflect the new location and structure.
- Introduced abstract methods `run` and `shutdown` in `BackendServer` to ensure all backends implement these essential operations.
- Modified the `Server` class to inherit from `BackendServer`, implementing the `run` and `shutdown` methods specific to the llama backend.
- Adjusted the `serve` command to instantiate and run the …
> Refactor: server architecture to support multiple backends

- .github/workflows/stale_bot.yml
Stale Bot is not working as expected in this repo but it is in the `taxonomy` repo
Updating the config here to more closely align with what is in that repo
**Checklist:**
> Fix Stale Bot action

- CHANGELOG.md
We are in the 0.18 release cycle so let's use that section for new features and breaking changes.
**Checklist:**
> bump CHANGELOG to 0.18

- src/instructlab/model/train.py
> fix: clean training result final directory to make sure training can work after a failure training

- src/instructlab/train/linux_train.py
Pay attention that version and language names are optional in huggingface.co/docs URL.
> add more links to huggingface.co/docs articles

- README.md
Resolves #1381
I kind of messed things up in the last PR and lost track of commits. I'm sorry if that may have caused any inconveniences.
**Checklist:**
> docs: added upgrade instructions to README.md

- .github/workflows/test.yml
- .pylintrc
- README.md
- pyproject.toml
- tox.ini
dolomite does not have python 3.9 support. Remove 3.9 tests and edit docs, pyproject, etc.
**Checklist:**
> python version bump

- containers/cuda/Containerfile
- containers/hpu/Containerfile
- containers/rocm/Containerfile
> com.redhat.component label

- docs/release-strategy.md
preceeds -> precedes
**Checklist:**
> docs: update release-strategy.md

- src/instructlab/model/train.py
The `TorchDeviceParam` class and `TORCH_DEVICE` object are no longer used. The code was accidently re-added during refactoring.
**Checklist:**
> Remove dead code `TorchDeviceParam`

- .pylintrc
- src/instructlab/config/init.py
- src/instructlab/data/generate.py
- src/instructlab/mlx_explore/gguf_convert_to_mlx.py
- src/instructlab/mlx_explore/utils.py
- src/instructlab/model/backends/backends.py
- src/instructlab/model/backends/vllm.py
- src/instructlab/model/chat.py
- src/instructlab/model/convert.py
- src/instructlab/model/serve.py
- src/instructlab/model/train.py
- src/instructlab/train/lora_mlx/lora.py
- src/instructlab/train/lora_mlx/prepare_model.py
- tests/test_utils.py
- tox.ini
pylint does not play well with implicit namespace packages. Add `__init__.py` to all subpackages to make them standard Python module packages.
**Checklist:**
> Add missing __init__.py, fix about 60 pylint violations

- src/instructlab/configuration.py
- src/instructlab/data/generate.py
- src/instructlab/model/backends/backends.py
- src/instructlab/model/backends/llama_cpp.py
- src/instructlab/model/backends/vllm.py
- src/instructlab/model/chat.py
- src/instructlab/model/serve.py
- tests/test_config.py
- tests/test_lab_generate.py
> Serve vllm using subprocess instead of multiprocessing

- requirements.txt
Resolves #1542 
**Checklist:**
> deps: Bump min eval version to 0.0.4

- src/instructlab/model/train.py
Resolves #1550 
**Checklist:**
> fix: mypy issue with training library

- src/instructlab/data/generate.py
- src/instructlab/model/backends/backends.py
- src/instructlab/model/backends/llama_cpp.py
- src/instructlab/model/backends/vllm.py
- src/instructlab/model/chat.py
- src/instructlab/model/evaluate.py
Avoid duplicated code and shorten long functions.
> refactor ensure_server, run_detached: return api_base

- scripts/basic-workflow-tests.sh
Now that we have the ability to run full training in e2e CI, make it
run the rest of the tests - serve the resulting model and run chat
against it to make sure it works.
> e2e: test serving model after training

- pyproject.toml
- requirements.txt
- src/instructlab/model/backends/backends.py
- src/instructlab/model/backends/llama_cpp.py
- src/instructlab/model/backends/vllm.py
- src/instructlab/model/evaluate.py
- src/instructlab/model/serve.py
- src/instructlab/utils.py
Next steps will be: adding more type annotations to existing functions; enabling stricter validations (--strict), revisiting existing type annotations and maybe tightening where possible (str -> Path, fewer Unions etc.)
> mypy: tackle all violations in excluded files

- scripts/infra/README.md
- scripts/infra/local-setup.sh
This PR adds a func to `cloud-instance.sh` that installs all necessary dnf-based packages for Fedora/RHEL
**Checklist:**
> Add func to install nessessary packages for AWS

- scripts/basic-workflow-tests.sh
The e2e script has now a new '-v' option (do not think verbose) that
will activate the vLLM backend when running the server.
We are sort of approaching the limit of what 'getopts' can do in terms
of choosing meaninful options. We could in the future transition to
'getopt' to allow for long flag to be added.
Closes: https://github.com/instructlab/instructlab/issues/1456
**Checklist:**
> ci: add option to run e2e test with the vLLM backend

- src/instructlab/model/evaluate.py
display evaluate command parameters in debug mode
**Checklist:**
> display evaluate command parameters in debug mode

- src/instructlab/model/evaluate.py
Given the serving api can return errors for generation and judgment requests, we need to show the error rate in case it's significant enough to have an effect on the results
**Checklist:**
- [*] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
> feat: Display api error rate for mt_bench and mt_bench_branch

- scripts/basic-workflow-tests.sh
- scripts/test-data/e2e-qna-knowledge.yaml
This is a smaller test, so it will run in CI quicker, but it still
exercises the knowledge pipeline.
Signed-off-by: Russell Bryant <russell.bryant@gmail.com>
> Switch to tonsils knowledge sample for e2e

- .spellcheck-en-custom.txt
- CHANGELOG.md
- src/instructlab/configuration.py
- src/instructlab/model/evaluate.py
- tests/test_config.py
Implements --gpus option for evaluate.
Resolves #1549
**Checklist:**
- [x ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
- [ x] Unit tests have been added, if necessary.
> Implements --gpus option for eval

- src/instructlab/configuration.py
> fix: minor typo in config init message

- .github/workflows/e2e-nvidia-a10g-x1.yml
- docs/ci.md
- scripts/basic-workflow-tests.sh
> ci: add ilab model evaluate mmlu to basic-workflow-tests

- pyproject.toml
- requirements-vllm-cuda.txt
This PR switches to using a hardened branch of vllm that makes it easier to align dependencies on, and has been tested to work well in combination with future the SDG improvements. In the future we may provide a version of these requirements that tracks with the latest upstream
**Checklist:**
> build: change vllm version to github.com/opendatahub-io/vllm

- scripts/functional-tests.sh
- src/instructlab/model/backends/backends.py
Lets the user know that the cli process is trying to connect to vLLM/Llamacpp- that it's not stalled.
**Checklist:**
> Improves logging when connecting to vLLM / Llamacpp

- src/instructlab/model/serve.py
- tests/test_backends.py
Additional vLLM args are now passed as click extra args. They are more convenient to use than passing each extra argument as a separate arg.
```console
ilab model serve ... --backend=vllm -- --dtype=auto --enable-lora
```
Also clean up unnecessary parameter handling in llama-cpp path.
**Checklist:**
> Pass vllm args as extra arguments

- CHANGELOG.md
- README.md
- scripts/functional-tests.sh
- src/instructlab/model/backends/backends.py
- src/instructlab/model/linux_test.py
- src/instructlab/model/test.py
- src/instructlab/utils.py
- tests/test_lab_model_test.py
linux_test is implemented like the chat and the generate with OpenAI client.
Don't use TLS for simplicity, assuming it's a local server only because fine-tuned model is local.
Resolves #659
Testing: #632
**Checklist:**
> linux_test

- docs/ci.md
This is a target e2e configuration that we do not have working yet,
but is the highest priority configuration to get working. Document
that combination in the table.
> docs: Document target e2e configuration

- src/instructlab/configuration.py
- src/instructlab/model/evaluate.py
- tests/test_config.py
- tests/test_lab_evaluate.py
> Rename sdg-path to tasks-dir for ilab model evaluate with mmlu

- src/instructlab/model/evaluate.py
- tests/test_lab_evaluate.py
This logic improves upon the lack of specific error handling between eval and instructlab around git repo related errors.  It replaces exceptions dumped to the terminal with understandable error messages.
**Checklist:**
> fix: Eval git repo and model not found error handling

- CHANGELOG.md
- src/instructlab/model/backends/backends.py
- src/instructlab/model/backends/llama_cpp.py
- src/instructlab/model/backends/vllm.py
- src/instructlab/model/evaluate.py
- src/instructlab/model/serve.py
Also add more debug logging to vLLM server detection loop.
**Checklist:**
> feat: Configure vLLM stdout/stderr suppression when running detached

- docs/ci.md
> docs: Tie clarification notes to cells in the table

- requirements.txt
- tests/test_lab_evaluate.py
Follow on to:
https://github.com/instructlab/instructlab/pull/1677
and
https://github.com/instructlab/eval/pull/64
**Checklist:**
> Adding test case for tasks_dir not found error

- src/instructlab/model/evaluate.py
> Flipping enable_serving_output flag to match background intention

- src/instructlab/model/evaluate.py
With the previous logic, the backend was actually selected after the params were setup.  This new logic makes sure we have the right backend selected before params are configured.
**Checklist:**
> Fix backend not being set for setting up serving params

- src/instructlab/data/generate.py
> feat: allow passing file as pipeline

- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-a10g-x4.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
> fix: harden remaining ec2 actions in E2E jobs

- src/instructlab/model/evaluate.py
Previously, --gpus wouldn't take effect if --tensor-parallel-size was set in serve vllm_args.  The normal behavior is that options should override config.  And a user could very possibly want to pass a different value than they use for the serve config.  Whether that value is set as an option or as evaluate config.
Also, the previous logic wasn't handling the --tensor-parallel-size=value format
**Checklist:**
> Change --gpus to override when set and handle different vllmarg styles

- src/instructlab/model/evaluate.py
Adding annotations helps callers to understand the function signature and the types that are expected to be passed.
Closes: https://github.com/instructlab/instructlab/issues/1745
**Checklist:**
> fix: add annotations to launch_server

- .spellcheck-en-custom.txt
- CHANGELOG.md
Updates the changelog to reflect the changes made in PR #1471.
Resolves #1660
**Checklist:**
> updates the changelog to reflect the changes made in PR #1471

- src/instructlab/model/backends/backends.py
- tests/test_backends.py
Adds new `is_model_safetensors` function that checks if supplied model path is a directory, and if so, checks if it qualifies as a safetensors model. Since a valid safetensors model should have the safetensors itself, along with required files for the tokenizer, we check to ensure all these files are present in the directory before concluding that the supplied modle path is a valid safetensors model 
Resolves #1457 
**Checklist:**
> feat: improve auto-detection check for safetensors models

- requirements-vllm-cuda.txt
**Checklist:**
- [ x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
> chore: Update vllm to 2024.07.17

- .github/workflows/e2e-nvidia-a10g-x4.yml
add the deps in the A10x1 runner yaml to the A10x4 runner file
wheel, instructlab-training[cuda]
the
**Checklist:**
> fix A10x4 runner Deps

- src/instructlab/clickext.py
PR #1622 added `--debug-params` helper. The helper was reporting the wrong parameter source for values from nested default map. `ConfigOption` now reports the correct source when the value is read from default map.
**Checklist:**
> Fix: show correct parameter source for ConfigOption

- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-a10g-x4.yml
> fix: typo in LD_LIBRARY_PATH definition in workflows

- scripts/infra/cloud-instance.sh
- scripts/infra/instructlab-cloud-config-example
- scripts/infra/nvidia-setup.sh
- Use precompiled nvidia driver approach to bring parity with bootc images
+ align driver versions and cuda libs.
- Update pip build process to be compliant with odh vllm
- Use constraints to ensure compatible dependency set
- Drop system pip install to avoid conflicts with venv approach
- Introduce new update command to manage updates, since drivers must be rebuilt
- Add ssh monitoring support for script initiated reboots
**Checklist:**
- [ x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
- ~~[ ] [Changelog](https://github.com/instructlab/instructlab/blob/main/CHANGELOG.md) updated with breaking and/or notable changes for the next minor release.~~
- ~~[ ] Documentation has …
> chore: update cloud provisioning

- src/instructlab/model/download.py
- src/instructlab/utils.py
This addresses comments from https://github.com/instructlab/instructlab/pull/1756 ; plus it optimizes the way symlinks are created, a bit.
> Follow-up to OCI download PR merged

- README.md
Part of https://github.com/instructlab/instructlab/issues/1782
**Checklist:**
> docs: add README section for evaluation

- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-a10g-x4.yml
- docs/ci.md
- scripts/basic-workflow-tests.sh
This PR has the following Features/PRs that put the 4xA10 workflow in an ideal state:
1.  Adding CACHE_DIR as a location to search for models: https://github.com/instructlab/instructlab/pull/1844
2.  Getting vLLM to work in basic-workflow.sh: https://github.com/instructlab/instructlab/pull/1841
The linked PR has multiple other fixes made to the test script, that are also in this PR. In the process of adding vLLM support, the `-g` flag (for GRANITE) was removed. Granite will now be the base model used in the entire workflow, mirroring the ideal ilab workflow.
3.  Adds remaining model evaluation benchmarks to the CI: https://github.com/instructlab/instructlab/pull/1676
4. Update ci.md to reflect the test matrix after this PR would be merged
5. Add the `-x` flag to `set` for faster debugging …
> ci: `basic-workflow-tests.sh` improvments for 4xA10 workflow

- requirements.txt
- requirements/cuda.txt
> bump instructlab-training to most recent version

- .github/ISSUE_TEMPLATE/design_change.md
I've seen a lot of "bugs" get filed that aren't really bugs - rather, they are proposed changes to the ilab design. This issue template makes it so it's easier for Maintainers to differentiate between actual bugs and design changes.
**Checklist:**
> github: add new issue template for design change

- src/instructlab/data/generate.py
`ilab data generate` ignores `--model` and instead uses the teacher model in the cfg. honor `--model` as an override
**Checklist:**
> set teacher model in generate to the value passed via `--model`

- src/instructlab/utils.py
There is a divergence between how the SDG library does validation and the 'taxonomy diff' command does the validation of the taxonomy. This brings it in line.
Resolves #1911 
**Checklist:**
> fix: Bring 'taxonomy diff' validation in line with 'data generate'

- README.md
> docs: update 'ilab taxonomy diff' README section

- CHANGELOG.md
- pyproject.toml
- src/instructlab/data/list.py
- src/instructlab/model/list.py
- src/instructlab/utils.py
- tests/test_lab.py
- **add `ilab model list`**
- **feat: introduce `ilab data list` to list datasets**
This PR follows the work done by @cdoern in PR #1840. 
Specifically, this PR now enables the user to list out available datasets
using a new command: `ilab data list`. This way, when the user generates
data, they can access it much more easily.
Here's an example output from the new command:
```
+------------------------------------------------------------+---------------------+-----------+
| Dataset                                                    | Created At          | File size |
+------------------------------------------------------------+---------------------+-----------+
| train_merlinite-7b-lab-Q4_K_M_2024-07-25T00_47_21.jsonl    | 2024-07-25 00:49:37 | 16.94 KB  |
| …
```
> feat: add `ilab data list`

- README.md
> Update example contents in 'ilab data generate'

- src/instructlab/model/train.py
> Add missing ilab model train help screen description

- src/instructlab/data/generate.py
> Fix missing import and typo

- src/instructlab/model/list.py
> Add missing ilab model list help screen description

- requirements.txt
> Bumping min versions for eval and sdg

- src/instructlab/configuration.py
- tests/testdata/default_config.yaml
> Changing few_shots default to 5

- src/instructlab/common.py
Updates the default system prompt used by `ilab model chat` to match current [sdg generated data](https://github.com/instructlab/sdg/blob/20ac841276d4920ddfb9b7259dbf44b7dadc7fa9/src/instructlab/sdg/generate_data.py#L41), instructlab models, and legal-approved message.
**Checklist:**
> Updating system prompt to match generated data, current ilab models, and updated crediting

- src/instructlab/model/train.py
> feat: add --enable-serving-output flag for phased training

- src/instructlab/config/init.py
> Adding help desc to --train-profile flag for ilab config init

- src/instructlab/configuration.py
Follow-up to #1959 
**Checklist:**
> Update hw config values for training

- README.md
> doc: change path to downloaded model in README.md

- src/instructlab/system/info.py
Added small improvements and clarifications to ilab system info output
> add hostname, python version and capabilities definition to system info output

- src/instructlab/model/chat.py
Currently, when launching ilab model chat, we check to see if the user is serving
on the endpoint url before proceeding. The issue is that the endpoint url is set
to a default value equivalent to http://localhost:8000 - which also happens to
be the default value that we set in the serve config. Instead of checking for
this default, we should instead read the host port from the users serve config
and check that to see if anything is being served. This will provide cleaner
logic - as we can assume that the user just wants us to connect directly
when endpoint url is provided and skip the precheck which is currently used
to determine whether or not we should start a server ourselves
Resolves #1882 (partially) 
**Checklist:** …
> fix: replace default endpoint with config value reading

- requirements.txt
- requirements/cuda.txt
To make use of the latest updates in the training library, this commit bumps the version
number from v0.3.2 to v0.4.0
**Checklist:**
> chore: update minimum training library version

- .github/mergify.yml
This fix updates the `files` attributes to use valid regex expressions (`~=` operator) when needed and exact match (`=` operator) otherwise. Globs are not supported and are replaced by regex. We use `^` and `$` to properly anchor the regex as needed. Leading and trailing `.*` are removed as they are not necessary.
For consistency across the multiple workflow conditions, we move the `check-success` condition to the top. We also remove unneeded quote characters as they were inconsistently used.
The `files` conditions are updated to properly match the globs used in the corresponding workflows. References to no-longer-present files are removed.
A `check-success` condition for the `spellcheck` job is added as it was missing. An old action for release-v0.14 is removed.
**Checklist:** …
> mergify config: Fix and update for valid regex and consistency

- requirements.txt
- requirements/cuda.txt
> Bump training lib to 0.4.1 to support optional save_samples

- README.md
Modified the eval MMLU benchmark commands in the README to reflect the latest changes.
**Checklist:**
> Update README with revised eval command usage

- scripts/infra/README.md
- scripts/infra/cloud-instance.sh
- scripts/infra/local-setup.sh
Adds to and updates some shell automation around IBM Cloud as well as related documentation
**Checklist:**
> infra: add additional support for IBM Cloud

- src/instructlab/model/evaluate.py
This code and the contains_argument helper where added at the same time, this is a follow-up to share the impl
**Checklist:**
> Used common method for contains argument

- CHANGELOG.md
Adjusted the text format of some flags in the `ilab model evaluate`
commands section of the changelog for improved readability and consistency.
**Checklist:**
> Update flag text format in `ilab model evaluate` commands in changelog

- README.md
- src/instructlab/utils.py
With #2087, we now support running diff against an empty taxonomy. Some of the README and logging was still a bit ambiguous around it so here are some proposed updates.
**Checklist:**
> update README and logging for ilab taxonomy diff

- src/instructlab/model/backends/backends.py
> Don't read gguf header with mmap

- .pylintrc
- tests/common.py
- tests/test_lab_evaluate.py
- tests/test_lab_generate.py
- tests/test_lab_serve.py
This is a follow-up to #2040.
Note to reviewers: `common.py` is largely (refactored) code from `test_lab_serve.py`
> tests: Validate that null vllm_args are accepted

- src/instructlab/model/evaluate.py
The combination of
https://github.com/instructlab/instructlab/pull/2072 and
https://github.com/instructlab/instructlab/pull/2046
caused a new test case failure.  It was a real problem (on mac) that was the cause but didn't result in test case failures without the two changes combined.
```
__________________________ test_vllm_args_null ___________________________
cli_runner = <click.testing.CliRunner object at 0x31efe4190>
def test_vllm_args_null(cli_runner: CliRunner):
fname = common.setup_gpus_config(section_path="serve", vllm_args=lambda: None)
>       args = common.vllm_setup_test(
cli_runner,
[
f"--config={fname}",
"model",
"evaluate",
"--benchmark",
"mt_bench",
"--model",
"instructlab/granite-7b-lab",
"--judge-model",
"instructlab/merlinite-7b-lab",
"--gpus",
"4",
],
) …
```
> Fixing test case broken by conflicting merges

- requirements.txt
caps dependency versions for future v0.18.z releases of instructlab 
**Checklist:**
> chore: cap dependency versions for instructlab libraries

- scripts/basic-workflow-tests.sh
> fix: missing exit in E2E script

- scripts/basic-workflow-tests.sh
> tests: add E2E test funcs for `system info` and `config show`

- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-a10g-x4.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
> ci: update runner labels to uniquely identify instance sizes

- src/instructlab/model/train.py
Using American English spelling of judgment to be consistent with evaluate
**Checklist:**
> Fixing typos

- src/instructlab/configuration.py
- src/instructlab/model/evaluate.py
- tests/test_lab_evaluate.py
Valid values include 'auto' and positive integers
**Checklist:**
> batch_size should allow for str or int

- .github/mergify.yml
This commit introduces a commit message template in the mergify.yml
configuration file. The template includes the pull request title,
number, body, and a list of users who approved the review.
One important feature is to add the name of approvers to the PR, so the
merge commit will include fields like:
```
Approved-by: leseb
```
**Checklist:**
> ci: improve merge commit content

- .github/workflows/test.yml
> chore: explain why free-disk-space is linux only

- .github/ISSUE_TEMPLATE/bug_report.md
> github: update bug template to use `ilab system info`

- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-a10g-x4.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
this allows us to explicitedly see which PR number is associated with each runner in the AWS console
**Checklist:**
> ci: add GitHubPR to AWS labels

- tests/test_config.py
Every option in `configuration.py` must include a description in its Field. We've implemented a unit test to ensure that whenever a new option is added, it comes with a description.
**Checklist:**
> tests: add test to ensure all config options have descriptions

- .github/workflows/e2e-nvidia-a10g-x4.yml
- docs/ci.md
Resolves #1806 
Followups may be required
**Checklist:**
> ci: add Slack notification step to nvidia-a10g-x4 job

- src/instructlab/model/chat.py
We try to surface as much information as we can using DEBUG level logging when the temporary server crashes. This is important when running the chat without a server or a generation.
**Checklist:**
> feat: better troubleshooting on internal server error

- scripts/infra/cloud-instance.sh
fd53014 cloud-instance.sh: Document ec2 terminate command
commit fd530145cd009c77d5be62dc63cee6a0d0579191
Date:   Thu Sep 5 09:50:54 2024 -0400
cloud-instance.sh: Document ec2 terminate command
This command exists, but was not in the help text.
> cloud-instance.sh: Document terminate command

- .github/workflows/e2e-nvidia-a10g-x4.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- docs/ci.md
- scripts/basic-workflow-tests.sh
removes extra 'ilab system info' step
updates documented issue in ci.md
updates E2E shell script for clarify/consistency
**Checklist:**
> cleanup: adjustments to minimal E2E job

- README.md
> Removed out-of-date What's new section in README.md (issue #2187)

- .github/workflows/e2e-nvidia-a10g-x4.yml
> refactor: adjust slack messages to add link to job

- README.md
Description: README: Add a note about the `python3` CLI.
This issue was identified at another PR https://github.com/instructlab/instructlab/pull/2083, and the way of fixing was suggested at https://github.com/instructlab/instructlab/pull/2083#pullrequestreview-2242982596.
I don't find the issue ticket about this issue.
You can check the modified `REAME.md` [here](https://github.com/junaruga/instructlab/blob/wip/readme-python-cli/README.md#-installing-ilab).
**Checklist:**
> README: Add a note about the `python3` binary.

- README.md
Description: README: Fix typos in the output of the `ilab model chat`.
The output of the `ilab model chat` has some issues about typo or formatting in the section `Chat with the model (Optional)` in [the `README.md` at the latest commit](https://github.com/instructlab/instructlab/blob/75c79111ef16275d9c67fa9a7350180b60ea4b9f/README.md#-chat-with-the-model-optional). I fixed the following 3 points.
1. I believe that the prompt `>>b>` is wrong. Replaced it with the `>>>`.
2. The position of the `│` is needed to adjust.
3. Maybe, the `what is the capital of Canada` should be the `what is the capital of Canada?` with the question mark `?`. Because it is mentioned in the sentence "Before you start adding new skills and knowledge to your model, you can check its baseline performance by asking …
> README: Fix typos in the output of the `ilab model chat`.

- README.md
- src/instructlab/config/init.py
updates text clarifying reset procedure
rewords misleading text about non-nvidia gpu support
enhances profile choices to be more human-readable
Resolves #2028
**Checklist:**
> ux: update training profile prompts for clarity

- tests/test_lab.py
With the introduction of lazyloading click command from entrypoints, we lost the ability to list command through `lab.ilab.commands.items()`. The test was always returning true. Adapted to load the commands and flags from entrypoints instead.
**Checklist:**
> fix: test_cli_params_hyphenated

- src/instructlab/configuration.py
Resolves https://github.com/instructlab/instructlab/issues/1538
**Checklist:**
> chore: cleanup and add comments to Config classes

- README.md
> update note for apple m installation

- CHANGELOG.md
- src/instructlab/config/init.py
- src/instructlab/configuration.py
- tests/test_lab_init.py
add auto selection for NVIDIA GPU train profiles. This uses torch under the hood
to read the amount of GPUs, tally the total vram, the GPU type, and the GPU amount. Use this information to choose the train profile which best matches the amount of GPUs/the GPU type. If none of these match, then match based off of vRAM. for good measure, set nproc_per_node at the end if basing of off vRAM. in case we found a profile which matches our vRAM amount but not our GPU amount
the workflow is as follows:
```ilab config init
Found /home/ec2-user/.config/instructlab/config.yaml, do you still want to continue? [y/N]: y
Existing training profiles were found in /home/ec2-user/.local/share/instructlab/internal/train_configuration/profiles
Do you also want to restore these profiles to the default values? …
```
> feat: train profile auto selection

- scripts/infra/cloud-instance.sh
When using stop/start to turn off and on dev instances, the public IP
address will change. I keep an entry in my ssh config to make it easy
to connect to these instances (both with ssh manually, as well as with
vscode over ssh). I found myself using "ec2 details" to get the new IP
and then updating my config. After a handful of times of this, I
decided to automate it.
Once an instance is running, you can run `ec2 update-ssh-config` and
it will either add the instance to the ssh config, or update it with
the latest address (via the hostname derived from the public IP, since
there was already code in the script to grab that).
> cloud-instance.sh: Add ssh config management

- src/instructlab/model/backends/backends.py
> enhance gguf check

- .github/PULL_REQUEST_TEMPLATE.md
> github: update PR template to account for dev docs

- .github/mergify.yml
> fix: mismatch between trigger and merge CI criteria

- src/instructlab/system/info.py
> add cpu_branch for darwin

- requirements.txt
- requirements/cuda.txt
- src/instructlab/configuration.py
- src/instructlab/model/train.py
- tests/testdata/default_config.yaml
support FSDP CPU offloading via the CLI and config file
resolves #2276
**Checklist:**
> add support for FSDP options

- .github/mergify.yml
- .github/workflows/lint.yml
- .github/workflows/status-checks.yml
- .github/workflows/test.yml
The workflow-complete jobs used job.needs which meant their job ids did not show up in the check-runs until they started. This can be some time since lint jobs take ~20min (and test jobs ~40min). Since the workflow-complete job ids do not appear for quite some time, the status checks in other jobs do not see them and properly wait for them to complete. For example, this allowed the test jobs to start while the lint jobs were still executing.
We change from using job.needs to using a status checks workflow to wait for the member jobs to complete. This quickly creates the entry in check-runs for the workflow-complete jobs which then allows other status check jobs to see these job ids and wait upon their completion.
Since the workflow-complete job's names are nested, we update the mergify …
> Fix workflow-complete jobs for use by status check jobs

- README.md
with the implementation of `--pipeline=simple/full/accelerated` the README needs to describe what the different techniques are and when to use them
**Checklist:**
> docs: Document Current State of Training

- requirements.txt
> cap instructlab libraries for 0.19 release

- .github/workflows/e2e-nvidia-l40s-x4.yml
> ci: change subnet for e2e-nvidia-l40s-x4 job

- src/instructlab/system/info.py
- Added memory information to the output
- Organized system info output into categories with headers
- Renamed get_sysinfo to get_sysinfo_by_category to closer match new functionality
**Checklist:**
> add memory check and pretty output

- src/instructlab/model/full_train.py
- change LR to 2e-5 (learns better)
- honor the gradient accumulation given by the multipack sampler
the LR is the big change here. The previous version of full train has little to no improvement after 8 epochs. This version knows about the new information after as little as 1 epoch.
This is a major improvement. 
Also add logging to print information about the data
**Checklist:**
> full train fixes

- src/instructlab/model/list.py
> for models from a registry other than HF, we need to follow symlinks.

- src/instructlab/model/backends/backends.py
- src/instructlab/model/backends/llama_cpp.py
The backends module, along with the llama_cpp module,
Move UvicornServer and get_uvicorn_config 
to reduce the circular dependency
llama_cpp.py -> backends.py.
```mermaid
graph LR;
subgraph backends
x[UvicornServer]
style x opacity:0
select_backend
style select_backend opacity:0
end
backends --> llama_cpp
linkStyle 0 opacity:0
select_backend --> llama_cpp --> x
```
Final state of [Acyclic dependencies](https://en.wikipedia.org/wiki/Acyclic_dependencies_principle):
```mermaid
graph LR;
subgraph backends
select_backend
style select_backend opacity:0
end
subgraph llama_cpp
v[Server]
style v opacity:0
x[UvicornServer]
style x opacity:0 …
```
> refactor: move UvicornServer & co to llama_cpp.py

- src/instructlab/model/list.py
the comment says we don't follow symlinks when in reality we do
**Checklist:**
> chore: update symlink list comment

- src/instructlab/config/init.py
> chore: remove 'also' from init text

- requirements/rocm.txt
> fix: Add dependency on instructlab-training for ROCm

- scripts/test-data/train-profile-l40s-x4.yaml
> ci: use FSDP distributed backend for training in L40sx4 job

- README.md
Related: https://github.com/instructlab/instructlab/issues/2425
**Checklist:**
> Update readme noting lack of mmlu gguf support

- README.md
Reformat some output in `README.md` and make it easy to read:
- Use form for `ilab config init` directory part
- Use form for  `ilab model trian` pipeline/strategy part
- Use `tree` show  for `ilab model train` Mac outputs, checkpoints, datasets
**Checklist:**
> reformat output in README.md

- src/instructlab/configuration.py
- src/instructlab/model/chat.py
- tests/test_model_chat.py
- tests/testdata/default_config.yaml
During the chat(or specify in cli), it can change the `context`,  actually, no any tips show what are the available contexts are? And what is the content? Besides  wrong input, it will tell.
~~~
>>> /c xx                                                                              [S][default]
╭──────────────────────────────────────────── system ─────────────────────────────────────────────╮
│ WARNING: Context xx not found. Available contexts: default, cli_helper                          │  
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
>>> /h                                                                                       [S][default]
╭─────────────────────────────────────────────── system …
> list contexts

- src/instructlab/utils.py
- tests/test_backends.py
enhance `is_model_safetensors`,  add the check for `safetensors` file
```
ls -lh *test_model.safetensors
-rw-r--r--  1 xx  xx    16B Oct 10 23:02 empty_tensors_test_model.safetensors
-rw-r--r--  1 xx  xx   184B Oct 10 23:02 test_model.safetensors
-rw-r--r--  1 xx  xx     0B Oct 10 23:07 empty_test_model.safetensors
$ ilab -v model list
DEBUG 2024-10-10 23:03:11,117 instructlab.model.backends.backends:48: No tensors found in /Users/xx/.cache/instructlab/models/instructlab/granite-7b-lab/empty_tensors_test_model.safetensors
DEBUG 2024-10-10 23:12:39,357 instructlab.model.backends.backends:52: Error while processing /Users/xx/.cache/instructlab/models/instructlab/granite-7b-lab/empty_test_model.safetensors: Error while deserializing header: HeaderTooSmall
```
**Checklist:**
[conventional …
> validate the safetensors file

- README.md
There are some issues when used `bash completion` in `MacOS`, so try to improve the doc
**Checklist:**
> update the MacOS bash completion note

- scripts/e2e-ci.sh
- scripts/test-data/train-profile-l40s-x4.yaml
- src/instructlab/configuration.py
- src/instructlab/model/train.py
- tests/testdata/default_config.yaml
with the upcoming system profiles work, pipeline should be a config entry so that ilab can detect, and set it for the user
**Checklist:**
> chore: add pipeline to train configuration

- scripts/e2e-ci.sh
- scripts/test-data/train-profile-l40s-x4.yaml
- src/instructlab/configuration.py
- src/instructlab/model/train.py
- tests/testdata/default_config.yaml
Should go in after https://github.com/instructlab/instructlab/pull/2460
**Checklist:**
> chore: add device to train configuration

- src/instructlab/model/full_train.py
Makes the full train script slightly more resistant to upcoming instructlab-training library changes, and ensures compatibility with both the current version and post-https://github.com/instructlab/training/pull/257
**Checklist:**
> Make full train compatible with updated library

- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- docs/ci.md
- scripts/e2e-ci.sh
Also changed Small-size E2E CI job to use new `e2e-ci.sh` script
Followup to https://github.com/instructlab/instructlab/pull/2452 and https://github.com/instructlab/instructlab/pull/2468
**Checklist:**
> Update Medium-size E2E CI job to use `full` SDG

- scripts/e2e-ci.sh
- src/instructlab/model/evaluate.py
> ci: use export to set $HOME

- scripts/e2e-ci.sh
> fix: medium e2e bug where generate points to repo not model

- CONTRIBUTING/CONTRIBUTING.md
Making a clear disambiguation up front that this is for contributing to the CLI codebase as opposed to say the taxonomy or other libraries....
Adding a paragraph to frame the project as fast-paced and redirecting to taxonomy for those who may feel lost at this level of rapid development
**Checklist:**
> docs: fit & finish polish to contributing.md

- docs/ci.md
> docs: fix some things in ci.md

- docs/conf.py
> fix: sphnix doc build needed updated myst config

- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- scripts/infra/cloud-instance.sh
- scripts/infra/nvidia-setup.sh
> Bump ami to include cudnn9 and nvrtc

- src/instructlab/model/accelerated_train.py
Previously, the instructlab/training run_training function would handle errors
by silently failing and reporting a success. As of training PR #217, we have fixed
this behaior by now raising a RuntimeError when we encounter a problem inside of
the training loop. This commit handles this error inside of the accelerated and
phased training pipelines.
**Checklist:**
> chore: wrap training library with try/catch handles

- .github/mergify.yml
- .github/workflows/e2e-nvidia-a10g-x1.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- README.md
- docs/ci.md
`-v` was added to `pip install` output so we can see environmental variable info for debugging issues related to installation 
**Checklist:**
> ci: E2E jobs now use GitHub var for AWS AMI and run `pip install` in verbose mode

- src/instructlab/config/init.py
Reformat the `config init` output, make it better to view:
```
$ ilab config init
Existing config file was found in:
/Users/test/.config/instructlab/config.yaml
Do you still want to continue? [y/N]: y
Existing training profiles were found in:
/Users/test/.local/share/instructlab/internal/train_configuration/profiles
Do you want to restore these profiles to the default values? [y/N]: y
----------------------------------------------------
Welcome to InstructLab CLI
This guide will help you to setup your environment
----------------------------------------------------
Please provide the following values to initiate the environment [press Enter for defaults]:
Path to taxonomy repo [/Users/test/.local/share/instructlab/taxonomy]: /Users/test/test-test1
`/Users/test/test-test1` seems to not …
```
> reformat the config init output

- README.md
Just reformat the `ilab config init` output, so update it in `README.md`.
**Checklist:**
> update ilab config init output

- src/instructlab/model/download.py
uppercase issue in `download.py`
**Checklist:**
> uppercase issue

- scripts/e2e-ci.sh
- scripts/phased_training_resume.py
Creates new script to try each phase (phase1, phase2, mt_bench) of phased training, first with an intentional failure then with a complete execution of each phase.  The end result should be a completed train.
Failures are created by monkey patching to throw exceptions.  Approximately 15 mins is added to the testing time for the optional and nightly large test.
**Checklist:**
> Phased training test

- requirements.txt
> deps: cap instructlab libraries for 0.20 release

- scripts/functional-tests.sh
- src/instructlab/cli/model/serve.py
- src/instructlab/model/backends/common.py
- tests/test_backends.py
- tests/test_config.py
llama-cpp was switched to llama_cpp but only in certain parts of the codebase making it hard for users to specify the backend they want to use.
Switch all instances of llama_cpp backend type back to llama-cpp
**Checklist:**
> llama backend fix

- .spellcheck-en-custom.txt
- README.md
**Description:** Going through the InstructLab readme and consolidating, restructuring and rewording some content.
The preview might help with checking out the formatting: 
- https://github.com/kelbrown20/kelly-instructlab/tree/revamp-readme
> [Docs] Revamping the InstructLab README

- CHANGELOG.md
- src/instructlab/profiles/intel/gaudi/gaudi_3.yaml
- tests/test_lab_init.py
Adds a Intel Gaudi 3 config schema to the CLI.
**Checklist:**
> Introduce config schema for Intel Gaudi

- src/instructlab/profiles/apple/m1/m1_max.yaml
- src/instructlab/profiles/apple/m1/m1_ultra.yaml
- src/instructlab/profiles/apple/m2/m2_max.yaml
- src/instructlab/profiles/apple/m2/m2_ultra.yaml
- src/instructlab/profiles/apple/m3/m3_max.yaml
- src/instructlab/profiles/nvidia/a100/a100_x2.yaml
- src/instructlab/profiles/nvidia/a100/a100_x4.yaml
- src/instructlab/profiles/nvidia/a100/a100_x8.yaml
- src/instructlab/profiles/nvidia/h100/h100_x2.yaml
- src/instructlab/profiles/nvidia/h100/h100_x4.yaml
- src/instructlab/profiles/nvidia/h100/h100_x8.yaml
- src/instructlab/profiles/nvidia/l4/l4_x8.yaml
- src/instructlab/profiles/nvidia/l40s/l40s_x4.yaml
- src/instructlab/profiles/nvidia/l40s/l40s_x8.yaml
the default device is CPU so for Mac we need to set MPS and for Nvidia we need to set CUDA
**Checklist:**
> fix: add proper devices to profiles

- .spellcheck-en-custom.txt
- CONTRIBUTING/CONTRIBUTING.md
- CONTRIBUTING/FIRST_TIME_CONTRIBUTORS.md
Trying to improve the contribution doc about the `tox` usage
**Checklist:**
> update tox usage

- README.md
**Description:** This PR moved the upgrade docs so its in a easier to spot place. Also adding a recommendation to run `ilab config init` after upgrading.
> [Docs] Highlight InstructLab upgrading and reinitializing

- README.md
New format in [2569](https://github.com/instructlab/instructlab/pull/2569), so update it in `README.md`
**Checklist:**
> format the download example output

- README.md
> miss the terminal word

- .github/mergify.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- src/instructlab/profiles/intel/gaudi/gaudi_3.yaml
the default device in the config is CPU,
this overrides with HPU for Intel Gaudi
**Checklist:**
> add device field for intel gaudi config

- README.md
**Description:** Update InstructLab readme to reflect the new auto detection feature and system profiles
**Preview:** https://github.com/kelbrown20/kelly-instructlab/tree/system-profiles-readme?tab=readme-ov-file#%EF%B8%8F-initialize-ilab
System profiles dev PR: #2495 (Merged) 
Auto detection dev PR: #2572 (Merged)
> [Docs] Update documentation for system profiles and auto detection

- src/instructlab/config/show.py
- tests/test_lab_config.py
- add --without-comments option and it will remove the comments from the show output, and make it easy to view
```
$ ilab config show --help
Usage: ilab config show [OPTIONS]
Displays the current config as YAML with an option to extract a specific
key.
Options:
-k, --key TEXT          Show only a specific section of the configuration,
e.g., -k chat or -k chat.context
-wc, --without-comments  Show the config without comments. Can be used in
conjunction with -k.
--help                  Show this message and exit.
chat:
context: default
greedy_mode: false
logs_dir: /root/.local/share/instructlab/chatlogs
max_tokens:
....
chat:
context: default
greedy_mode: false
logs_dir: /root/.local/share/instructlab/chatlogs
max_tokens:
model: /root/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf …
```
> add --without-comments option for show

- src/instructlab/config/init.py
Intel returns Intel(r) for their CPUs, so we need to do a more general check than strict matching `intel`.
Also, add a [0] option for profiles that just sets the pydantic defaults. It is unclear who would get into this scenario with the auto-detection working
but if a user is running on such a system, the pydantic defaults might just be what they're looking f
resolves #2608 
**Checklist:**
> Fix Intel Auto-Detection and Profile Selection Menu

- scripts/test-data/profile-l40s-x4.yaml
> fix model path in L40s-x4 test profile

- requirements.txt
- src/instructlab/data/generate_data.py
SDG 0.5.0 is out, 0.21 will be based off of this, bump the version
**Checklist:**
> bump SDG minimum version

- src/instructlab/config/init.py
FROM:
```
Please choose a system profile.
Profiles set hardware-specific defaults for all commands and sections of the configuration. <<<<
First, please select the hardware vendor your system falls into
```
TO
```
Please choose a system profile.
Profiles set hardware-specific defaults for all commands and sections of the configuration. <<<<
First, please select the hardware vendor your system falls into
```
**Checklist:**
> remove the space in init

- README.md
- docs/instructlab_models.md
**Description:** There were some details in the LLM guide that were not accurate, updating so its up to date
> [Docs] Update the LLM guide

- CHANGELOG.md
add information about full training and sdg optimizations
**Checklist:**
> update changelog for 0.21 release

- requirements.txt
Bump SDG minimum version to v0.6.0
**Checklist:**
> Bump minimum SDG version to v0.6.0

- src/instructlab/cli/data/generate.py
- src/instructlab/configuration.py
- src/instructlab/model/chat.py
- src/instructlab/utils.py
This PR adds the ability to detect the architecture of a GGUF model file - which would allow GGUF models to get the appropriate system prompt based on their architecture
**Checklist:**
> feat: detect gguf model arch

- requirements.txt
> deps: cap dependencies for 0.21 release

- .github/workflows/e2e-nvidia-l40s-x4.yml
Replaces https://github.com/instructlab/instructlab/pull/2663
Includes the changes required for our slack actions.
**Checklist:**
> Adjust to slack-github-action 2.0 api changes

- README.md
Merged [2610](https://github.com/instructlab/instructlab/pull/2610), so update the description.
**Checklist:**
> update the config show cmd description

- README.md
A user in #users explained they tried to swap out the SDG teacher model with a different model. We have a command for model path for ilab sdg generate, but it isnt clear in our docs that only mistral and mixtral (and merlinite in simple pipeline) are compatible. 
Not knowing this could cause a user frustration.
**Checklist:**
> make a note of SDG supported model types

- README.md
Check the datasets files whether generated with `ilab data list` cmd.
**Checklist:**
> update data list output

- docs/PROMPTING-FAQ.md
This new FAQ document provides guidance on improving model responses when they fail to return desired results. It includes a detailed example that demonstrates how adding context can help the model produce accurate answers.
Resolves https://github.com/instructlab/instructlab/issues/2596 (part of the issue)
**Checklist:**
> Add Prompting FAQ for troubleshooting model responses

- .github/workflows/e2e-aws-custom.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
This is to help debugging disk space issues
**Checklist:**
> Add disk check after tests run

- scripts/infra/cloud-instance.sh
> Update to latest ami default volume size

- scripts/e2e-ci.sh
the github action was cleaning up the ilab artifacts
even if we preserved the E2E test dir
add disk checks into the script itself for more
granular checking + benefiting the libraries
**Checklist:**
> ci: add disk check to script

- README.md
It seems that only those who are aware of the changed PR will know about this change. So add the note in `README.md`.
**Checklist:**
> add hf_transfer

- src/instructlab/config/init.py
- src/instructlab/configuration.py
- src/instructlab/profiles/amd/cpu.yaml
- src/instructlab/profiles/apple/m1/m1_max.yaml
- src/instructlab/profiles/apple/m1/m1_ultra.yaml
- src/instructlab/profiles/apple/m2/m2.yaml
- src/instructlab/profiles/apple/m2/m2_max.yaml
- src/instructlab/profiles/apple/m2/m2_pro.yaml
- src/instructlab/profiles/apple/m2/m2_ultra.yaml
- src/instructlab/profiles/apple/m3/m3.yaml
- src/instructlab/profiles/apple/m3/m3_max.yaml
- src/instructlab/profiles/apple/m3/m3_pro.yaml
- src/instructlab/profiles/intel/cpu.yaml
- src/instructlab/profiles/intel/gaudi/gaudi_3.yaml
- src/instructlab/profiles/nvidia/a100/a100_x2.yaml
- src/instructlab/profiles/nvidia/a100/a100_x4.yaml
- src/instructlab/profiles/nvidia/a100/a100_x8.yaml
- src/instructlab/profiles/nvidia/h100/h100_x2.yaml
- src/instructlab/profiles/nvidia/h100/h100_x4.yaml
- src/instructlab/profiles/nvidia/h100/h100_x8.yaml
- src/instructlab/profiles/nvidia/l4/l4_x8.yaml
- src/instructlab/profiles/nvidia/l40s/l40s_x4.yaml
- src/instructlab/profiles/nvidia/l40s/l40s_x8.yaml
- tests/test_lab_init.py
- tests/testdata/default_config.yaml
Metadata is meant to store specific information about what type of system this configuration should apply to, namely GPU information. This is a better and more maintainable heuristic for system profiles as we scale the amount of systems we want to automatically apply configurations to
**Checklist:**
> Introduce Metadata to the config.yaml

- src/instructlab/config/init.py
- tests/test_lab_init.py
currently we update full_chip_name in each iteration of the sku checking loop. Do this outside of the loop so things like PCIe do not print in the menu
**Checklist:**
> Do not store SKU in printed menu

- pyproject.toml
**Dev Docs related to this Pull Request:**
Link to Dev Doc or PR: https://github.com/instructlab/dev-docs/blob/main/docs/instructlab-cli-1.0.0.md
**Checklist:**
> core: update project description

- scripts/e2e-ci.sh
- src/instructlab/config/init.py
> Fixing typo

- requirements.txt
> deps: Cap dependencies for 0.22 release

- src/instructlab/cli/data/generate.py
- src/instructlab/configuration.py
- src/instructlab/utils.py
- tests/testdata/default_config.yaml
Adds option to select legacy template in the general section of the config.
Solves #2790 
**Checklist:**
> Add legacy template override option to general config

- CHANGELOG.md
> update CHANGELOG for serve

- .github/ISSUE_TEMPLATE/team_recommend.md
> fix: update nomination template from "CLI" to "Core"

- src/instructlab/config/init.py
- src/instructlab/profiles/nvidia/a100/a100_x2.yaml
- src/instructlab/profiles/nvidia/a100/a100_x4.yaml
- src/instructlab/profiles/nvidia/a100/a100_x8.yaml
- src/instructlab/utils.py
- tests/test_lab_init.py
the A100 profile SKUs need to match the ones here: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/main/src/nvidia/generated/g_nv_name_released.h
**Checklist:**
> amend A100 profile SKUs

- scripts/ilab-macos-installer.sh
Some users might need `sudo` to set the soft link, so it will fail after install. To make it fluently, it will use `the whole path` to run the next steps.
https://github.com/instructlab/instructlab/pull/2419#discussion_r1890165605
**Checklist:**
> handle the /usr/local/bin no permission issue

- src/instructlab/cli/data/generate.py
- src/instructlab/cli/model/train.py
- src/instructlab/model/accelerated_train.py
- src/instructlab/model/convert.py
- src/instructlab/model/evaluate.py
- src/instructlab/model/test.py
- tests/test_lab_evaluate.py
for [2740](https://github.com/instructlab/instructlab/issues/2740)
**Checklist:**
> add success messages for generate train convert evaluate test cmds

- .spellcheck-en-custom.txt
- README.md
Adds missing instructions on how to download OCI models. Also fixes formatting issue in the same section.
**Checklist:**
> docs: add documentation around OCI downloads

- src/instructlab/model/serve_backend.py
An incorrect  log for backend_type was introduced, fix the log to display the proper info
**Checklist:**
> fix backend_type log

- CHANGELOG.md
- README.md
- src/instructlab/cli/model/upload.py
- src/instructlab/model/upload.py
- src/instructlab/utils.py
- tests/test_lab_upload.py
Resolves #2555 
**Checklist:**
> feat: add OCI support to `ilab model upload`

- src/instructlab/model/backends/common.py
Issue resolved by this Pull Request:
Resolves https://github.com/instructlab/instructlab/issues/2853
**Checklist:**
> fix the warning when the model is a file type

- scripts/functional-tests.sh
- src/instructlab/configuration.py
Resolves https://github.com/instructlab/instructlab/issues/2792
https://github.com/instructlab/instructlab/blob/main/src/instructlab/configuration.py#L1315
```
if config_obj is None and "--help" in sys.argv[1:]:  # config_obj will not None, so cannot handle the help situation
config_obj = get_default_config()
error_msg = None
```
Before:
```
$ ilab --config=/tmp/test-test.yaml model evaluate --help
Usage: ilab model [OPTIONS] COMMAND [ARGS]...
Try 'ilab model --help' for help.
Error: `/tmp/test-test.yaml` does not exist or is not a readable file.
Please run `ilab config init` or point to a valid configuration file using `--config=<path>`.
```
after:
```
$ ilab --config=test-test.yaml model evaluate --help
Usage: ilab model evaluate [OPTIONS]
Evaluates a trained model
Options:
--model TEXT …
```
> handle the help situation if config lacks

- src/instructlab/cli/model/train.py
Based on the comment https://github.com/instructlab/instructlab/issues/2698#issuecomment-2506676655 and the code https://github.com/instructlab/instructlab/blob/main/src/instructlab/cli/model/train.py#L429
the Strategies only worked with `accelerated` pipeline, the better `UX` should tell users, not just show the `fail message`.
**Checklist:**
> add a description in cmd option

- docs/ci.md
- scripts/e2e-ci.sh
> docs: fix CI documentation around X-Large flag

- CONTRIBUTING/CONTRIBUTING.md
Resolves https://github.com/instructlab/instructlab/issues/1623
based on: https://github.com/instructlab/instructlab/pull/1622
**Checklist:**
> add debug options in CONTRIBUTING.md

- README.md
Since we renamed `CLI` to `Core`, let's start by updating the README and initialization code as a beginning.
**Checklist:**
> update Core for README and init

- src/instructlab/cli/model/train.py
Checking `train` , only `pipeline simple` use `--local`, but users thought they all works, so add tips for it.
https://github.com/instructlab/instructlab/issues/2837
**Checklist:**
> add tips for --local option usage

- scripts/e2e-ci.sh
From `taxomony ` to `taxomomy `
**Checklist:**
> fix the taxonony to taxonomy

- CHANGELOG.md
- README.md
- pyproject.toml
- requirements.txt
- src/instructlab/cli/model/upload.py
- src/instructlab/model/upload.py
- src/instructlab/utils.py
- tests/test_lab_upload.py
> feat: add S3 support to `ilab model upload`

- src/instructlab/model/backends/vllm.py
- src/instructlab/model/evaluate.py
Based on https://github.com/instructlab/instructlab/pull/2927#discussion_r1920180818
```
$ python test-test.py
prefix:  --foo
args:  ['--foo', '4']
flag:  True
value:  4
$ python test-test.py
prefix:  --foo
args:  ['--foo', '4', '--foo']
flag:  True
value:  None
$ python test-test.py
prefix:  --foo
args:  ['--foo', '--foo']
flag:  True
value:  None
$ python test-test.py
prefix:  --foo
args:  ['--foo', '4', '--foo=2']
flag:  True
value:  2
$ python test-test.py
prefix:  --foo
args:  ['foo']
flag:  False
value:  None
```
**Checklist:**
> Improvement to get_argument

- src/instructlab/model/convert.py
- tests/test_lab_model_convert.py
Resolves # https://github.com/instructlab/instructlab/issues/2800
**Checklist:**
> fix model_name miss

- tests/test_backends.py
For https://github.com/instructlab/instructlab/pull/2939#pullrequestreview-2561042995
**Checklist:**
> add a test for get_argument

- pyproject.toml
- src/instructlab/cli/model/chat.py
- src/instructlab/model/backends/backends.py
- src/instructlab/model/chat.py
- tests/test_lab_config.py
Refactored click command handling into a dedicated `cli` module and moved the core chat functionality into a separate module. This restructing lays the groundwork for future API handlers and multi-processing work.
**Checklist:**
> split `ilab model chat` click cmds from functionality

- src/instructlab/cli/model/chat.py
- src/instructlab/configuration.py
- src/instructlab/defaults.py
- src/instructlab/model/chat.py
- tests/test_lab.py
- tests/test_model_chat.py
- tests/testdata/default_config.yaml
Resolves #2876 
Depends on #2832 
Dev doc: https://github.com/instructlab/dev-docs/pull/161
**Checklist:**
> feat: Retrieval augmented generation for chat

- .github/actions/free-disk-space/action.yml
- .github/workflows/e2e-nvidia-l40s-x8.yml
- scripts/e2e-ci.sh
Resolves #2915
**Checklist:**
We periodically run into insufficient disk space issues in the CI. These disk space issues are commonly caused by:
A. Our E2E runner running out of disk space. Example:
([Link to log file source](https://github.com/instructlab/instructlab/actions/runs/12891882950/job/35945158959))
B. Our GitHub runner running out of disk space. Example:
([Link to log file source](https://github.com/instructlab/instructlab/actions/runs/12753745982))
This PR resolves the above issues by:
1. Performing disk cleanups to remove unused, unnecessary packages from our GitHub and EC2 runners.
2. Disabling the generation of checkpoint states triggered during our …
> fix: Resolve insufficient disk space issues in XL e2e job

- README.md
update download output in README.md
**Checklist:**
> update download output in README.md

- .github/workflows/e2e-aws-custom.yml
> fix: align E2E custom job install steps to other jobs

- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
> ci: openai api_key feeds into medium and large jobs

- src/instructlab/cli/model/chat.py
miss the help info:
https://github.com/instructlab/instructlab/blob/main/src/instructlab/cli/model/chat.py#L105
```
from:
$ ilab model chat --help|grep rag
--rag
to:
$ ilab model chat --help|grep rag
--rag                           To enable the RAG pipeline.
```
**Checklist:**
> add the help info for --rag

- requirements.txt
- requirements/cuda.txt
- requirements/hpu.txt
- requirements/rocm.txt
> deps: bump instructlab libraries for 0.23.0 release

- scripts/infra/cloud-instance.sh
Otherwise, multiple ids are extracted, then parsed as a single id. This
makes the script complain about InvalidInstanceID.Malformed:
An error occurred (InvalidInstanceID.Malformed) when calling the
DescribeInstances operation: Invalid id: "instance-id-1 instance-id-2"
**Checklist:**
> infra: When extracting instance-id, ignore terminated instances

- .github/workflows/e2e-aws-custom.yml
> fix: add HF_TOKEN and OPENAI_API_KEY env vars to custom job

- CHANGELOG.md
> feat(RAG): Announce RAG in CHANGELOG.md

- .spellcheck-en-custom.txt
- README.md
> feat(RAG): Provide RAG instructions in README.md

- requirements.txt
> deps: cap dependencies for 0.23.0 release

- CHANGELOG.md
For https://github.com/instructlab/instructlab/pull/2844
**Checklist:**
> update --skip-server for evaluate in CHANGELOG.md

- src/instructlab/model/chat.py
Since the README.md updated, It should be easy to set or copy-paste for the users if they forgot to set it permanent with below changed.
```
change from:
$ ilab model chat --rag
ERROR 2025-01-28 15:59:51,153 instructlab.model.chat:591: 
This functionality is experimental; set ILAB_FEATURE_SCOPE to "DevPreviewNoUpgrade" to enable.
to:
$ ilab model chat --rag
ERROR 2025-01-28 16:05:40,942 instructlab.model.chat:595: 
This functionality is experimental; run "export ILAB_FEATURE_SCOPE=DevPreviewNoUpgrade" command to enable.
```
**Checklist:**
> update rag enable prompt

- src/instructlab/model/download.py
- src/instructlab/model/list.py
- src/instructlab/utils.py
- tests/test_lab_model_list.py
Model list now includes absolute path to each model. 
This will save some time, since the path is required as argument during local chatting and other applications.
AnalyzeModelResult is now a dataclass, rather than a tuple. This allows for named fields and improves readability.
**Checklist:**
> feat: Improving model list output

- README.md
Also add <version> to the python commands for Linux install instructions.
**Checklist:**
> Make it more clear in the README doc that python 3.12+ is not yet supported

- .github/workflows/test.yml
Required to fix https://github.com/instructlab/instructlab/pull/3051
**Checklist:**
> fea: Injected hf_token in test job

- .github/workflows/test.yml
Removed injection of HF token.
**Checklist:**
> fix: Reverting previous change to test job

- .github/workflows/e2e-nvidia-l4-x1.yml
Avoids more complicated changes to avoid using HF_TOKEN.
**Checklist:**
> Disable medium test by default with older release branches

- .yamllint.yaml
- tests/testdata/sample_taxonomy/compositional_skills/howdy/qna.yaml
This makes locally running newly introduced yamllint possible, while also resolving an ongoing CI issue.
**Checklist:**
> fix: Reformatted file to comply with yamllint reqs

- README.md
- docs/README.md
While working with instructlab I've found couple of issues in the documentation.
**Checklist:**
> Fix documents

- src/instructlab/cli/model/download.py
- src/instructlab/cli/process/attach.py
- src/instructlab/cli/process/list.py
```
$ ilab process --help
Usage: ilab process [OPTIONS] COMMAND [ARGS]...
Command group for interacting with the processes run by InstructLab.
If this is your first time running ilab, it's best to start with `ilab
config init` to create the environment.
Options:
--help  Show this message and exit.
Commands:
attach <<<<<<<<<
list <<<<<<<<<
Commands:
chat      Runs a chat using the modified model
convert   Converts model to GGUF
download       <<<<<<<<<
evaluate  Evaluates a trained model   
```
**Checklist:**
> miss the help info for download attach list

- README.md
Putting example of new `ilab model list` output into README
**Checklist:**
> Amending ilab model list output example

- README.md
create a symlink for ilab after installation, e.g.
```
ln -s /path/venv/bin/ilab /usr/local/bin/ilab
```
then, no need to source to the venv every time.
**Checklist:**
> create a symlink for ilab after installation

- README.md
Seems the `docs/instructlab_models.md` updated, so changed to `docs/user/instructlab_models.md`
**Checklist:**
> update the models doc link in README.md

- requirements.txt
> deps: Cap dependencies for 0.24.0 release

- .github/mergify.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- .github/workflows/test.yml
We'd like to see if disabling spell check will make us agregeously
ilitarate. ;) If the experiment doesn't go well, we can revert this
patch later.
This is a follow-up to https://github.com/instructlab/instructlab/pull/3130
**Checklist:**
> ci: disable spell check

- pyproject.toml
- src/instructlab/cli/process/list.py
- src/instructlab/data/generate_data.py
- src/instructlab/defaults.py
- src/instructlab/process/process.py
- tests/process/test_process.py
- tests/test_lab_process_attach.py
- tests/test_lab_process_list.py
Resolves https://github.com/instructlab/instructlab/issues/3081
**Checklist:**
> feat: add --state option to filter process list output

- src/instructlab/model/serve_backend.py
- tests/common.py
Resolves https://github.com/instructlab/instructlab/issues/2286
**Checklist:**
> add a sanity check for tensor-parallel-size

- src/instructlab/rag/haystack/component_factory.py
**Checklist:**
Margify failed to cherry pick this commit due to multiple merge commits. See below:
https://github.com/instructlab/instructlab/pull/3064#issuecomment-2663126721
Manually cherry picking and adding...
> [backport] skipping docs with same ID by default

- README.md
This PR updates the **Install with Nvidia CUDA** section in the README to prevent installation failures caused by missing dependencies.
Users attempting to install `instructlab[cuda]` may encounter the following errors:
- `ModuleNotFoundError: No module named 'torch'`
- `ModuleNotFoundError: No module named 'psutil'`
- Updated the installation steps to explicitly install `torch` and `psutil` **before** running `pip install instructlab[cuda]`.
- Ensured that these dependencies are in place to prevent package resolution failures.
- Modified the **Install with Nvidia CUDA** section in README to include:
```bash
pip install torch psutil
```
before installing `instructlab[cuda]`.
---
Resolves # (Add issue number if applicable)
---
1. Set up a fresh …
> Fix: Add missing `torch` and `psutil` dependencies to CUDA installation instructions

- CHANGELOG.md
Since https://github.com/instructlab/instructlab/pull/3125 merged, so updated it.
**Checklist:**
> docs: update a feat change

- scripts/infra/cloud-instance.sh
- **feat(infra): allow to pass instance id with -i in cloud-instance.sh**
**Checklist:**
> feat(infra): add -i option for instance id to cloud-instance.sh

- CONTRIBUTING/CONTRIBUTING.md
Corrected two broken links in CONTRIBUTING/CONTRIBUTING.md
**Checklist:**
> docs: corrected broken links

- .spellcheck-en-custom.txt
- README.md
- docs/user/dk_bench.md
- docs/user/index.rst
- src/instructlab/model/dk_bench_utils.py
- tests/test_lab_evaluate.py
> docs: Add DK-Bench docs

- src/instructlab/model/chat.py
**Checklist:**
No need the parameter for `get_cli_helper_sysprompt`.  [2729](https://github.com/instructlab/instructlab/issues/2729)
```
def get_cli_helper_sysprompt() -> str:
"""
Returns the system prompt to put the chatbot in CLI helper mode
"""
return CLI_HELPER_SYS_PROMPT
```
[2730](https://github.com/instructlab/instructlab/issues/2730), make sure mode_path is `PATH`
> fix cannot change context in cli issue

- docs/conf.py
- src/instructlab/cli/data/generate.py
- src/instructlab/cli/model/chat.py
- src/instructlab/cli/model/evaluate.py
- src/instructlab/cli/model/train.py
- src/instructlab/configuration.py
- src/instructlab/model/chat.py
- tests/testdata/default_config.yaml
> Adds support for simple global/general model configuration

- scripts/infra/cloud-instance.sh
> docs: Add MOTD to warn about updating the kernel

- docs/accelerators/gpu-acceleration.md
Old cuda package have been seen to cause updates to fail due to dependency errors
Closes: #3241
**Checklist:**
> Document removing any CUDA packages before Upgrade

- .github/workflows/test.yml
- requirements.txt
- src/instructlab/rag/convert.py
- tests/test_lab_rag_convert.py
- tox.ini
bring changes in https://github.com/instructlab/sdg/pull/574/files to instructlab 
**Checklist:**
> chore: update docling api references

- .github/workflows/test.yml
- requirements.txt
- src/instructlab/rag/convert.py
- tests/test_lab_rag_convert.py
- tox.ini
This is on the path to fix MacOS tests and the gate. It doesn't enable MacOS tests, yet, because functional tests are still failing.
**Checklist:**
> re-introduce the docling fix; fix DISABLE_GPU_ACCELERATION setting via GITHUB_ENV file

- requirements.txt
**Checklist:**
Before we cut a release, we should bump the SDG version in the `requirements.txt` file to ensure that SDG's latest release, which contains important docling bugfixes, gets consumed.
> chore: Bump SDG version to ensure the latest docling changes are consumed

- src/instructlab/cli/data/generate.py
- src/instructlab/cli/model/train.py
- src/instructlab/configuration.py
- tests/common.py
- tests/test_lab_generate.py
- tests/testdata/default_config.yaml
allow setting a global student and teacher model id in the config, which can be overridden by cmd args 
**Checklist:**
> pick up model id defaults from config yaml

- .github/mergify.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
Temporarily disable the small job on PRs until https://github.com/instructlab/instructlab/issues/3289 is investigated 
this is simply to prevent blocking important changes that need to go in 
**Checklist:**
> ci: temporarily disable small job on PRs

- .github/workflows/e2e-nvidia-l40s-x4-llama.yml
- scripts/e2e-ci.sh
- scripts/test-data/profile-l40s-x8-llama.yaml
Adds a new large-sized job specifically to run the llama pipeline. This is also an optional job that should be trigger-able when needed 
**Checklist:**
> ci: add new Llama e2e large sized job 

- README.md
Address https://github.com/instructlab/instructlab/issues/3144#issue-2855799992 by providing a link to Nvidia's developer tool for dowloading CUDA.
Issue resolved by this Pull Request:
Resolves #3144 
**Checklist:**
> provides link to CUDA install via Nvidia: fixes issue 3144

- .github/workflows/test.yml
- .pylintrc
- CHANGELOG.md
- CONTRIBUTING/CONTRIBUTING.md
- README.md
- docs/maintainers/ci.md
- pyproject.toml
- scripts/ilab-macos-installer.sh
- src/instructlab/model/evaluate.py
- tests/test_macos_install.py
- tests/test_package.py
- tox.ini
> chore: Remove python 3.10 support

- src/instructlab/configuration.py
Before the change, lists of models were not converted to dicts before
passing them to ruamel representor. It broke `config show` when a
`models` section was added to it because the field is s list of
model_info classes.
With this change, we should correctly handle tuples and lists. If we
ever need something else, like dicts, we may expand the serialization
code further.
**Checklist:**
> feat: Handle lists of pydantic models when dumping to yaml

- .github/workflows/e2e-nvidia-l40s-x4-py312.yml
We will need this job to validate that the switch to python 3.12 doesn't
break anything, particularly for dolomite training.
**Checklist:**
> ci: Add e2e-nvidia-l40s-x4 job variant for python 3.12

- src/instructlab/configuration.py
> fix: edit issue

- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4-llama.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
- .github/workflows/e2e-nvidia-l40s-x8.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
Updating to get a better idea over time how much storage is being used and the storage isn't needed after the test
**Checklist:**
> Preserve storage after e2e tests

- .github/workflows/e2e-aws-custom.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4-llama.yml
- .github/workflows/e2e-nvidia-l40s-x4-py312.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
- .github/workflows/e2e-nvidia-l40s-x8.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
Before the change, if test script failed, we couldn't check the final
storage.
This should help with investigation of:
https://github.com/instructlab/instructlab/issues/3298
**Checklist:**
> ci: Always collect df -h stats regardless of failure

- src/instructlab/model/serve_backend.py
since we support HPU and ROCm for inference, we need to gate torch.cuda.device_count since on HPU specificially this will cause issues.
use similar logic as we do in `init.py` to ensure CUDA is available, and HPU/ROCm are not.
**Checklist:**
> fix: properly gate usage of torch.cuda.device_count

- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
This allows to test workflow changes to these jobs before merging them.
Note: this change doesn't include more risky changes like adding inputs
for pr number etc. This is intentional and will be done in a separate PR
when the Run workflow button is available in the UI and we can test
changes to workflows before merging.
**Checklist:**
> ci: enable workflow_dispatch for all e2e jobs, part 1

- .github/mergify.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
> ci: trigger affected jobs on constraints-dev.txt change

- .github/workflows/e2e-aws-custom.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4-llama.yml
- .github/workflows/e2e-nvidia-l40s-x4-py312.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
- .github/workflows/e2e-nvidia-l40s-x8.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
Otherwise, pip may install a version of a package that does not satisfy
the constraints; then fail to honour the constraints because:
```
ERROR: pip's dependency resolver does not currently take into account
all the packages that are installed. This behaviour is the source of the
following dependency conflicts.
```
**Checklist:**
> ci: Force use of constraints file for all `pip install` commands

- scripts/generate_constraints.sh
- tox.ini
> chore: Improve constraints generator - require linux; add tox env

- .github/workflows/docs.yml
E.g. right now changes to docs requirements are not triggering the job.
**Checklist:**
> ci: Trigger docs job on any change under docs/ directory

- .isort.cfg
- .yamllint.yaml
These were moved out of the tree in:
01500fbc67efb3f193d4dfe76d0c77f5fce50197
**Checklist:**
> chore: remove unnecessary skips for files moved to ci-actions

- .github/workflows/constraints-update.yml
- tox.ini
We'll have to merge it before being able to run it...
**Checklist:**
> ci: add workflow to update constraints-dev.txt and create PR weekly

- scripts/generate_constraints.sh
> ci: Include doc dependencies into constraints

- .github/workflows/constraints-update.yml
> ci: Sign off constraints bot patches

- .github/workflows/e2e-aws-custom.yml
- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-l40s-x4-llama.yml
- .github/workflows/e2e-nvidia-l40s-x4-py312.yml
- .github/workflows/e2e-nvidia-l40s-x4.yml
- .github/workflows/e2e-nvidia-l40s-x8.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
- scripts/install-ilab-with-cuda.sh
**Checklist:**
Our workflows are currently copy-pasting the same installation script. This PR removes the common logic from affected workflows and puts it in a separate script with execute permissions.
> feat(ci): Migrate InstructLab CUDA installation logic into a reusable script

- .github/workflows/e2e-nvidia-l4-x1.yml
- .github/workflows/e2e-nvidia-t4-x1.yml
> ci: Run medium/small e2e on install-ilab-with-cuda.sh touched

- constraints-dev.txt
- scripts/generate_constraints.sh
- **chore: Use --constraint for pip-compile**
- **chore: Use pip-compile --strip-extras to remove [...]**
- **chore: Pin "unsafe" packages (used for base packaging)**
- **chore: Include constraint annotations for dependency chains**
**Checklist:**
> Add annotations to constraints and other adjustments

- requirements-dev.txt
- requirements.txt
If any libraries need a constraint, a constraint file should be used to
pin in CI. In the worst scenario, broken versions can be excluded with
`!=` condition.
We now constrain all dependencies, so it's safe to do so.
**Checklist:**
> chore: Uncap all dependencies

- scripts/install-ilab-with-cuda.sh
Otherwise, torch versions may differ, which results in all kinds of
pain.
**Checklist:**
> ci: Build flash-attn with same package versions as used in runtime

- constraints-dev.txt
- notebooks/Training_a_LoRA_With_Instruct_Lab.ipynb
- requirements-dev.txt
- scripts/generate_constraints.sh
- src/instructlab/cli/model/serve.py
- src/instructlab/llamacpp/llamacpp_convert_to_gguf.py
- src/instructlab/model/backends/vllm.py
- src/instructlab/model/chat.py
- src/instructlab/model/dk_bench_utils.py
- src/instructlab/train/lora_mlx/lora.py
- src/instructlab/train/lora_mlx/make_data.py
- tests/test_config.py
- tests/test_lab.py
- tests/test_lab_download.py
- tests/test_lab_evaluate.py
- tests/test_lab_rag_convert.py
- tests/test_lab_serve.py
- tests/test_lab_upload.py
- tox.ini
Note to reviewers: I recommend to review [with whitespaces ignored](https://github.com/instructlab/instructlab/pull/3427/files?diff=unified&w=1). Most changes are automatic (from `ruff`).
**Checklist:**
> chore: Bump ruff and isort; move pins to constraints file

- containers/README.md
Added content for container file dependencies
**Checklist:**
- [ x] **Commit Message Formatting**: Commit titles and messages follow guidelines in the
- [x ] Documentation has been updated, if necessary.
> docs: Update README.md for dependencies #3431

- constraints-dev.txt
- constraints-dev.txt.in
This PR updates the constraints-dev.txt file using `tox -e constraints`.
> chore: update constraints-dev.txt (2025-06-02)

- tox.ini
> tox: Fail when interpreter is missing (don't just skip with rc=0)

- constraints-dev.txt
- constraints-dev.txt.in
- pyproject.toml
This PR updates the constraints-dev.txt file using `tox -e constraints`.
> chore: update constraints-dev.txt (2025-06-16)

- .pylintrc
- pyproject.toml
- scripts/test-data/profile-l40s-x8-llama.yaml
- src/instructlab/cli/model/train.py
- src/instructlab/defaults.py
- tox.ini
It's being removed in training library.
See: https://github.com/instructlab/training/pull/616
**Checklist:**
> fix: Remove dolomite support

- constraints-dev.txt
This PR updates the constraints-dev.txt file using `tox -e constraints`.
> chore: update constraints-dev.txt (2025-06-23)
